facebook/zstd

programs/bench.c
programs/util.h
programs/zstdcli.c
zlibWrapper/.gitignore
zlibWrapper/Makefile
zlibWrapper/README.md
zlibWrapper/examples/example.c
zlibWrapper/examples/example_original.c
zlibWrapper/zstd_zlibwrapper.c
zlibWrapper/zstd_zlibwrapper.h

bench.c: experimental -r (operate recursively on directories) for Windows and _POSIX_C_SOURCE >= 200112L

added zlibWrapper - zstd wrapper for zlib

---

lib/compress/huf_compress.c
lib/compress/zbuff_compress.c
programs/xxhash.c

spelling-fixes, as of lintian.debian.org

---

tests/test-zstd-speed.py

- support for ~ in filenames
- result files ending with .txt

test-zstd-speed.py: added --message in start and finish e-mail

---

programs/Makefile

Add OpenBSD to the Makefile test.

---

zstd.rb

I am not sure how popular zstd is yet, thus we can have this Brew formula live here until the brew team accepts it in their repo.
Feedback welcome.

Adding brew formula for easy install

---

zstd.rb

Tested locally, installed 0.7.4 as expected.

Update brew for 0.7.4

---

lib/legacy/zstd_v04.c

ZSTD_decompressDCtx was undefined.

Fix compile issue with ZSTD_LEGACY_SUPPORT=1 and ZSTD_HEAPMODE=0

---

zstd_compression_format.md

a lot of changes in formating and naming of variables

improved zstd_compression_format.md

---

README.md

The repository was moved, update the links.

Fix build status images

---

.travis.yml
contrib/pzstd/Makefile
contrib/pzstd/Options.cpp
contrib/pzstd/test/Makefile
contrib/pzstd/utils/Range.h
contrib/pzstd/utils/test/Makefile

There were small issues with flags and missing includes.

Pzstd should now compile with gcc

---

.travis.yml
contrib/pzstd/ErrorHolder.h
contrib/pzstd/Makefile
contrib/pzstd/Options.cpp
contrib/pzstd/SkippableFrame.cpp
contrib/pzstd/test/OptionsTest.cpp
contrib/pzstd/utils/WorkQueue.h
contrib/pzstd/utils/test/Makefile
contrib/pzstd/utils/test/WorkQueueTest.cpp

Fix problems 1 and 2 of issue #331.
Add building pzstd to the travis-ci build.
Add ability to limit size of the maximum size of a WorkQueue to prepare to fix problem 3.

[pzstd] linux build and CLI fixes

---

index.html

Hi,
I've just uploaded the Perl binding to zstd.
https://metacpan.org/release/Compress-Zstd
Can you please update the document?

Add Perl binding

---

contrib/pzstd/README.md

Update README to reflect the new CLI.

[pzstd] Update README

---

examples/Makefile
programs/fileio.c
programs/zstdcli.c
tests/Makefile

Remove references to GPLv2 license

---

contrib/pzstd/Makefile
lib/Makefile

This should fix the build, but we'll see what CI says.

The static library was moved to libzstd.a

---

lib/legacy/zstd_v05.c
lib/legacy/zstd_v06.c

Introduced by bb68062c590dbd46905907dd2a63a658040a79d4.

Fix bug in zstd v0.{5, 6} dictionary decompression

---

contrib/pzstd/Pzstd.cpp
contrib/pzstd/Pzstd.h

* No longer reduce the frame size for small files.
* Add some verbose logging.

[pzstd] Fix small file frame size

---

zlibWrapper/examples/minigzip.c
zlibWrapper/gzclose.c
zlibWrapper/gzguts.h
zlibWrapper/gzlib.c
zlibWrapper/gzread.c
zlibWrapper/gzwrite.c

Zlibwrapper

---

zlibWrapper/.gitignore
zlibWrapper/zstd_zlibwrapper.c

added the totalInBytes flag - we need it as strm->total_in can be reset by user

fix for zlibWrapper

---

lib/compress/zstdmt_compress.c
lib/compress/zstdmt_compress.h
programs/fileio.c
programs/fileio.h
programs/zstdcli.c
tests/zstreamtest.c

Taking into account notifications from asana and github issue board

zstdmt refinements

---

programs/zstd.1

Tested with `make install && man zstd` and visual inspection.

Add cover dictionary training to zstd.1

---

.travis.yml
Makefile
NEWS
lib/Makefile
programs/.gitignore
programs/Makefile
programs/fileio.c

Make .gz decoding support default for `zstd`

Gzstd default

---

appveyor.yml
programs/platform.h
programs/util.h

fixed "mingw32" AppVeyor target

---

lib/common/mem.h
lib/common/threading.h
lib/compress/huf_compress.c
lib/compress/zstd_compress.c
lib/compress/zstd_opt.h
lib/decompress/huf_decompress.c
lib/decompress/zstd_decompress.c
lib/zstd.h

spelling fixes in comments

---

lib/compress/fse_compress.c

A bug in FSE_normalizeM2 could cause a divide by 0 in some corner cases.  Tests added in Cyan4973/FiniteStateEntropy#79.

Fix bug in FSE distribution normalization

---

tests/decodecorpus.c

https://travis-ci.org/facebook/zstd/jobs/204423280
Fix tested using `gcc -m32`.

Fix 32-bit -Wsign-compare issues in decodecorpus.c

---

README.md

Added the complete name of the tool for Windows i.e. Visual Studio

Fix for a small typo

---

tests/decodecorpus.c

https://travis-ci.org/facebook/zstd/jobs/204807461
Can't get them to reproduce the compile errors locally,
tested fix by forcing that test to run on Travis.

Fix some more ARM compile errors

---

lib/common/fse_decompress.c
lib/decompress/huf_decompress.c
lib/decompress/zstd_decompress.c
programs/fileio.c
tests/fuzzer.c
tests/playTests.sh

saved ~128KB (from ~150KB to ~20KB)

Improved DDict memory usage

---

lib/dictBuilder/cover.c

Thanks to @nemequ for reporting the resource leaks.

Fix COVER_optimizeTrainFromBuffer() resource leaks

---

.travis.yml

https://travis-ci.org/facebook/zstd/jobs/208502754

Fix travis test broken by Makefile change

---

.travis.yml
Makefile
TESTING.md
appveyor.yml
tests/Makefile

Also turn off appveyor tests on feature branches.

Add medium tests on TravisCI

---

tests/fuzzer.c
tests/zstreamtest.c

Fixes https://travis-ci.org/facebook/zstd/jobs/211257353

Prevent fuzz testers from combining large dicts with high clevel

---

Makefile
tests/Makefile
tests/fuzzer.c
tests/zstreamtest.c

Aim to fix test timeouts on Travis, e.g. https://travis-ci.org/facebook/zstd/jobs/212897352

Strongly limit compression level when source is large for tests running on QEMU

---

doc/educational_decoder/zstd_decompress.c

Small changes trying to reduce chance of confusion

Educational decoder polish updates

---

programs/zstdcli.c

Fixes same issue as https://github.com/lz4/lz4/pull/341

Ignore extension in command name matching

---

lib/dictBuilder/zdict.c

Minor improvements :
- slightly better dictionary generation, by removal of some detectable duplicates
- fixed one case of dictionary generation failure

Legacy dict builder

---

tests/test-zstd-speed.py

Better compatibility with Mac OS-X
Force attribution to a selected core # (Linux)

Improved speed tests

---

programs/fileio.c
programs/platform.h
programs/zstdcli.c

Turn off sparse mode for OS X by default

---

.travis.yml

Don't merge until travis tests pass

Install liblzma on OS X long test

---

examples/simple_compression.c
examples/streaming_compression.c
examples/streaming_decompression.c

unchecked argv[idx] access

---

contrib/linux-kernel/README.md
contrib/linux-kernel/squashfs-benchmark.sh

Take patch from PR #682 by @iburinoc and update benchmarks.

[kernel] Update README with SquashFS patch

---

README.md

Fixes some minor grammar issues.

Minor grammatical changes

---

tests/roundTripCrash.c

- change crash function to call abort when fuzzer library is being used

Improve roundTripCrash

---

contrib/linux-kernel/lib/zstd/compress.c
contrib/linux-kernel/test/DecompressCrash.c
contrib/linux-kernel/test/Makefile
contrib/linux-kernel/test/RoundTripCrash.c
contrib/linux-kernel/xxhash_test.c
contrib/linux-kernel/zstd.diff
contrib/linux-kernel/zstd_compress_test.c
contrib/linux-kernel/zstd_decompress_test.c

* Port libzstd UBSAN fix to the linux kernel zstd
* Add round trip and decompression libfuzzer targets
* Add in-kernel tests for xxhash and zstd via a special character device

[linux] Add more tests and fuzzing

---

programs/fileio.c

- changed error code for when file cannot be opened
- reversed the calculation of ratio

Patching ratio and non-existent file bugs

---

lib/decompress/zstd_decompress.c

* `ZSTD_decompressStream_generic()` `ip` may be `NULL` for one of the calls
to `memcpy()`
* Assert the source is not `NULL` for calls to `memcpy()` where I believe
the source should not be `NULL`

[libzstd] Fix memcpy() on potential NULL source

---

contrib/linux-kernel/README.md

Just a couple of typo fixes.
Hope you're having a great day! :)

Fix typos in README.md

---

build/cmake/programs/CMakeLists.txt

This fixes a linking issue on Solaris 10

Solaris fix

---

lib/common/pool.c
lib/common/pool.h
tests/poolTests.c

When queueSize=0, wait until there is an available thread before allowing a job to be added.

Allow queueSize=0 in pool.c

---

contrib/adaptive-compression/Makefile
contrib/adaptive-compression/adapt.c
contrib/adaptive-compression/test-correctness.sh

- bound compression levels
- fix C90 warnings
- add -pthread flag to makefile so that it compiles properly

Patching warnings, adding ability to bound compression variation

---

lib/compress/zstd_compress.c

If the destination buffer is the minimum allowed size in
`ZSTD_compressSequences()` (2^17), then if the block isn't compressible
compression might fail with `dstSize_tooSmall`, when it should instead emit
a raw uncompressed block.
Additionally, `ZSTD_compressLiterals()` implicitly called
`ZSTD_noCompressLiterals()` if Huffman compression failed. Make that
explicit.
Fixes #780.

Fix compression failure on incompressible data

---

Makefile
circle.yml
lib/decompress/zstd_decompress.c

[CI] Add gcc7build test

---

contrib/linux-kernel/0006-squashfs-tools-Add-zstd-support.patch

- Fix build instructions in Makefile

[kernel] Update squashfs-tools patch

---

lib/common/fse_decompress.c
lib/compress/fse_compress.c
lib/compress/huf_compress.c
lib/decompress/huf_decompress.c

Caught by Clang's optimization remarks.

[FSE][HUF] Inline error checks

---

contrib/adaptive-compression/README.md

- added information about use cases
- added test data
- more options + descriptions

Updating README.md

---

doc/educational_decoder/Makefile
doc/educational_decoder/harness.c
doc/educational_decoder/zstd_decompress.c
doc/educational_decoder/zstd_decompress.h

- Added Makefile
- fixed some bugs regarding warnings from clang
- simplified to single frame decoding
- created separate API for dictionary creation/initialization/freeing
- modularized sequence execution
- renamed `IO_read_bytes` and `IO_write_bytes`

Educational decoder 2

---

lib/common/pool.c
lib/compress/zstdmt_compress.c
lib/legacy/zstd_legacy.h

fixed : pool performance when jobs are fires fast and queueSize==0

reduced pool queue to 0 to save memory

---

programs/.gitignore
programs/Makefile
programs/README.md
programs/zstd.1
programs/zstd.1.md
programs/zstdcli.c

Requested and inspired by patch from @ib (#771)

cli : Display supported formats on -vV command

---

lib/common/error_private.h
lib/common/pool.c
lib/common/pool.h
lib/common/threading.h
lib/common/zstd_common.c
lib/common/zstd_internal.h
lib/compress/zstdmt_compress.c

* pthreads functions might still allocate.

[pool] Accept custom allocators

---

contrib/linux-kernel/0002-lib-Add-zstd-modules.patch
contrib/linux-kernel/include/linux/zstd.h
contrib/linux-kernel/lib/zstd/compress.c
contrib/linux-kernel/lib/zstd/decompress.c
contrib/linux-kernel/lib/zstd/error_private.h
contrib/linux-kernel/lib/zstd/mem.h
contrib/linux-kernel/lib/zstd/zstd_common.c
contrib/linux-kernel/lib/zstd/zstd_internal.h
contrib/linux-kernel/lib/zstd/zstd_opt.h
contrib/linux-kernel/test/DecompressCrash.c
contrib/linux-kernel/test/RoundTripCrash.c
contrib/linux-kernel/xxhash_test.c
contrib/linux-kernel/zstd_compress_test.c
contrib/linux-kernel/zstd_decompress_test.c

[linux-kernel] Update license

---

tests/fuzz/Makefile
tests/fuzz/stream_decompress.c

Fix some minor errors found when trying libFuzzer at https://github.com/facebook/zstd/pull/828.

Fix tests/fuzz build error

---

lib/compress/zstd_compress.c

`ZSTD_copyCCtx` currently is used in the following ways:
- Initializing a `cctx` using a `cdict` in `compressBegin_internal`: a `cdict` currently only contains compression parameters. By using only the cdict's applied parameters, the other parameters are now "lost". Before the parameter restructuring, only the compression parameters were copied over with `copyCCtx`. This fix preserves this behavior. Though future use-cases may want different behaviour?
- As a standalone function in the buffer-less streaming API called in the `ZSTDcs_init` stage. Again, old behavior is preserved and fields that can be changed in/before the ZSTDcs_init stage are copied.

Fix parameter handling with ZSTD_copyCCtx

---

programs/util.h

The timer used was only accurate up to 0.01 seconds. This timer is accurate up to 1 ns.
It is a monotonic timer that measures the real time difference, not on CPU time.

[bench] Use higher resolution timer on POSIX

---

tests/decodecorpus.c

Adds a flag to generate raw zstd compressed blocks (with no block/frame header)

Make decodecorpus generate raw compressed blocks

---

tests/fuzz/Makefile
tests/fuzz/fuzz_helpers.h
tests/fuzz/simple_round_trip.c
tests/fuzz/stream_round_trip.c
tests/fuzz/zstd_helpers.c
tests/fuzz/zstd_helpers.h

* Fuzz the long range matcher and the new API
* Whitespace fixes

[fuzzer] Fuzz long range matching & new API

---

lib/decompress/zstd_decompress.c

* `fParams` are initialized.
* Caught by the `block_decompress` fuzzer. It now doesn't crash with MSAN:
```
CC=clang CXX=clang++ python fuzz.py build all --enable-msan --enable-coverage --lib-fuzzing-engine ~/build/libfuzzer/msan/libFuzzer.a
./fuzz.py libfuzzer block_decompress
```
This command requires building `libFuzzer.a` with MSAN, which is a pain. Once we have the coverage corpora set up, it will be easy to run regression tests like this without any external dependencies/C++, so MSAN testing will be easy.

[block] Don't use fParams in ZSTD_decompressBlock()

---

NEWS
programs/fileio.c

fix #851 : sudo zstd -t file.zst changes /dev/null permissions

---

lib/common/bitstream.h

One change needed to allow larger window sizes. I picked 31 because that allows offsets up to 2^32-4, which is large enough so this won't be the limiting factor again (unless significant changes are made to the rest of the code).

[bitstream] Allow adding 31 bits at a time

---

lib/common/zstd_internal.h
lib/compress/zstd_compress.c
lib/decompress/zstd_decompress.c
tests/decodecorpus.c

* Allow ofcode up to 31
* Initial benchmarks look good, I will paste the results here when they're complete

[libzstd] Increase MaxOff

---

.travis.yml
Makefile
circle.yml
tests/fuzz/Makefile
tests/fuzz/README.md
tests/fuzz/fuzz.py
tests/fuzz/simple_round_trip.c

* Run the regression tests on CircleCI without any sanitizers. This takes ~2 mins. On the three runs I ran, each instance of CircleCI took approximately as long, within 1 minute. [306](https://circleci.com/gh/terrelln/zstd/306), [308](https://circleci.com/gh/terrelln/zstd/308), [309](https://circleci.com/gh/terrelln/zstd/309).
* Run the regression tests on Travis with UBSAN/ASAN (~5 mins), and MSAN (~10 mins).
* Add commands to `fuzz.py` to minimize the corpus and build the zipfiles that go on the release.
* Add a build rule to download the fuzz corpora.
* Fix some minor bugs in `fuzz.py` and the fuzzers.

[fuzz][CI] Set up regression tests

---

lib/common/pool.c
lib/common/threading.c
lib/common/threading.h
lib/compress/zstdmt_compress.c
lib/dictBuilder/cover.c

* `sed -i 's/pthread_/ZSTD_pthread_/g' lib/{,common,compress,decompress,dictBuilder}/*.[hc]`
* Fix up `lib/common/threading.[hc]`
* `sed -i s/PTHREAD_MUTEX_LOCK/ZSTD_PTHREAD_MUTEX_LOCK/g lib/compress/zstdmt_compress.c`
Fixes #868

[libzstd] pthread function prefixed with ZSTD_

---

tests/fuzz/default.options
tests/fuzz/fuzz.py

* Add a `list` command that just lists the fuzzers
* Add a default options file for libFuzzer

[fuzz] Small changes for oss-fuzz integration

---

programs/fileio.c

fixes #874 :
when a frame is not properly terminated by a "last block" signal,
zstd -d used to detect the issue early and immediately error out.
This version will decode and flush the last block, and only then issue an error.

decode more data before triggering error

---

programs/fileio.c

```
> zstd --list -v file1 file2 file3
*** zstd command line interface 64-bits v1.3.2, by Yann Collet ***
Window Size: 512.00 KB (524288 B)
Compressed Size: 0.02 KB (19 B)
Check: XXH64
Window Size: 8192.00 KB (8388608 B)
Compressed Size: 0.02 KB (19 B)
Check: XXH64
Window Size: 512.00 KB (524288 B)
Compressed Size: 0.01 KB (15 B)
Check: None
```

[zstdcli] Add window size to verbose list

---

lib/compress/zstd_compress.c

Fixes #888.
Improvements to the test suite coming next.

Fix invalid use of dictionary offcode table

---

lib/common/mem.h
lib/common/zstd_internal.h
lib/compress/zstd_compress.c
lib/compress/zstd_opt.c
lib/decompress/zstd_decompress.c
tests/Makefile

These UB are harmless on current architecture,
but well, the associated fixes are easy enough.

Fixes some arithmetic pointer operations

---

programs/fileio.c

Its possible (though very unlikely) that the user presses Ctrl-C after `remove(srcFileName)` finishes with `--rm`, but before the signal handler gets removed.

[zstd] Fix rare bug with signal handler

---

README.md

Missing dot

---

programs/zstd.1.md

Include information about the benchmark output/methodology

---

programs/bench.c
programs/dibio.c
programs/fileio.c
programs/util.h
tests/decodecorpus.c
tests/fuzzer.c
tests/paramgrill.c
tests/zbufftest.c
tests/zstreamtest.c

Fixes #935.
@mestia can you verify that this patch fixes the tests on GNU Hurd?

 Use util.h for timing

---

programs/fileio.c
programs/fileio.h
programs/zstdcli.c
tests/playTests.sh

Allow `-o` with multiple files, which will work like `-c`.

Allow -o with multiple files

---

programs/fileio.c

When the entire file fits in `ress.srcBuffer`, setting `ZSTD_e_end` allows us to use the single-pass API.

[fileio] Merge end loop for small optimization

---

contrib/meson/meson.build
contrib/meson/meson_options.txt

meson: support differn't legacy levels.

---

contrib/meson/meson.build
contrib/meson/meson_options.txt

this is necessary to link correctly

meson: get soversion right

---

tests/playTests.sh

Will fail before PR #972 is landed.

Add test case for PR #972

---

lib/compress/zstd_double_fast.c
lib/compress/zstd_fast.c

If the hash table is empty load positions into the hash table
that we would otherwise skip.
| Level | Data Set     | Improvement |
|-------|--------------|-------------|
| 1     | github       | 0.44%       |
| 1     | hg-changelog | 0.13%       |
| 1     | hg-commands  | 1.28%       |
| 1     | hg-manifest  | 0.70%       |
| 3     | github       | 0.74%       |
| 3     | hg-changelog | 0.87%       |
| 3     | hg-commands  | 1.74%       |
| 3     | hg-manifest  | 0.23%       |

Load more dictionary positions into table if empty

---

programs/README.md
programs/zstd.1
programs/zstd.1.md
programs/zstdcli.c

Also `-b#` value changed to 3 as it is by fact

cli: fix align of defaults

---

tests/fullbench.c

to use less calls to `time()`, like in `bench.c`.
also upgraded accuracy to nanosecond.

updated fullbench measurement methodology

---

lib/compress/zstdmt_compress.c

* Computes the XXH hash in the worker threads in serial and in order.
* Workers get a sequence number and wait until ther number shows up. On
error, ensures that its sequence is finished, so future threads don't
get blocked.
* Sets up for ldm integration, which will go in the same spot.

Move XXH64_update() into worker threads

---

lib/compress/zstdmt_compress.c

Prepares for LDM integration by separating the job size and overlap logic
into helper functions.

Pull job/overlap log logic into common function

---

contrib/docker/Dockerfile

Dockerfile proposed by @gyscos at #880

Add Dockerfile

---

build/cmake/contrib/gen_html/CMakeLists.txt
build/cmake/programs/CMakeLists.txt

Based on @Ne01eX's patch over at #1043. Omitted all formatting changes found over at the patch, so it condenses to a change in man page variables.

Update man page variables in CMakeLists

---

programs/zstd.1
programs/zstd.1.md

First PR in this cool project. Are there any open issues for someone interested in contributing more?
I'm proficient in C and have a strong background in mathematics, and I'm not above starting with docs.

 Correct small typo in manual (man file and markdown)

---

lib/compress/zstd_compress.c
lib/zstd.h
tests/fuzzer.c

Add ZSTD_CCtx(Param)?_getParameter() function

---

lib/compress/zstd_compress.c
tests/zstreamtest.c

The new advanced API basically set `requestedParams = appliedParams` when
using a dictionary. This halted all parameter adjustment, which can hurt
compression ratio if, for example, the window log is small for the first
call, but the rest of the files are large.
This patch fixes the bug, and checks that the `requestedParams` don't change
in the new advanced API when using a dictionary, and generally in the fuzzer.

Fix parameter adjustment with dictionary

---

tests/playTests.sh

Thanks to @mestia for reporting and finding the bug!
Fixes #1116.

Fix playTests.sh typo

---

tests/playTests.sh

Write to /dev/random for test

---

tests/paramgrill.c

Several small refactoring of `paramgrill`
the most important one being the introduction of programmable constraints,
in anticipation for arrival of next intern
and also because I need the updated tool
to re-adjust compression level tables.

Paramgrill refactoring

---

lib/compress/zstd_compress.c

Pull request #1144 exercised a new path in the zstd decoder that proved to
be buggy. Avoid the extremely rare bug by emitting an uncompressed block.

Work around bug in zstd decoder

---

lib/compress/zstd_compress.c
lib/compress/zstd_compress_internal.h
lib/compress/zstd_fast.c
lib/compress/zstd_fast.h
lib/compress/zstd_ldm.c
lib/compress/zstd_ldm.h

ZSTD_fast: Support Searching the Dictionary Context In-Place

---

lib/compress/zstd_compress.c

The (pretty old) code inside `ZSTD_compress()`
was making some bold assumptions
on what's inside a CCtx and how to init it.
This is pretty fragile by design.
CCtx content evolves.
Knowledge of how to handle that should be concentrate in one place.
A side effect of this strategy
is that `ZSTD_compress()` wouldn't check for BMI2 capability,
therefore missing some potential speed opportunity on compatible systems.
This patch makes `ZSTD_compress()` use
the same initialization and release code
as the normal creator / destructor ones.
Measured on my laptop, with a custom version of `bench.c`
manually modified to use `ZSTD_compress()` (instead of the advanced API) :
This patch :
1#silesia.tar       : 211984896 ->  73651053 (2.878), 312.2 MB/s , 723.8 MB/s
2#silesia.tar       : 211984896 -> …

clean ZSTD_compress() initialization

---

lib/compress/zstd_compress.c
lib/zstd.h

Fixes #1148 
Reviewer: @Cyan4973

Expose ZSTD_CLEVEL_DEFAULT and update documentation

---

doc/zstd_compression_format.md

adding clarifications from IETF RFC DISCUSS.

updated Zstandard frame format

---

doc/zstd_manual.html
lib/common/debug.h

following suggestion from #1209

updated DEBUG_STATIC_ASSERT()

---

build/VS2010/fullbench-dll/fullbench-dll.vcxproj
build/VS2010/fullbench/fullbench.vcxproj
programs/bench.c
programs/bench.h
programs/zstdcli.c
tests/Makefile
tests/fullbench.c
tests/paramgrill.c

Makes bench.c more useable by other files.
Test plan:
Ran fullbench, zstd -b#, and paramgrill before/after changes.

Bench module

---

doc/zstd_compression_format.md

Update to keep in sync with the RFC.

Small fixes to zstd specification

---

.travis.yml

This reverts commit 9c277f137cbcaa385ff5b95ec4cbdce50675541d.

Revert "attempt to re-enable arm64 tests"

---

tests/Makefile
tests/README.md
tests/paramgrill.c

Depends on MultiLvl Branch (Only last 4 commits new)
allow for force attach dictionary
-change ZSTD_compressionParameters struct to paramValues_t struct
time limit works for optimizer
fix turning off asserts

forceAttachDict

---

programs/bench.c

Fix scan-build warnings in bench.c

---

tests/README.md
tests/paramgrill.c

Remove unused globals from old paramgrill
Remove outdated comments
Group similar functions together
Add some consts
Only last 4 commits, rebase after paramgrill display

Clean up paramgrill code

---

Makefile

This PR implements a requested FB bootcamp task, T17937099.
Tested on Linux and MacOS for compatibility.
The output should look like:
```
Target Name          Description
----------------     ----------------------------------------
aarch64build
...
list                 Print all targets and their descriptions (if provided)
...
```

Zstandard - better `make list`

---

doc/zstd_compression_format.md

following #1305 comments from @ulikunitz

spec clarification

---

contrib/seekable_format/examples/seekable_decompression.c
contrib/seekable_format/zstdseek_decompress.c

Seekable fixes pull

---

doc/zstd_manual.html
lib/zstd.h

indicating the equivalence with `diff` operation.

updated documentation of *refPrefix()

---

tests/playTests.sh

Sometimes, it's necessary to test that a certain command fails, as expected.
Such failure is actually a correct behavior, and must not stop the flow of tests.
Several tests were prefixed with `!` to invert return code.
This does not work : it effectively makes the tests pass no matter what.
Use instead function `die()`, which is meant to trap unwanted successes, and transform them into errors.

fixed `!` tests

---

doc/zstd_compression_format.md

to match last edits of RFC8478.

updated format documentation

---

Makefile
lib/Makefile
programs/Makefile

when terminal uses colors,
as suggested by @danielshir (#1294).

fixed usage of grep in Makefile

---

lib/compress/zstd_lazy.c

on btlazy2 strategy with dictAttach

fixed msan warning

---

build/VS_scripts/build.generic.cmd
build/cmake/.gitignore

fix #1270 reported by @epicabsol

fixed VS2017Community build script

---

programs/bench.h
tests/paramgrill.c

and slightly refactored surrounding function.
I believe the formula calculating variance should get a second reviewing round,
as it's not clear if it's correct.

fixed paramgrill wrong assert() conditions

---

lib/zstd.h

as suggested by @indygreg in #1360

Clarify streaming api doc

---

Makefile
doc/zstd_manual.html
lib/zstd.h
programs/zstd.1
tests/.gitignore

bumped version number to v1.3.7

---

.travis.yml
lib/common/pool.c
tests/fuzzer.c

* Run `tsan-fuzztest` in travis.
* Add multithreaded dictionary builder tests to `fuzzer.c`.
* Reorder condition variable signal/broadcasts before unlocking.

Add TSAN dictionary tests

---

programs/zstdgrep
tests/Makefile

Fix  #1428 - zstdgrep now returns 1 on unmatch

---

README.md

I realized I forgot to update the README.md with my last diff for the buck files. This is just a small documentation change, sorry I forgot to include in my last change set.

Add buck build instructions to README.md

---

examples/dictionary_compression.c
examples/dictionary_decompression.c
examples/multiple_streaming_compression.c
examples/simple_compression.c
examples/simple_decompression.c
examples/streaming_compression.c
examples/streaming_decompression.c
examples/utils.h

Pull a request to the dev branch to avoid unnecessary merge conflict from the master branch.

Refactor examples to avoid code duplication.

---

tests/regression/config.c
tests/regression/config.h
tests/regression/method.c
tests/regression/results.csv

* Rebase on top of the new advanced API (no ratio changes)
* Add advanced API methods (one pass + streaming)
* Add old streaming API methods
* Update `results.csv`, the cron job should start passing.
Next I will add more configs that test setting parameters directly.

[regression] add more methods

---

README.md

- Increase one heading level. Now headings is bigger and prettier.
- Explain a bit more about Meson build.

README: Explain a little bit about Meson build

---

programs/fileio.c

complementing existing error messages in `fileio.c`.
Requested by `fbpkg`.

add more system error strings

---

build/cmake/CMakeLists.txt

Update ZSTD_LEGACY_SUPPORT to 5 based on a request by @lzutao in #1474.

ENH: Update to -DZSTD_LEGACY_SUPPORT=5

---

programs/util.c

Similar to Apple, use the native physical core count sysctl, when available.
This is a little repetitive (it's basically the `__APPLE__` method plus the
otherBSD method concatenated together) but seemed clearer than any way that
would totally eliminate repetition.
The `__FreeBSD_version` check only tests the version of the FreeBSD kernel
that zstd is compiled on; importantly, it may be run on a different version.
So the compile-time check is a little naive and needs to be able to fallback
to work on older versions of FreeBSD.  For a similar reason, it may make
sense to simply eliminate the `__FreeBSD_version` check entirely.  The
tradeoff is that a spurious `sysctlbyname` would be issued when `-T0` is used on
older kernels.

Fix #1425 - Use physical core count API on FreeBSD

---

programs/fileio.c
programs/fileio.h
programs/zstdcli.c

Remove global parameters, pass into public functions instead

---

programs/fileio.c
programs/fileio.h

was broken by #1505.
I'm surprised it passed CI tests.
LZ4 tests are part of the "Extended" tests on Travis CI,
which are run on "master" and in "cron" jobs.
Since latest cron job did not failed,
especially this one : https://travis-ci.org/facebook/zstd/jobs/484365040
it suggests cron jobs are no longer using `dev` branch.
To be investigated

fixed fileio.c compilation with LZ4 enabled

---

build/meson/lib/meson.build
contrib/adaptive-compression/Makefile
contrib/largeNbDicts/Makefile
doc/educational_decoder/Makefile
lib/Makefile
programs/Makefile
tests/Makefile
tests/fuzz/Makefile

https://github.com/facebook/zstd/issues/1514

-Wformat-security not needed with -Wformat=2

---

tests/fuzz/fuzz.py

Newer clang versions have libfuzzer built in, which can be linked with `-fsanitize=fuzzer`. Add a flag `--enable-fuzzer` which enables this option, ignoring `--lib-fuzzing-engine`.
Fixes #1539.

[fuzz] Add --enable-fuzzer for clang fuzzing

---

examples/streaming_compression.c
examples/utils.h

Update streaming_compression to the new API and add instructive comments.
Issue #1548.

[examples] Update streaming_compression to the new API

---

tests/regression/results.csv

Only the negative levels, and level 1 changed.

[regression] Update results.csv for level 1 change

---

CHANGELOG
README.md

* Update benchmarks in the README
* Update the CHANGELOG

Prepare for the zstd-1.4.0 release

---

lib/decompress/zstd_decompress_block.c

[libzstd] Error if all sequence bits aren't consumed

---

doc/zstd_manual.html
programs/zstdgrep
tests/Makefile

Handle `-f` Flag in `zstgrep`

---

doc/zstd_manual.html
lib/zstd.h

It seems this is still a confusing topic,
for example in klauspost/compress#109 .

Added comments on I/O buffer sizes for streaming

---

build/VS2010/libzstd-dll/libzstd-dll.vcxproj
build/VS2010/libzstd/libzstd.vcxproj

VS2010 project settings improvements

---

tests/fuzz/default.options

See https://github.com/facebook/zstd/commit/d9c1e9125f2863a90c2910b995cb6920dc0d5734#commitcomment-33877694.

[fuzz] Remove max_len from the options

---

.travis.yml
programs/util.c
tests/Makefile

Protect lstat() With Better Macro Guard

---

lib/legacy/zstd_v05.c

The match length and literal length extra bytes could either
by 2 bytes or 3 bytes in version 0.5. All earlier verions were
always 3 bytes, and later version didn't have dumps.
The bug, introduced by commit 0fd322f812211e653a83492c0c114b933f8b6bc5,
was triggered when the last dump was a 2-byte dump, because we didn't
separate that case from a 3-byte dump, and thought we were over-reading.
I've tested this fix with every zstd version < 1.0.0 on the buggy file,
and we are now always successfully decompressing with the right
checksum.
Fixes #1693.

[legacy] Fix bug in zstd-0.5 decoder

---

doc/zstd_compression_format.md

following comments from Intel's Smita Kumar.

clarifications on field `Block_Size`

---

index.html

Add Crystal Lang Binding Reference to Homepage

---

lib/zstd.h

[libzstd] Improve advanced API docs

---

programs/util.c

Set Mod Time Nanoseconds

---

lib/compress/zstd_compress_internal.h
lib/compress/zstd_fast.c

- reduced lifetime of some variables
- more accurate code comments
No functional change.

minor refactor of ZSTD_fast

---

tests/zstreamtest.c

[test] Test the bounds of ZSTD_c_srcSizeHint

---

programs/fileio.c

[programs] don’t do chmod when coming from stdin or multiple files

---

lib/common/zstd_internal.h
lib/zstd.h
programs/util.c
zlibWrapper/Makefile
zlibWrapper/examples/fitblk.c
zlibWrapper/examples/zwrapbench.c
zlibWrapper/gzclose.c
zlibWrapper/gzlib.c
zlibWrapper/gzread.c
zlibWrapper/gzwrite.c
zlibWrapper/zstd_zlibwrapper.c

for increased compatibility with compilers.
Also : made the zlib wrapper part of automated CI compilation tests.

make zlibWrapper strict ISO-C90 compatible

---

doc/zstd_compression_format.md

clarifications for the FSE decoding table

---

lib/compress/zstd_compress.c
lib/dictBuilder/zdict.c

Take ZSTD_parameters as a const pointer

---

doc/zstd_compression_format.md

Specs. clarifications for Block_Maximum_Size

---

lib/decompress/huf_decompress.c

This has no measurable impact on large files but improves small file
decompression by ~1-2% for 10kB, benchmarked with:
head -c 10000 silesia.tar > /tmp/test
make CC=/usr/local/bin/clang-9 BUILD_STATIC=1 && ./lzbench -ezstd -t1,5 /tmp/test

Optimized loop bounds to allow the compiler to unroll the loop.

---

lib/decompress/huf_decompress.c

Introduced by #1866. I guess I missed the test failure while merging?

Fix Appveyor failure

---

programs/zstd.1.md

https://github.com/facebook/zstd/issues/1886

Fixing hashLog error 2^26=64Mib

---

programs/fileio.c

On failure fread may return either a short read or 0. Need to use
ferror to detect error versus eof.
For https://github.com/facebook/zstd/issues/1895

Check for fread failure

---

lib/compress/zstd_compress.c

[fuzz] msan uninitialized unsigned value

---

doc/educational_decoder/harness.c

following #1953 (false positive, due to heuristic's confusion)

refactor of harness, for clarity

---

doc/educational_decoder/Makefile
doc/educational_decoder/README.md
doc/educational_decoder/harness.c
doc/educational_decoder/zstd_decompress.c

added an ability to remove error messages and dictionary support
using macro at compile time
for the benefit of smaller binary size.

minor : update educational decoder

---

lib/common/zstd_internal.h

The idea is to only do one copy the first iteration, since the copy length is probably less than 16. Then do two in the loop since at that point it is probably long. Also allow gcc to vectorize the loop, since we've already split out the first iteration. I missed this before because gcc gets worse unless you remove `DONT_VECTORIZE`.
I benchmarked zstd compiled with `-O3` before and after this change. The test file is enwik7. I report the decompression speed delta range for levels 1, 3, 5, and 16. More detailed results are in https://docs.google.com/spreadsheets/d/1Ynecjk46B_EktG5athbCeDJ-ZGC__u9vnOkh33PdxJc/edit?usp=sharing (sorry only available to FB employees).
| Device | Architecture | Compiler | Decompression speed delta | Notes |
| -- | -- | -- | --| -- |
| i9-9900K | x86_64 | …

Improve wildcopy performance across the board

---

programs/benchzstd.c

https://github.com/facebook/zstd/issues/1885
```
./zstd -r -d -b github/*.zst
```

Benchzstd multiple file decompression enable 

---

.github/workflows/main.yml

[CIFuzz] Rename output path to artifacts

---

programs/zstdcli.c

This is an attempt to fix #2006, in which the `--stream-size` CLI option is limited to 4 GB (32-bit unsigned int).  For CLI variables whose internal types are already `size_t`, this allows values up to the `size_t` limit to be specified.
This is something of a quick hack to get the CLI working for my application; happy to take suggestions on how to improve it!

Allow some CLI options to accept numeric values up to size_t

---

programs/zstd.1
programs/zstd.1.md
programs/zstdgrep.1
programs/zstdless.1

also updated `zstd.1`
stacking prior updates completed on `zstd.1.md`.

man page : added `--verbose` long command

---

.cirrus.yml

Testing to see if this will fix the FreeBSD failures

[cirrus-ci] Removing pkg -y update and using 11.3-snap instead of 11.2 

---

programs/zstdcli.c

Realized I forgot hashLog in the original pr

--show-default-cparams Adding hashLog

---

lib/compress/zstd_compress_sequences.c

Dont log errors when ZSTD_fseBitCost() returns an error

---

lib/zstd.h

https://github.com/facebook/zstd/issues/2012

[doc] Fixing ZSTD_c_compressionLevel confusing note

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

LZ4 just added this. I think it would be helpful here too.

Add issue templates to zstd

---

.travis.yml

Looks like we can run icc on travis. It might be helpful for issues like https://github.com/facebook/zstd/issues/1951
I think just make check should be fine here. Here is the run on my fork: 
https://travis-ci.com/bimbashrestha/zstd/jobs/293671236

[ci] Adding icc make check to travis

---

contrib/diagnose_corruption/check_flipped_bits.c

Addresses https://github.com/facebook/zstd/issues/2051.

[bug] adding fclose before return

---

programs/fileio.c

https://github.com/facebook/zstd/issues/2059

[bug] Fixing Incorrect/inconsistent reported compression percentage for empty files

---

build/meson/meson.build

https://github.com/facebook/zstd/issues/2073#issuecomment-622405927

[build] fix meson build issue

---

lib/common/huf.h
lib/compress/huf_compress.c
tests/decodecorpus.c

Reduce stack usage of HUF_sort()

---

lib/compress/huf_compress.c

This just helps for some static analyzer warnings.

fix minor conversion warnings in huf_compress.c

---

programs/zstdgrep
tests/playTests.sh

Fixing zstdgrep inconsistencies listed on https://github.com/facebook/zstd/issues/2064
See each commit message for details
* Fix multiple -e
* Fix pipe in with -f
* Fix "incorrect parameters" output on regexp
* Don't show filename on single file (ie: no to /tmp/file:start and yes to start <- grep does this)
* Fixing --regexp giving lots of irelevant complaints

[bugs] zstdgrep/grep inconsistencies

---

CONTRIBUTING.md

https://github.com/facebook/zstd/issues/1990

[doc] Adding static analysis section and note

---

Makefile
lib/Makefile

https://github.com/facebook/zstd/issues/2072

[build] Adding $TARGET_SYSTEM for cross-compilation Fedora fix

---

lib/compress/zstd_compress.c

`ZSTD_estimateCCtxSize()` provides estimates for one-shot compression, which
is guaranteed not to buffer inputs or outputs. So it ignores the sizes of the
buffers, assuming they'll be zero. However, the actual workspace allocation
logic always allocates those buffers, and when running under ASAN, the
workspace surrounds every allocation with 256 bytes of redzone. So the 0-sized
buffers end up consuming 512 bytes of space, which is accounted for in the
actual allocation path through the use of `ZSTD_cwksp_alloc_size()` but isn't
in the estimation path, since it ignores the buffers entirely.
This commit fixes this.

Fix ZSTD_estimateCCtxSize() Under ASAN

---

tests/fuzzer.c

ensure that `estimateCCtxSize()` works as intended.

re-inforced tests for initStaticCCtx

---

CONTRIBUTING.md

https://github.com/facebook/zstd/issues/1990

[doc] measuring performance docs

---

programs/README.md
programs/zstdgrep
tests/playTests.sh

https://github.com/facebook/zstd/issues/2064

Revert to old zstdgrep because of potential license issue

---

.travis.yml
build/meson/tests/meson.build

error introduced in https://github.com/facebook/zstd/blame/3b39ce6b527c5cfe395a187c75b77baf5cc7de02/.travis.yml#L192

fixed zbuff test

---

contrib/pzstd/Logging.h
contrib/pzstd/Pzstd.cpp
contrib/pzstd/Pzstd.h

Fixes #2165
Tested with `make pzstd`

[pzstd] Fix compilation error in MinGW

---

Makefile

also : implemented verbose mode in root `Makefile` (`make V=1`)
fix #2169

fixed double-compilation of lib with make -j all

---

programs/fileio.c
programs/zstd.1.md
tests/playTests.sh

Closes https://github.com/facebook/zstd/issues/2191

Fixing some typos 

---

.github/workflows/generic-dev.yml

Doesn't work on ubuntu-latest so using ubuntu-16.04

[actions] adding arm to actions

---

lib/Makefile

Replace -E option with equivalent -r for older versions of sed

---

programs/zstd.1
programs/zstd.1.md

Rename ZSTDMT_NBTHREADS_MAX to ZSTDMT_NBWORKERS_MAX.

---

examples/streaming_compression.c

Use threads in streaming_compression.c example.

---

lib/common/debug.h

Revert "Fix -Wunused-variable under FUZZING_BUILD_MODE..."

---

programs/platform.h

reported and suggested by @ewildgoose (#1872)

fix uclibc's st_mtim

---

CHANGELOG
lib/README.md
lib/zstd.h

* Document thew new build macros in `lib/README.md`
* Update CHANGELOG for the next release
* Bump version number to 1.4.6

Prepare library for a release

---

.github/workflows/generic-dev.yml
tests/fuzzer.c

They take a long time to run, so let's pull them out so that you have to ask for them.

Separate Long Tests in Fuzzer

---

tests/fullbench.c

makes it possible to measure scenarios such as #2314
```
./fullbench -i0
*** Zstandard speed analyzer 1.4.6 64-bits, by Yann Collet (Sep 21 2020) ***
Sample 10000000 bytes :
1#compress                     :   501.6 MB/s  ( 3154783)
2#decompress                   :  1763.6 MB/s  (10000000)
11#compressContinue             :   513.5 MB/s  ( 3154783)
12#compressContinue_extDict     :   484.1 MB/s  ( 3155118)
13#decompressContinue           :  1745.4 MB/s  (10000000)
30#decodeLiteralsHeader         :149187.6 MB/s  (      44)
31#decodeLiteralsBlock          :  2663.8 MB/s  (   37031)
32#decodeSeqHeaders             : 71965.7 MB/s  (      73)
41#compressStream               :   396.0 MB/s  ( 3154893)
42#decompressStream             :  1732.4 MB/s  (10000000)
43#compressStream_freshCCtx     : …
```

update fullbench for compressStream2()

---

examples/streaming_compression_thread_pool.c
lib/common/pool.c
lib/compress/zstd_compress.c
lib/compress/zstd_compress_internal.h
lib/compress/zstdmt_compress.c
lib/compress/zstdmt_compress.h
lib/zstd.h

This is a follow up of #2290 which implements sharing of threads pools.
@Cyan4973: what do you think about this approach?

Allow external creation of POOLs that can be shared.

---

lib/decompress/zstd_decompress.c

fix #2386, reported by @Neumann-A

fix incorrect assert

---

lib/dictBuilder/cover.c
lib/dictBuilder/cover.h
lib/dictBuilder/fastcover.c

Pass dictBufferCapacity to COVER_selectDict()

---

lib/compress/zstd_compress.c

Clamp compression level where needed.
It should cover all possible sites.
If this code style is not liked, feel free to ask me to modify or submit a new PR.
It's up to you to discuss whether to clamp silently or to return an error.
IMO clamp is safe, suppose the maximum level of zstd v1.4 is 22, the maximum level of zstd v1.5 is 30, then the code written for v1.5 can run on v1.4 without error.
This change seems to fix a wrong parameter type:
```diff
--- a/lib/dictBuilder/zdict.c
+++ b/lib/dictBuilder/zdict.c
@@ -706,7 +705,7 @@ static void ZDICT_flatLit(unsigned* countLit)
#define OFFCODE_MAX 30  /* only applicable to first block */
static size_t ZDICT_analyzeEntropy(void*  dstBuffer, size_t maxDstSize,
-                                   unsigned compressionLevel,
+ …
```

Clamp compression level

---

zlibWrapper/zstd_zlibwrapper.c

* Reimplement `ZWRAP_readLE32()`
* Reimplement the 3 zstd allocation functions
zlibWrapper still depends on static linking only symbols, but now it only uses `zstd.h`.

[zlibWrapper] Only use public zstd functions

---

build/cmake/tests/CMakeLists.txt
tests/paramgrill.c

For issue #2323
Paramgrill works fine on windows with some minor adjustments to the cmake file (at least locally with MSVC 2019). A bunch of warnings need to be fixed though.

Paramgrill for windows

---

doc/zstd_compression_format.md

Update Zstd Compression Format to Clarify Repcode Behavior

---

lib/compress/huf_compress.c

Comment and refactor `HUF_buildCTable()` and the helper functions
it calls as I read and understand the code. Hopefully this refactor
makes the code a bit more clear.

[huf_compress] Refactor and comment HUF_buildCTable()

---

Makefile
examples/Makefile

streamlined example recipe
