facebook/zstd

- lib/fse.c
- lib/zstd.c
Hello Yann,
Here you have a few missing casts.
They're not required in C, but library will fail to compile in C++ mode otherwise
(reproduce it by typìng `cl.exe /Tp fse.c` and `cl.exe /Tp zstd.c`)
Great library.
Keep up the good work.
- r-lyeh
PS: I have kept your identation style when creating the type casts. Also, see errors bugfixed below:
```c++
fse.c(135) : error C2440: 'initializing' : cannot convert from 'const void *' to 'const BYTE *' Conversion from 'void*' to pointer to non-'void' requires an explicit cast
fse.c(148) : error C2440: 'initializing' : cannot convert from 'void *' to 'BYTE *' Conversion from 'void*' to pointer to non-'void' requires an explicit cast
fse.c(169) : error C2440: 'initializing' : cannot convert from 'const void *' to 'const BYTE *' Conversion from …
```
> Bugfixed Visual Studio errors when compiled as C++ sources

- lib/zstd.c
By making the buffer part of the zstd context structure, one malloc/free
can be removed from the compression.
> Remove one malloc/free from compression

- programs/Makefile
- programs/playTests.sh
This patch allows me to run tests on MIPS board which lacks make.
> Move tests from zstd-playTests target to separate shell script.

- lib/zstd.h
- lib/zstd_buffered.h
- lib/zstd_buffered_static.h
- lib/zstd_static.h
I'm building a .NET wrapper for Zstandard, and for that I need to build zstd as a windows DLL with a `__declspec(dllexport)` prefix on all the public methods defined in the header files. This allows me to use `LoadLibrary` and `GetProcAddress` at runtime to bind to the native library.
I looked at other projects and how they were adressing this, and used the same pattern as, for example, SQLite which defines a `SQLITE_API` prefix. Other libraries also have a similar LIBFOO_API.
This PR is about adding a `ZSTDLIB_API` macro as a prefix to all public methods in the `zstd_*.h` headers, which is by default not defined. Only when building with `ZSTD_DLL_EXPORT=1` then this macro would be defined as `__declspec(dllexport)` on Win32.
Questions:
- Are the names `ZSTDLIB_API` and `ZSTD_DLL_EXPORT` …
> Add __declspec(dllexport) via optional ZSTDLIB_API macro when building a DLL for Windows

- contrib/cmake/programs/CMakeLists.txt
Please, test PR cmake build for paramgrill target with gcc 4.8.4. I have only 5.3 and 4.9.3 on my archlinux...
> Paramgrill math library

- dictBuilder/divsufsort_private.h
- dictBuilder/sssort.c
- dictBuilder/trsort.c
- visual/2013/dictBuilder/dictBuilder.vcxproj
- visual/2013/dictBuilder/dictBuilder.vcxproj.filters
- visual/2013/zstd.sln
- visual/2013/zstdlib/zstdlib.vcxproj
- visual/2013/zstdlib/zstdlib.vcxproj.filters
Added a .vcxproj for the new `dictBuilder` to the VS2013 solution.
I had to fiddle with a few things to make it build, with my limited knowledge of C++ projects in VS:
- included `string.h` instead of `strings.h`
- copy/pasted a bunch of defines to make VS shut up about `INLINE` / `FORCE_INLINE` from other files.
- disabled "treat warning as errors" because there are a bunch of warnings in VS that I do not understand
With these hacks, I can produce a working dictBuilder.exe that seems to output the same dictionary as the version I build previously on linux.
Also note I added the new `error_private.h` and `error_public.h` to the `zstdlib.vcxproj`, for completness (not required but easier to load these files from the IDE if they are included)
> Added VS2013 project for dictBuilder

- .gitignore
Visual Studio 2015 Update 2 adds a new file format for their internal intellisense db engine, with extension ".VC.db", as described in https://www.visualstudio.com/en-us/news/vs2015-update2-vs.aspx#Cdoubleplus
Anyone installing a new version of 2015 Update 2 will get this new format by default, and will get a ~5MB file in the VS solution folder which should probably not be part of the repo.
> Added new ".VC.db" Visual Studio C++ database file to gitignore

- programs/fileio.c
… it but fail to successfully compress or decompress
> propagate errors when decompressing; also unlink dstfile if we create

- visual/2013/fullbench/fullbench.vcxproj
- visual/2013/fuzzer/fuzzer.vcxproj
- visual/2013/zstd/zstd.vcxproj
- visual/2013/zstdlib/zstdlib.vcxproj
Currently, when VS 2013 builds the various projects (zstd.exe, tools, zstlib, ...), they all end up in various folders all other the place, making it difficult to find the correct location:
- `zstd.exe` ends up `../vs2013/Release/zstd.exe' for both x86 and x64 build
- the other projects end up in '.../vs2013/Win32/Release/` or `.../vs2013/x64/Release/`
This PR changes all the vcxprojs to output to `./bin/{ARCH}/{CONFIG}` by default (ex: `bin/Win32/Release` or `./bin/x64/Release`). This way, all the outputs are in a `bin` subfolder, and are easy to find.
This would also work if in the future there are additional release types (like a ReleaseStatic, or with custom settings, ...)
If people are running a CI server to run tests after the build, on Windows, they would need to update the paths …
> Update VS2013 vcxprojs to all build to the same folders

- lib/common/mem.h
- programs/datagen.c
- programs/xxhash.c
No stdint.h on OpenVMS, it is inttypes.h instead, some projects use HAVE_STDINT_H.
> No stdint.h on OpenVMS.

- programs/util.h
Define util sleep functions on VMS.
If PRIO_PROCESS is not defined then do not attempt to use it in the definition of SET_HIGH_PRIORITY.
> Minor changes needed for OpenVMS

- lib/dictBuilder/zdict.c
- lib/dictBuilder/zdict.h
In some cases a custom dictionary building algorithm tailored for a specific
input can be more effective than the one produced by `ZDICT_trainFromBuffer`,
but with the current API it's not possible encode the entropy tables into the
custom-built dictionary.
This commit extracts the logic to add entropy tables to a dictionary from
`ZDICT_trainFromBuffer` and exposes it as a function
`ZDICT_addEntropyTablesFromBuffer`.
> Expose function to add entropy tables to pre-built dictionary.

- .gitignore
- build/build.VS2010.cmd
- build/build.VS2012.cmd
- build/build.VS2013.cmd
- build/build.VS2015.cmd
- build/build.generic.cmd
This PR adds a set of build commands for Windows, intended for people who want to quickly build `zstd.exe` or `zstdlib_*.dll` without needing to open Visual Studio and fight with the project conversion process (see Issue #201 for the context), and is inspired by the build scripts used in [GitExtensions](https://github.com/gitextensions/gitextensions/blob/aefed53bb6879658e3eb22322dcb9cae93a05547/Build/build.generic.cmd)
- `build.generic.cmd` is the main build script that runs msbuild on the Visual Studio project, for a specific configuration (ex: Release, x64, v120).
- `build.VSxxx.cmd` are helper scripts that call `build.generic.cmd` with a set of default settings for this particular version of Visual Studio.
For example, somone with Visual Studio 2013 installed, would run …
> Added build commands for various versions of Visual Studio

- build/build.generic.cmd
This address feedback from #201 by fixing the hardcoded path to `Program Files (X86)`, as well as fixing a leak of the variables defined in the script by adding `SETLOCAL`
- Whether running on 32-bit, 64-bit or WoW64, `%programfiles(x86)%` returns `C:\Program Files (x86)` by default.
- Without `SETLOCAL`, the script would leak all variables defined via `SET` in the CMD session, even after the scripts exists.
> Fix hardcoded path in msbuild scripts

- projects/VS2010/fullbench/fullbench.vcxproj
- projects/VS2010/fullbench/fullbench.vcxproj.filters
- projects/VS2010/fuzzer/fuzzer.vcxproj
- projects/VS2010/fuzzer/fuzzer.vcxproj.filters
- projects/VS2010/zstd/zstd.vcxproj
- projects/VS2010/zstd/zstd.vcxproj.filters
- projects/VS2010/zstdlib/zstdlib.vcxproj
- projects/VS2010/zstdlib/zstdlib.vcxproj.filters
Removed reference to the old `..._static.h` files from the `.vcxproj` of the VS2012 solution.
VS does not seem to complain when a reference .h is missing (only when you click on the file in the Solution Explorer to open it), but I figured it would be better if they are removed.
Note that I updated the project with VS2015, which also updated the `.vcxproj.filters` files to add some stuff (maybe they were out of sync?). I think the `.vcxproj.filters` files are not used by msbuild, so it should not impact the command line build.
> Removed old xxx_static.h header references from VS2010 project

- programs/zstd.1
This is also wrong in master.
The file seems outdated, the "--ultra" parameter is also not listed.
Is this man-page still used?
> Fix Max Compression Level in zstd.1

- programs/zstd.1
".SH OPTIONS" is enough.
Closes #234
> Redundant entry for options in the man page.

- lib/legacy/zstd_v04.c
Couple of functions and declarations were missing in order to be able to use the low-level streaming API with the legacy decoders.
> Add legacy support for the low-level streaming API

- Makefile
- lib/Makefile
- programs/Makefile
Zstd has been introduced to FreeBSD ports
(http://www.freshports.org/archivers/zstd/) which DragonFly BSD also
uses.  FreeBSD and DragonFly use the install targets (albeit modified in
some cases) so they must be added to the associated Makefile filters.
> Enable build on FreeBSD ports (includes DragonFly BSD) [dev branch]

- programs/zstdcli.c
Test Plan:
```
davidlam-mbp:zstd davidlam$ ./zstd --help | grep verbose
-v     : verbose mode; specify multiple times to increase log level (default:2)
davidlam-mbp:zstd davidlam$ ./zstd ./README.md -o /dev/null
./README.md          : 45.69%   (  5529 =>   2526 bytes, /dev/null)
davidlam-mbp:zstd davidlam$ ./zstd -v ./README.md -o /dev/null
*** zstd command line interface 64-bits v0.8.1, by Yann Collet ***
./README.md          : 45.69%   (  5529 =>   2526 bytes, /dev/null)
davidlam-mbp:zstd davidlam$ ./zstd -v -v ./README.md -o /dev/null
*** zstd command line interface 64-bits v0.8.1, by Yann Collet ***
./README.md          : 45.69%   (  5529 =>   2526 bytes, /dev/null)
Completed in 0.00 sec
davidlam-mbp:zstd davidlam$ ./zstd -v -v -v ./README.md -o /dev/null
*** zstd command line …
```
> Add more descriptive message to -v option in zstd CLI

- lib/dictBuilder/zdict.h
- lib/zstd.h
I made a basic .NET wrapper for zstd (and its dictionary builder) and am planning to publish it soon. However, it requires some new API functions to be exported from DLL.
> Export functions related to dictionary compression from DLL

- index.html
I suggest adding a link to C# binding. The link is inserted so as to maintain binding order mentioned [here](https://github.com/Cyan4973/zstd/pull/276#issuecomment-236909368).
> Add a link to C# binding

- index.html
Changed URLs to reflect change in ownership from and reduce page load times of zstd.net due to multiple redirects.
I have signed the CLA at code.facebook.com/cla
> Changed URLs

- index.html
Caught a typo in the documentation home page title.
> Fix typo in index page title

- contrib/pzstd/Makefile
- contrib/pzstd/Pzstd.cpp
- contrib/pzstd/utils/WorkQueue.h
- contrib/pzstd/utils/test/WorkQueueTest.cpp
The memory usage was linear in the size of the file.  It is now linear in the number of threads and the compression level.
To achieve this, I limited how far ahed the reading/(de)compression threads can get from the writer thread.
This is an initial fix for issue #331, the memory usage can likely still be reduced without reducing performance.  However this gets pzstd 90% of the way there, and even increases performance.
> [pzstd] Fix memory usage issues

- index.html
I've released the Erlang binding. Could you add it to the list?
https://hex.pm/packages/zstd
> Add Erlang binding

- appveyor.yml
- contrib/pzstd/Options.cpp
- contrib/pzstd/Pzstd.cpp
- contrib/pzstd/Pzstd.h
- contrib/pzstd/test/OptionsTest.cpp
- contrib/pzstd/utils/FileSystem.h
Pzstd now builds on windows with minGW-64 and VS2015.
This resolves #331, as the last issue of setting a reasonable default for the number of threads has been fixed.
It doesn't build on minGW-32, because by default it doesn't support pthreads, and thus doesn't support `std::thread`.  This is fixable.  I think a version of minGW-64 supports a posix threads implementation for minGW-32.  There are also libraries that provide this functionality if necessary.
> [pzstd] Windows build and default number of threads

- zstd_compression_format.md
I noticed that the wiki and `zstd_compression_format.md` are out of sync.  Is there a clean way to have the wiki track this file, or should we just have that part of the wiki link to this file?
> Specify that dictionary ID is little-endian

- index.html
When zstd 1.0 was released, I got very excited.
When I looked at the existing Python bindings, I was less excited. The existing Python bindings only support the simple compression API. They don't support streaming nor do they support dictionary compression: two features that are important to me.
In addition, the existing bindings have their own framing (they add a 32 bit length field at the beginning of output), making them incompatible with the zstd 1.0 framing protocol and other zstd implementations.
Long story short, I decided that it would be easier to create my own Python bindings than attempt to bring the existing bindings into a state I was happy with. So I did.
I feel my bindings are at least as good as the existing Python bindings and am requesting they be listed on the official …
> Add alternate Python bindings

- index.html
This package is different from **node-zstandard**. 
It's nodejs native module binding ZSTD's API.
> Add nodejs native module binding

- build/.gitignore
It seems that when the projects folder was moved to the new path in cfe5fe45819804b6ef148dc8524fcec1fcd1fc43, the `build/bin` was changed to `build/` instead of `bin/` and building makes a lot of stuff show up in git.
> Update .gitignore for new location of msbuild projects

- contrib/pzstd/Options.cpp
- contrib/pzstd/Pzstd.cpp
- contrib/pzstd/Pzstd.h
- contrib/pzstd/test/PzstdTest.cpp
At the end of (de)compression with verbosity > 1, print the same result line that zstd prints.  The result line should be printed in exactly the same conditions as zstd prints it.
Live updates of the (de)compression status is not currently included, as the writer thread doesn't know how much input corresponds to the output it receives.  This is doable, but I think it should be put off to a future version.  The change involves adding extra shared state, and I don't want to make changes to the multithreaded part of the code without having enough time to test them.
> [pzstd] Print (de)compression results

- lib/decompress/zstd_decompress.c
- lib/legacy/zstd_v04.c
- lib/legacy/zstd_v05.c
- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
`ZSTD_execSequences()` could write up to 7 bytes beyond the end of its buffer.
> Fix ZSTD_execSequence() edge case

- contrib/pzstd/test/OptionsTest.cpp
If I/O is not connected to a terminal
(like in a package build system for example),
a portion of the test expected to fail would pass.
This removes the system dependent test.
> pzstd: fix test failure on headless build

- lib/compress/zstd_compress.c
- lib/decompress/zstd_decompress.c
Each of the places fixed passed `NULL` to `memcpy()` during the run of `./contrib/pzstd/test/PzstdTest`.  The ubsan failures only showed up when testing with `qemu-aarch64`.
> Fix ubsan failures (pass NULL to memcpy)

- lib/decompress/zstd_decompress.c
- lib/legacy/zstd_v04.c
- lib/legacy/zstd_v05.c
- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
`memmove(op, match, sequence.matchLength)` is not the desired behavior.
Overlap is allowed, and handled as if we did `*op++ = *match++`, which
is not how `memmove()` handles overlap.
Only triggered if both of the following conditions are met:
* The match spans extDict & currentPrefixSegment
* `oLitEnd <= oend_w < oLitEnd + length1 < oMatchEnd <= oend`.
These two conditions imply that the block is less than 15 bytes long.
This bug isn't triggered by the streaming API, because it allocates
enough space for the window size + the block size, so there cannot be
a match that is within 8 bytes of the end and overlaps with itself.
It cannot be triggered by the block decompression API because all of
the decompressed data is in the currentPrefixSegment.
Introduced by commit …
> Fix small bug in ZSTD_execSequence()

- lib/decompress/zstd_decompress.c
Commit ae1cb3b3d07024618269b89e3421d828adfd34d9 caused the regression.
It is an instruction alignment issue, because if it is `U64 i` instead
of `U32 i`, the regression returns.  This patch fixes the regression
in gcc, but only gets some of the clang performance back.
Benchmarks:
Run on `silesia.tar`.  I only show levels 1-5 because the performance
regression was uniform across all levels.  I did one run on levels
1-19 and it looked good.
| Build | Level | Before | While | After |
|-------|-------|-------:|------:|------:|
| gcc   |     1 |  931.4 | 904.4 | 932.8 |
| gcc   |     2 |  849.1 | 822.6 | 851.2 |
| gcc   |     3 |  815.6 | 790.6 | 818.9 |
| gcc   |     4 |  794.1 | 770.7 | 798.0 |
| gcc   |     5 |  785.7 | 760.7 | 788.8 |
| clang |     1 |  705.5 | 683.2 | 693.8 |
| clang | …
> Fix ZSTD_execSequence() performance regression

- lib/common/zstd_internal.h
- lib/decompress/zstd_decompress.c
The zstd reference compressor will not emit a match in the last 7bytes of a block.  The decompressor will also not accept a match in the last 7 bytes.  This patch makes the decompressor accept a match in the last 7 bytes.
Something strange happens if you leave the check on line 904 as `(oLitEnd>oend_w) | (oMatchEnd>oend)`, which makes line 906 dead code.  Compiling with gcc, the decompressor runs more than 1% faster across the board.  It must be triggering some optimization pass that isn't triggered otherwise.
Benchmarks show that it slows decompression down slightly for levels 1-3 and 17-19, but speeds it up on the rest.  I'm not really sure why it would speed up though...
gcc
> ./zstd.base -b1 -e19 -i10 && ./zstd -b1 -e19 -i10
1#Synthetic 50%     :  10000000 ->   3141927 (3.183), 392.8 …
> ZSTD_execSequence() accepts match in last 7 bytes

- doc/zstd_compression_format.md
- doc/zstd_manual.html
- lib/compress/zstd_compress.c
- lib/zstd.h
Specify that when `dict == NULL || dictSize < 8` no dictionary
gets loaded.
Also add some periods.
> ZSTD_compress_usingDict() specify dict == NULL

- lib/decompress/zstd_decompress.c
- lib/legacy/zstd_v02.c
- lib/legacy/zstd_v03.c
- lib/legacy/zstd_v04.c
- lib/legacy/zstd_v05.c
- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
* Sets `WILDCOPY_OVERLENGTH` bytes beyond the end of the literals to `0` in the `litBuffer`.
* Removes `litBufSize` because in all cases we know that `litSize <= sizeof(litBuffer) - WILDCOPY_OVERLENGTH` or `litSize <= srcSize - lhSize - WILDCOPY_OVERLENGTH`, so as long as `iLitEnd <= litPtr + litSize` there is no uninitialized memory read with the `memset()`.
> Fix uninitialized memory read

- lib/zstd.h
Allow static linking section to be included even if zstd has already been included without it.
Minimal repro:
#include <zstd.h>
#define ZSTD_STATIC_LINKING_ONLY
#include <zstd.h>
ZSTD_frameParams params; /* Compiler error: ZSTD_frameParams not defined */
> Fix ZSTD_STATIC_LINKING_ONLY with double include

- lib/libzstd.pc.in
It is safe to use such variables for future maintainance.
> libzstd.pc.in: Change to use variables for libdir and includedir

- lib/compress/zstd_compress.c
- tests/.gitignore
- tests/Makefile
- tests/longmatch.c
The bug is exposed by [test.c](https://gist.github.com/terrelln/6b7c01740fc05b0bcf5b3572056c9869), and the test case is fixed after the patch.  I'm still unfamiliar with the compression code, so there maybe be consequences that I don't see, but I think this patch works.
When the overflow protection kicks in, it makes sure that `ip - ctx->base` isn't too large. However, it didn't ensure that saved offsets are still valid. This change ensures that any valid offsets (<= windowLog) are still representable after the update.
The bug would shop up on line 1056, when `offset_1 > current + 1`, which causes an underflow. This in turn, would cause a segfault on line 1063.
The input must necessarily be longer than 1 GB for this issue to occur. Even then, it only occurs if one of the last 3 matches is …
> Fix compression segfault

- lib/decompress/zstd_decompress.c
- lib/legacy/zstd_v01.c
- lib/legacy/zstd_v02.c
- lib/legacy/zstd_v03.c
- lib/legacy/zstd_v04.c
- lib/legacy/zstd_v05.c
- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
Allows an adversary to write up to 3 bytes beyond the end of the buffer.
Occurs if the match overlaps the `extDict` and `currentPrefix`, and the
match length in the `currentPrefix` is less than `MINMATCH`, and
`op-(16-MINMATCH) >= oMatchEnd > op-16`.
Benchmarks:
> ./zstd.base -b1 -e5 -i5
Benchmarking levels from 1 to 5
1#Synthetic 50%     :  10000000 ->   3141931 (3.183), 398.0 MB/s ,1548.2 MB/s
2#Synthetic 50%     :  10000000 ->   3117899 (3.207), 282.7 MB/s ,1496.1 MB/s
3#Synthetic 50%     :  10000000 ->   3225553 (3.100), 174.0 MB/s ,1159.0 MB/s
4#Synthetic 50%     :  10000000 ->   3315489 (3.016), 142.1 MB/s , 974.4 MB/s
5#Synthetic 50%     :  10000000 ->   3266973 (3.061),  99.0 MB/s , 969.2 MB/s
> ./zstd -b1 -e5 -i5
Benchmarking levels from 1 to 5
1#Synthetic 50%     :  10000000 -> …
> Fix decompression bug

- lib/common/zstd_internal.h
- lib/decompress/zstd_decompress.c
- lib/legacy/zstd_v01.c
- lib/legacy/zstd_v02.c
- lib/legacy/zstd_v03.c
- lib/legacy/zstd_v04.c
- lib/legacy/zstd_v05.c
- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
execSequence relied on pointer overflow to handle cases where
`sequence.matchLength < 8`.  Instead of passing an `size_t` to
wildcopy, pass a `ptrdiff_t`.
Benchmarks:
> ./zstd.base -b1 -e5 -i5
Benchmarking levels from 1 to 5
1#Synthetic 50%     :  10000000 ->   3141931 (3.183), 398.0 MB/s ,1548.2 MB/s
2#Synthetic 50%     :  10000000 ->   3117899 (3.207), 282.7 MB/s ,1496.1 MB/s
3#Synthetic 50%     :  10000000 ->   3225553 (3.100), 174.0 MB/s ,1159.0 MB/s
4#Synthetic 50%     :  10000000 ->   3315489 (3.016), 142.1 MB/s , 974.4 MB/s
5#Synthetic 50%     :  10000000 ->   3266973 (3.061),  99.0 MB/s , 969.2 MB/s
> ./zstd -b1 -e5 -i5
Benchmarking levels from 1 to 5
1#Synthetic 50%     :  10000000 ->   3141931 (3.183), 394.8 MB/s ,1548.7 MB/s
2#Synthetic 50%     :  10000000 ->   3117899 (3.207), …
> Fix execSequence wildcopy undefined behavior

- contrib/pzstd/Options.cpp
- programs/util.h
- programs/zstdcli.c
- tests/playTests.sh
* Add `-D_POSIX_C_SOURCE=200112L` to enable POSIX functionality
* Remove last bashism from `tests/playTests.sh`
* Use `gmd5sum` from the sysutils/coreutils port
> Make zstd build out of the box properly on FreeBSD

- .travis.yml
- appveyor.yml
- build/VS2005/zstdlib/zstdlib.vcproj
- build/VS2010/libzstd-dll/libzstd-dll.vcxproj
- build/VS2010/libzstd/libzstd.vcxproj
- build/cmake/lib/CMakeLists.txt
- lib/common/zstd_common.c
- lib/common/zstd_errors.h
- lib/deprecated/zbuff_common.c
- lib/dictBuilder/zdict.h
- lib/zstd.h
- tests/.gitignore
- tests/Makefile
- tests/symbols.c
In `zstd_common.c`, since `zbuff.h` wasn't included, the symbols are by default
hidden in the shared library, and the exported symbols aren't defined.
> Export ZBUFF_isError() and ZBUFF_getErrorName()

- lib/dictBuilder/zdict.c
- lib/dictBuilder/zdict.h
- tests/symbols.c
1.  `ZDICT_DEPRECATED` needs to include `ZDICTLIB_API` or the symbols won't be exported
2.  `symbols.c` needs `ZDICT_DISABLE_DEPRECATE_WARNINGS` defined
3.  `ZDICT_finalizeDictionary()` had a comparison that was flipped
4.  Allow `dictBufferCapacity == dictContentSize`
> Fix failing test due to deprecation warning

- programs/zstdless
Fixes #496.
Adds a shebang line to `zstdless` so it works under more environments.
Quotes the `$@` variable to protect against spaces etc in the input filenames.
> zstdless: add shebang and quote $@

- contrib/pzstd/Makefile
Fixes the problem that the compiler doesn't enable c++11 mode by default and the package build system has its own CXXFLAGS.
> Move -std=c++11 cxxflag to PZSTD_CXXFLAGS

- .travis.yml
- NEWS
- lib/common/pool.c
- lib/common/pool.h
- lib/compress/zstd_compress.c
- lib/decompress/zstd_decompress.c
- lib/dictBuilder/zdict.c
- tests/.gitignore
- tests/Makefile
- tests/pool.c
Adds a thread pool in `common/pool.{c, h}`.
Adds simple tests for the thread pool.
If pthreads isn't available, which is determined by `#ifdef ZSTD_PTHREAD`, it falls back to executing the functions inline.
I'm merging it into zstdmt .  I will need it, or something similar, eventually for the dictionary builder.  I can either merge the dictionary builder into the zstdmt branch, or I can remove the multithreaded functionality until the zstdmt branch is merged into dev.  Which do you think would be better?
> [zstdmt] Add thread pool

- .travis.yml
- lib/common/pool.c
- lib/common/pool.h
- lib/common/threading.c
- lib/common/threading.h
- tests/Makefile
- tests/pool.c
Add support for condition variables to `threading.h`.  This initial implementation only works for Windows Vista and above.  Supporting earlier Windows versions will require a custom implementation of condition variables.  However, adding support for older Windows only requires changing the threading files, so it can be done transparently.
> pthread_cond_t

- build/VS2005/fuzzer/fuzzer.vcproj
- build/VS2005/zstd/zstd.vcproj
- build/VS2005/zstdlib/zstdlib.vcproj
- build/VS2008/fuzzer/fuzzer.vcproj
- build/VS2008/zstd/zstd.vcproj
- build/VS2008/zstdlib/zstdlib.vcproj
- build/VS2010/fuzzer/fuzzer.vcxproj
- build/VS2010/libzstd-dll/libzstd-dll.vcxproj
- build/VS2010/libzstd/libzstd.vcxproj
- build/VS2010/zstd/zstd.vcxproj
- build/cmake/lib/CMakeLists.txt
- lib/dictBuilder/cover.c
- lib/dictBuilder/zdict.h
- programs/dibio.c
- programs/dibio.h
- programs/zstdcli.c
- tests/fuzzer.c
- tests/playTests.sh
Adds dictionary builder based off of the heuristic in [Effective Construction of Relative Lempel-Ziv Dictionaries](http://www2016.net/proceedings/proceedings/p807.pdf).  It divides the input equally into epochs.  Then it looks at each segment of length `k` in the epoch and picks the one with the best score.  The score of a segment is the sum of the frequencies of the segments of length `d` it covers.  `k` is called the segment size, and `d` is called the dmer size.  It continues this until the dictionary is full.
1.  `COVER_trainFromBuffer()` builds a dictionary with a set segment size and dmer size.  This functionality can be used on the CLI as `zstd --train --cover=k=#,d=# ...`.
2.  `COVER_optimizeTrainFromBuffer()` tries a bunch of different segment and dmer sizes.  Optional either `k` …
> Add new dictionary builder

- lib/dictBuilder/cover.c
- lib/dictBuilder/zdict.h
- programs/dibio.c
* The cover algorithm requires a single buffer of 4x the input size, so in 32-bit mode, the maximum input size is 1 GB.
* Document the memory requirements for the cover dictionary builder.
* Make error messages on OOM or too large input clearer.
> Handle cover dictionary builder maximum input size for 32-bit mode

- lib/decompress/zstd_decompress.c
- tests/fuzzer.c
Tests pass on travis and appveyor
> Fixed decompress_usingDict not propagating corrupted dictionary error

- lib/compress/zstd_compress.c
When porting python-zstandard to use ZSTD_initCStream_usingCDict()
so compression dictionaries could be reused, an automated test
failed due to compressed content changing.
I tracked this down to ZSTD_initCStream_usingCDict() not
setting the dictID field of the ZSTD_CCtx attached to the
ZSTD_CStream instance.
I'm not 100% convinced this is the correct or full solution,
as I'm still seeing one automated test failing with this change.
> Set dictionary ID in ZSTD_initCStream_usingCDict()

- tests/zstreamtest.c
It was reading beyond the end of the input buffer because no errors were
detected. Once that was fixed, it wasn't making forward progress because
no errors were detected and it was waiting for input.
> Fix segfault in zstreamtest MT

- build/VS2005/fuzzer/fuzzer.vcproj
- build/VS2005/zstdlib/zstdlib.vcproj
- build/VS2008/fuzzer/fuzzer.vcproj
- build/VS2008/zstdlib/zstdlib.vcproj
- build/VS2010/fuzzer/fuzzer.vcxproj
- build/VS2010/libzstd-dll/libzstd-dll.vcxproj
- build/VS2010/libzstd/libzstd.vcxproj
- build/cmake/lib/CMakeLists.txt
- lib/common/pool.h
- lib/compress/zstdmt_compress.c
- lib/compress/zstdmt_compress.h
- lib/dictBuilder/cover.c
- lib/dictBuilder/zdict.h
- programs/zstdcli.c
* The cover optimizing trainer now uses threads if `ZSTD_MULTITHEAD` is defined.
* Add include guards and `extern "C"` to `pool.h`, `threading.h` and `zstdmt_compress.h`.
* Fix up VS builds to include `pool.{c, h}`, `threading.{c, h}`, and `zstdmt_compress.{c, h}`.
Appveyor has passed on my branch, and the travis tests that get run have also passed.
> Multithreaded COVER dictionary training

- programs/Makefile
- programs/fileio.c
I'm not sure how to test this. I tried adding the flag `-nostdinc` and them adding back in the standard includes with `-isystem`, which supposedly doesn't add paths to the quotes include path, but gcc and clang both still allowed `"zlib.h"` to be included.
However, we can ensure that `#include <zlib.h>` works in the `HAVE_ZLIB` test.
> Change zlib include to be a system include

- lib/dictBuilder/cover.c
* Move blurb to the top of `cover.c`.
* Add missing attribution.
> Attribute cover dictionary code

- contrib/educational_decoder/README.md
- contrib/educational_decoder/harness.c
- contrib/educational_decoder/zstd_decompress.c
- contrib/educational_decoder/zstd_decompress.h
Add a self-contained decoder that implements the Zstandard format specification and can be used as the base for alternate implementations, or to gain a better understanding of how the format works without the tricks and optimizations of the reference implementation.
> Add educational decoder to /contrib

- .travis.yml
- tests/Makefile
It was timing out in `qemu` runs.
The travis file should be ok, but it doesn't run the modified test on my branch, so the PR tests will determine if it is ok.
> Remove test-longmatch from test target and only run it once

- lib/common/zstd_common.c
- tests/fuzzer.c
ZSTD_getErrorString previous delegated to ERR_getErrorName instead of ERR_getErrorString, causing it to function incorrectly.
> Fix ZSTD_getErrorString and add tests

- lib/deprecated/zbuff.h
- lib/dictBuilder/zdict.h
- programs/platform.h
* Clang doesn't allow C++14 attributes to go after `__attribute__(())`, so reorder them.
* A compiler was complaining about redefinition of `_POSIX_C_SOURCE`, @inikep is this change correct?
> Fix small bugs

- programs/util.h
On MinGW, use _stat64() and struct _stat64 instead of stat() and struct stat_t. This fixes reporting incorrect sizes for large files.
> zstdcli: Fix reporting incorrect sizes of large flies on MinGW

- programs/fileio.c
There is another bug related to large files on Windows (MinGW, likely also VC++).
1. Generate zero-filled file larger than 2048 MB
`dd if=/dev/zero of=testfile bs=1M count=2049`
(see [other solutions](http://stackoverflow.com/questions/982659/quickly-create-large-file-on-a-windows-system) if you don't have dd)
2. Create compressed test file
`zstd -1 testfile -o testfile.zst`
3. Attempt to decompress or test it
`zstd --test testfile.zst`
sample result:
`Decoded : 2005 MB...     Error 71 : 1 GB skip error (sparse file support)`
`fseek()` fails if file position indicator is over 2GB (even for small relative offset). This leads to skip errors in `FIO_fwriteSparse()`/`FIO_fwriteSparseEnd()` during decompression of large sparse files.
`_FILE_OFFSET_BITS=64` does not help there, even for MinGW …
> zstdcli: fix writing 2GB+ sparse files under Windows

- examples/simple_compression.c
there was a small issue of memory leak for output file name in the example, simple free() should fix it
> fix memory leak

- lib/common/threading.c
When ZSTD_MULTITHREAD is not defined, `lib/common/threading.c ` triggers empty translation unit warning, which is currently suppressed only under MSVC++.
It may be worth to consider building lib in strict standards mode, and this is currently the only warning generated by `-pedantic` under GCC and Clang. It could be suppressed for GCC/Clang another `#pragma`, but proposed commit avoids this problem in a portable way by including one of standard C headers.
> Portable way to avoid empty unit warning in threading.c

- lib/compress/zstd_compress.c
- tests/Makefile
```
make zstreamtest CC=clang CFLAGS="-O3 -g -fsanitize=memory -fsanitize-memory-track-origins"
./zstreamtest -vv -t4178 -i4178 -s4531
```
* 2 breaks at zstd_compress.c:2418  -- in ZSTD_compressContinue_internal()
* 2 breaks at zstd_compress.c:2276  -- in ZSTD_compressBlock_internal()
* 1 break at zstd_compress.c:1547
When `zc->forceWindow == 1`, after calling `ZSTD_loadDictionaryContent()` we
have `zc->loadedDictEnd == zc->nextToUpdate == 0`. But, we've really loaded up
to `iend` into the dictionary. Then in `ZSTD_compressBlock_internal()` we see
that `current > zc->nextToUpdate + 384`, so we load the last 192 bytes a second
time. In this case the bytes we are loading are a block of all 0s, starting in
the previous block. So when we are loading the last 192 bytes, we find a `match`
in …
> [zstdmt] Fix MSAN failure with ZSTD_p_forceWindow

- lib/decompress/zstd_decompress.c
- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
- tests/zstreamtest.c
In decompression streaming mode, `outBuff` was small enough that under special conditions, the position in the buffer could be reset, causing writes to be made too close to data still in the window, and wildcopy would overwrite this data.  Fixed by extending `outBuff` by `WILDCOPY_OVERLENGTH` bytes.
> Fix wildcopy overwriting data still in window

- lib/decompress/zstd_decompress.c
- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
- tests/zstreamtest.c
#549 didn't extend the buffers enough for all cases.
> execSequence copies up to 2*WILDCOPY_OVERLENGTH extra

- doc/zstd_compression_format.md
Take various sections of the format specification and re-order them to put related sections together and avoid interleaving unrelated info (e.g. separating entropy encoding primitives from how they are used).
> Restructure Format Specification

- examples/dictionary_decompression.c
- examples/simple_decompression.c
In the directory zstd/examples,
After the command, "./streaming_compression README.md"
the following command always fails. ( malloc: can not allocate... )
./simple_decompression README.md.zst
because
ZSTD_findDecompressedSize(cBuff, cSize);
always return "ZSTD_CONTENTSIZE_UNKNOWN" not "0"
By the way, 
is that OK? the file compressed by streaming can not be simple decompressed 
because I can not get decomprssed size?
> original size unknown

- circle.yml
- contrib/educational_decoder/README.md
- tests/.gitignore
- tests/Makefile
- tests/README.md
- tests/decodecorpus.c
Command line tool to generate test .zst files.
Example:
```
./decodecorpus -ptestfiles -otestfiles -n10000 -s1
```
will generate 10,000 sample .zst files in the `testfiles` directory with the zstd checksum field set, as well as the 10,000 original files for more detailed comparison of decompression results.
```
./decodecorpus -t -T1mn
```
will choose a random seed, and for 1 minute, generate random test frames and ensure that the zstd library correctly decompresses them in both simple and streaming modes.
Note: Does not handle dictionaries currently
> Create a tool that generates random, valid, Zstd frames for decoder testing

- lib/decompress/zstd_decompress.c
- tests/fuzzer.c
- tests/zstreamtest.c
for "one-pass" scenarios.
Provides ~5% additional performance, by avoiding skippable `memcpy()` and `malloc()` tasks.
> Improve streaming decompression speed

- lib/decompress/zstd_decompress.c
Need to add some helper functions too due to definition order
> Check to ensure ddict isn't null before dereference

- lib/decompress/zstd_decompress.c
Caught by running `zstreamtest` with MSAN.
> Set dictID to 0 for content only dictionaries

- lib/common/huf.h
- lib/compress/huf_compress.c
- lib/compress/zstd_compress.c
* Compressor saves most recently used Huffman table and reuses it
if it produces better results.
* I attempted to preserve CPU usage profile.
I intentionally left all of the existing heuristics in place.
There is only a speed difference on the second block and later.
When compressing large enough blocks (say >= 4 KiB) there is
no significant difference in compression speed.
Dictionary compression of one block is the same speed for blocks
with literals <= 1 KiB, and after that the difference is not
very significant.
* In the synthetic data, with blocks 10 KB or smaller, most blocks
can't use repeated tables because the previous block did not
contain a symbol that the current block contains.
Once blocks are about 12 KB or more, most previous blocks have
valid Huffman tables for the current …
> Allow compressor to repeat Huffman tables

- lib/common/huf.h
- lib/compress/huf_compress.c
- lib/compress/zstd_compress.c
The compressor always reuses the existing Huffman table if the literals
size is at most 1 KiB. If the compression strategy is `ZSTD_lazy` or
stronger always check to see if reusing the previous table or creating
a new table is better.
This doesn't yet weigh in decompression speed.
> Always check Huffman tables for ZSTD_lazy+

- .buckconfig
- contrib/pzstd/Pzstd.cpp
- contrib/pzstd/Pzstd.h
Fedora now enables this option by default, resulting
in the following build failure:
Logging.h: In instantiation of
'void pzstd::Logger::operator()(int, const char*, Args ...)
Pzstd.cpp:413:48:   required from here
Logging.h:46:17: error: format not a string literal and no format arguments
[-Werror=format-security]
std::fprintf(out_, fmt, args...);
~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
> support -Werror=format-security

- lib/compress/zstd_compress.c
If we wait until `(2U<<30)` we risk doing some pointer subtractions where the difference is greater than or equal to `1<<31`, which is undefined behaviour on 32-bit architectures.  Found by running `playTests.sh --test-large-data` with ubsan.
> Reduce point at which we reduce offsets to protect against UB

- lib/compress/zstd_compress.c
- lib/decompress/huf_decompress.c
* Take `sizeof(*zcs)` instead of `sizeof(zcs)`.
* Avoid defining `inline`, and use the `FORCE_INLINE` definition from `zstd_internal.h` instead.
> Small fixes

- programs/Makefile
zstd-internal was intended to be a helper target, but it doesn't help
at all, what it does in practice is a useless rebuild of zstd every time
"make zstd" is invoked.
Fixes: 030ac243a0f3 ("Changed Makefile to generate zstd with .gz support by default")
> programs/Makefile: remove zstd-internal target

- lib/common/mem.h
- lib/decompress/zstd_decompress.c
Fix some places where we subtract pointers that aren't in the same object, leading to potential undefined behaviour.
> Fix undefined behaviour in decompressor

- programs/Makefile
- programs/fileio.c
- programs/fileio.h
- programs/zstdcli.c
- tests/playTests.sh
Finish feature started by @inikep.
* Add xz and lzma compression and decompression support to target `xzstd`.
* Fix bug in gzip decompression that silently accepted truncated files.
* Add gzip frame composition tests.
* Add xz/lzma compatibility tests.
* Add xz/lzma frame composition tests.
> Add xz and lzma support.

- .gitattributes
- .travis.yml
Introduce the long tests onto the master branch.  If merged before 1.1.4 release, these tests will fail on master until the release (as they test behaviour that's been fixed since 1.1.3), but the crons should pass.  The config is set up so that when this branch is built as a cron, it actually builds `dev` branch, using the long test config (to get things such as OS X testing, etc.), so after merging a cron should be set up on TravisCI on master branch.
This will cause merge conflicts for release merges (`dev -> master`).  These should be resolved in favour of the version in master, and never merged back into `dev` branch.
Alternatively, the `.gitattributes` change should make this easy, if
```
git config --local merge.ours.driver true
```
is run within a `zstd` clone, then merging `dev` …
> Update .travis.yml for long tests (master branch only)

- programs/zstdcli.c
- tests/playTests.sh
Not sure I understand why the condition was the way it was before, but I don't think this should break any case that worked properly before.
Fixes this case writing compressed data to term:
```
echo bob | zstd
```
> Fix zstd not erroring on compressing to terminal without forceStdout

- lib/compress/zstd_compress.c
- lib/decompress/zstd_decompress.c
Set pointers to `NULL` after freeing, to help make use after free errors more obvious in optimized builds.
> Zero pointers after freeing

- programs/Makefile
* If zlib/lzma isn't in the usual spot, it won't be used,
even if `$CFLAGS` and `$LDFLAGS` add the location it is in.
* Update the test code snippets to not trigger any warnings.
* Some MinGW versions need to explicitly add `$(EXT)`, otherwise `rm have_zlib$(EXT)` will fail.
Tests:
* On my Mac both zlib and lzma are detected with clang and gcc-6
* On linux with gcc-4.8.5 both zlib and lzma are detected
* On Appveyor, the only failure to detect zlib is the second test, which happens because it can't find `zlib.h`.
* On CircleCI, all tests detect zlib except the cross-compilation tests, as expected.
> Add $(FLAGS) when testing for zlib/lzma support.

- contrib/pzstd/Options.cpp
- lib/dictBuilder/cover.c
- lib/dictBuilder/zdict.c
- programs/bench.c
- programs/dibio.c
- programs/fileio.c
- programs/util.h
- programs/zstd.1
- programs/zstd.1.md
- programs/zstdcli.c
- tests/fuzzer.c
- tests/playTests.sh
- tests/zbufftest.c
- tests/zstreamtest.c
- zlibWrapper/examples/zwrapbench.c
Without `--force`, attempting to follow/(de)compress symbolic links will display a warning and move on.
With g_displayLevel as unsigned, `-qqq` would trigger maximum verbosity mode, which seems like incorrect behaviour.
> Match gzip behaviour on symbolic links and change g_displayLevel to int

- lib/common/error_private.c
- lib/common/zstd_errors.h
- lib/dictBuilder/zdict.c
- programs/zstdcli.c
- tests/playTests.sh
Properly expressed with an error code (see zstd_errors.h)
and a cli return code != 0
> dictBuilder fails to create dictionary on certain input

- appveyor.yml
With this, `zstd_x86.exe` and `zstd_x64.exe` artifacts on appveyor will be statically linked to `zlib`, and can be bundled and released with the windows packages.
> Statically build and link zlib on appveyor

- lib/dictBuilder/zdict.c
- lib/dictBuilder/zdict.h
Now uses ZDICT_DICTSIZE_MIN and ZDICT_CONTENTSIZE_MIN
from zdict.h.
Also : reduced limit values to 256 and 128 respectively
> Ensure all limits derived from same constants

- lib/dictBuilder/zdict.c
- programs/zstd.1
- programs/zstd.1.md
- programs/zstdcli.c
- tests/playTests.sh
now works with the `=` variant, which is the recommended one.
Old variant `--dictID #` still works, for compatibility with existing scripts.
Long term objective is to remove the old variant..
> changed advanced commands --maxdict= and --dictID=

- programs/platform.h
Fixes same issue as https://github.com/lz4/lz4/pull/342, tested locally.
> Fix IS_CONSOLE returning 1 for NUL on windows

- lib/decompress/zstd_decompress.c
Didn't cause correctness issues, but technically was too large for its type.
> Remove extra 'F' from skippable magic mask

- lib/common/bitstream.h
- lib/common/mem.h
- lib/compress/fse_compress.c
- lib/compress/zstd_compress.c
- lib/compress/zstd_opt.h
- lib/dictBuilder/zdict.c
- lib/legacy/zstd_v01.c
- lib/legacy/zstd_v02.c
- lib/legacy/zstd_v03.c
- lib/legacy/zstd_v04.c
- lib/legacy/zstd_v05.c
- lib/legacy/zstd_v06.c
- programs/util.h
- tests/fullbench.c
Generated with the following command and manually checked:
```
sed -i '' $'s/\t/    /g' lib/**/*.{h,c} programs/**/*.{h,c} tests/**/*.c contrib/**/*.{h,c} examples/**/*.c zlibWrapper/**/*.{h,c}
```
> Convert all tabs to spaces

- lib/common/mem.h
Method 1 `__packed` is always as good or better than `memcpy()`.
But it's not portable, as it depends on compiler extension.
For `gcc`, `__packed` directive works fine.
Furthermore, `gcc` has serious performance issues with `memcpy()` on ARM 32 bits.
See #620
> Changed memory strategy to __packed for gcc

- lib/compress/zstd_compress.c
- lib/compress/zstdmt_compress.c
- programs/zstd.1
- programs/zstd.1.md
- programs/zstdcli.c
- tests/zstreamtest.c
will no longer allocated temporary buffer
if there is enough space in provided `dstBuffer` to compress directly there.
> Optimize ZSTDMT_compress() memory usage

- lib/compress/zstd_compress.c
- tests/fuzzer.c
- tests/zstreamtest.c
* Fix `ZSTD_initCStream_usingCDict()` to use the dictionary
* Make `ZSTD_compress_usingCDict()` respect contentSizeFlag.
> Fix ZSTD_initCStream_usingCDict() and ZSTD_compress_usingCDict()

- lib/common/fse.h
- lib/compress/fse_compress.c
Reduce stack usage of `FSE_compress_wksp()` by 4 KiB.
> Switch call of FSE_count() to FSE_count_wksp()

- tests/playTests.sh
Mainly tests a file slightly larger than 4GB to catch 32-bit issues.  Ran a few times on both appveyor and travis and it worked every time, so it doesn't seem like it'll be an issue.
Tested with zstd v1.1.3 to confirm it fails.
> Test large files on-disk in playTests.sh

- programs/bench.c
- programs/dibio.c
- programs/fileio.c
- programs/util.h
- programs/zstdcli.c
Need separate core counting routines for windows, OS X, and Linux.
Tested on (HT: HyperThreading):
Mac, HT
Linux, HT
Linux, no HT
Windows, no HT
Linux, Aarch64, no HT
> Make -T0 mean "number of physical cores"

- programs/Makefile
This avoids conflicts between how the library was configured and how the CLI was configured.
> Compile CLI using files instead of objs

- programs/fileio.c
Using fix suggested by @terrelln
> Fix LZ4 wrapper deprecation warnings

- doc/zstd_manual.html
- lib/common/fse.h
- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/zstd.h
reduce memory space of CCtx structure
CCtx might be on the stack for some scenario (ZSTD_compress)
transferred into workSpace,
which is always dynamically allocated from heap
> Small cctx

- contrib/pzstd/utils/test/ThreadPoolTest.cpp
- contrib/pzstd/utils/test/WorkQueueTest.cpp
The tests sometimes hang on Appveyor. Add logging statements to the tests that have hung to find out where it is hanging.
> [pzstd] Add logging statements to tests

- contrib/linux-kernel/include/linux/zstd.h
- contrib/linux-kernel/lib/zstd/compress.c
- contrib/linux-kernel/lib/zstd/decompress.c
- contrib/linux-kernel/test/UserlandTest.cpp
Since we require memory to already be allocated, and nothing needs to be freed, the functions are initialization, not creation.
> [kernel] Rename ZSTD_create*() to ZSTD_init*()

- doc/zstd_manual.html
- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstdmt_compress.c
- lib/zstd.h
- programs/bench.c
- programs/fileio.c
- tests/fuzzer.c
- tests/zstreamtest.c
- zlibWrapper/examples/zwrapbench.c
ZSTD_createCDict_advanced() only sets `compressionParameters`.
New prototypes `*_usingCDict_advanced()`, allowing to set `frameParameters`.
> Breaking API Change around CDict

- contrib/linux-kernel/fs/squashfs/zstd_wrapper.c
- contrib/linux-kernel/squashfs.diff
Depends on https://github.com/facebook/zstd/pull/679 and existing zstd kernel patch.
Tested locally using https://github.com/iburinoc/squashfs-tools on 4.6-rc7 kernel.
> SquashFS linux kernel patch

- programs/fileio.c
- tests/playTests.sh
The problematic srcfile will be named on console/log,
but decompression/test will continue onto next file in the list.
The final operation result will still be an error, as soon as one file in the list fails.
> cli : -d and -t do not stop after a failed decompression

- lib/common/bitstream.h
The following warning appears during the build:
```
zstd/lib/common/bitstream.h: In function ‘BIT_initDStream’:
zstd/lib/common/bitstream.h:277:33: warning: this statement may fall through [-Wimplicit-fallthrough=]
case 7: bitD->bitContainer += (size_t)(((const BYTE*)(srcBuffer))[6]) << (sizeof(bitD->bitContainer)*8 - 16);
zstd/lib/common/bitstream.h:278:6: note: here
case 6: bitD->bitContainer += (size_t)(((const BYTE*)(srcBuffer))[5]) << (sizeof(bitD->bitContainer)*8 - 24);
zstd/lib/common/bitstream.h:278:33: warning: this statement may fall through [-Wimplicit-fallthrough=]
case 6: bitD->bitContainer += (size_t)(((const BYTE*)(srcBuffer))[5]) << (sizeof(bitD->bitContainer)*8 - 24);
zstd/lib/common/bitstream.h:279:6: note: here
case 5: bitD->bitContainer += (size_t)(((const …
```
> lib/common: warning: this statement may fall through

- lib/compress/huf_compress.c
- lib/compress/zstd_compress.c
The following warning appears during build.
```
../lib/compress/huf_compress.c: In function ‘HUF_compress1X_usingCTable’:
../lib/compress/huf_compress.c:444:8: warning: this statement may fall through [-Wimplicit-fallthrough=]
if (sizeof((stream)->bitContainer)*8 < HUF_TABLELOG_MAX*4+7) HUF_FLUSHBITS(stream)
^
../lib/compress/huf_compress.c:465:18: note: in expansion of macro ‘HUF_FLUSHBITS_2’
HUF_FLUSHBITS_2(&bitC);
^~~~~~~~~~~~~~~
../lib/compress/huf_compress.c:466:9: note: here
case 2 : HUF_encodeSymbol(&bitC, ip[n+ 1], CTable);
../lib/compress/zstd_compress.c: In function ‘ZSTD_compressStream_generic’:
../lib/compress/zstd_compress.c:3366:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
zcs->streamStage = zcss_flush;   /* pass-through to flush stage */ …
```
> lib/compress: warning: this statement may fall through

- lib/legacy/zstd_v04.c
- lib/legacy/zstd_v05.c
- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
The following warning appears during build at sevaral places.
```
../lib/legacy/zstd_v04.c:819:40: warning: this statement may fall through [-Wimplicit-fallthrough=]
case 7: bitD->bitContainer += (size_t)(((const BYTE*)(bitD->start))[6]) << (sizeof(size_t)*8 - 16);
../lib/legacy/zstd_v05.c:821:40: warning: this statement may fall through [-Wimplicit-fallthrough=]
case 7: bitD->bitContainer += (size_t)(((const BYTE*)(bitD->start))[6]) << (sizeof(size_t)*8 - 16);
../lib/legacy/zstd_v06.c:913:40: warning: this statement may fall through [-Wimplicit-fallthrough=]
case 7: bitD->bitContainer += (size_t)(((const BYTE*)(srcBuffer))[6]) << (sizeof(bitD->bitContainer)*8 - 16);
../lib/legacy/zstd_v07.c:583:40: warning: this statement may fall through [-Wimplicit-fallthrough=]
case 7: …
```
> lib/legacy: warning: this statement may fall through

- lib/common/zstd_errors.h
- lib/dictBuilder/zdict.h
- lib/zstd.h
Useful if users want to hide all of zstd symbols.
> [libzstd] Allow users to define custom visibility

- build/cmake/CMakeLists.txt
- build/cmake/CMakeModules/AddZstdCompilationFlags.cmake
- build/cmake/lib/CMakeLists.txt
- build/cmake/programs/CMakeLists.txt
Several fixes and improvements to CMake build. Quick overview:
- Ensure XXHash symbols are hidden.
- Add option to disable build of shared library.
- Link zstd CLI to static library, as it uses symbols that are not public interface of libzstd. This helps to avoid any dllexport or so visibility issues. Fixes #707.
- Rework MSVC flag handling
-  Remove most of them as CMake defaults are pretty good as is. This fixes /RTC1-in-release problem described in #707 and prevents bunch of unnecessary warnings.
- Add option allowing linking to static run-time library
- Enable install target on Windows.
- Install zstd_errors.h (currently it is installed by makefile, but not in CMake)
- Rename static library when compiling with MSVC to avoid name conflict with import library.
> CMake improvements

- contrib/linux-kernel/kernelize.sh
- contrib/linux-kernel/lib/zstd/compress.c
- contrib/linux-kernel/lib/zstd/decompress.c
- contrib/linux-kernel/lib/zstd/fse.h
- contrib/linux-kernel/lib/zstd/fse_compress.c
- contrib/linux-kernel/lib/zstd/fse_decompress.c
- contrib/linux-kernel/lib/zstd/huf_compress.c
- contrib/linux-kernel/lib/zstd/huf_decompress.c
- lib/compress/huf_compress.c
- lib/compress/zstd_compress.c
- lib/decompress/huf_decompress.c
- lib/decompress/zstd_decompress.c
* Delete `FSE_COMMONDEFS_ONLY` from kernel code.
* Fix clang-formatting edge cases. Change `/lib` as well.
* `ZSTD_decompressStream()` ends a scope for a case early, clang-format doesn't like that, so extend that scope.
* Whitespace only changes for `/lib`.
> [linux-kernel] Minor formatting changes

- lib/Makefile
The macro name is ZSTD_MULTITHREAD, not ZSTD_MULTHREAD.
Fixes: ca6fae78080d ("Add MT enabled targets for libzstd")
> Fix typo in libzstd.a-mt make rules

- contrib/linux-kernel/lib/zstd/Makefile
- contrib/linux-kernel/lib/zstd/compress.c
- contrib/linux-kernel/lib/zstd/zstd_opt.h
- contrib/linux-kernel/zstd.diff
* Fix clang-formatting edge case for goto labels.
* Fix Makefile in the case where both `zstd_compress` and `zstd_decompress` are built into the kernel.
> [linux-kernel] Fix formatting and Makefile

- lib/Makefile
INSTALL_LIB can be passed -s flag to strip symbols. Static libraries should not be stripped, only dynamic ones should be stripped.
> INSTALL_DATA instead of INSTALL_LIB for libzstd.a

- contrib/linux-kernel/lib/zstd/decompress.c
- contrib/linux-kernel/test/UserlandTest.cpp
- contrib/linux-kernel/zstd.diff
Added test fails before the change, and succeeds after.
> [linux] Fix decompression memory allocation

- lib/compress/zstd_compress.c
Detected by a check added to UBSAN in trunk clang.
> [libzstd] Fix UBSAN failure

- contrib/pzstd/Pzstd.cpp
The `outs` queue is bounded, so if an error occurs, one or more threads could be waiting to push something onto the queue, so we need to pop things off. It won't infinite loop, since there is an error. We know that the producer won't push more than 1 more thing onto the queue, and will call `finish()`.
Fixes #720.
> [pzstd] Fix potential deadlock in the case of errors

- Makefile
- programs/Makefile
- programs/README.md
- programs/fileio.c
- programs/zstdcli.c
- tests/playTests.sh
* Support lzma by default
* Fix conversion warnings
* Review lzma compression/decompression code
> [zstdcli] Support xz by default when liblzma is available

- doc/zstd_manual.html
- lib/compress/zstd_compress.c
- lib/decompress/zstd_decompress.c
- lib/zstd.h
- tests/fuzzer.c
- tests/paramgrill.c
- tests/zstreamtest.c
After redacting https://github.com/facebook/zstd/issues/21#issuecomment-310737366, it felt that the previous `*_initStatic*()` had shortcomings making it a bit unnecessary complex to use.
This proposal improves usability on 2 points : 
- Simplified `*_estimate*()` functions : In particular, the compression estimations were using `ZSTD_compressParameters` type as argument, which is an advanced struct. The new version now requests a simpler `int compressionLevel` for basic prototypes, while still allowing the richer `cParams` in `_advanced()` version. `*_estimateDStreamSize*()` has been updated too, requesting a `size_t windowLog` rather than more peculiar `ZSTD_frameHeader` type, to be easier to invoke.
- Added `ZSTD_initStatic{C,D}Stream()`, which are merely redirections towards …
> simplified API for *initStatic*()

- lib/dictBuilder/cover.c
- lib/dictBuilder/zdict.c
- lib/dictBuilder/zdict.h
- programs/dibio.c
- programs/dibio.h
- programs/zstdcli.c
- tests/fuzzer.c
- tests/symbols.c
* Prefix legacy dictionary builder functions with `LEGACY` instead of `ZDICT`.
* Extract common parameters into `ZDICT_params_t`.
* The stable API keeps the `ZDICT` prefix, and users of the advanced API
explicitly choose an algorithm `COVER` or `LEGACY`.
> [zdict] Make COVER the default algorithm

- contrib/linux-kernel/0000-cover-letter.patch
- contrib/linux-kernel/0001-lib-Add-xxhash-module.patch
- contrib/linux-kernel/0002-lib-Add-zstd-modules.patch
- contrib/linux-kernel/0003-btrfs-Add-zstd-support.patch
- contrib/linux-kernel/0004-squashfs-Add-zstd-support.patch
- contrib/linux-kernel/lib/xxhash.c
- contrib/linux-kernel/lib/zstd/compress.c
- contrib/linux-kernel/lib/zstd/decompress.c
- contrib/linux-kernel/lib/zstd/entropy_common.c
- contrib/linux-kernel/lib/zstd/fse.h
- contrib/linux-kernel/lib/zstd/fse_compress.c
- contrib/linux-kernel/lib/zstd/fse_decompress.c
- contrib/linux-kernel/lib/zstd/huf.h
- contrib/linux-kernel/lib/zstd/huf_compress.c
- contrib/linux-kernel/lib/zstd/huf_decompress.c
- contrib/linux-kernel/lib/zstd/zstd_common.c
- contrib/linux-kernel/test/Makefile
- contrib/linux-kernel/test/include/linux/math64.h
- Use div_u64 for division of u64s (2/4)
- Reduce stack usage of FSE_buildCTable_wksp(), FSE_compress_wksp, and HUF_readDTableX4 (2/4)
> [linux-kernel] Update patches for v2

- appveyor.yml
- programs/zstd.1
- programs/zstd.1.md
* The appveyor tests sometimes hang, and pzstd is now deprecated in favor of zstdmt, so delete the tests.
* Update the zstd man page to reflect that strategies start from 1.
> [pzstd] Remove appveyor tests

- programs/fileio.c
`fileio.c` used to `exit()` on decoding errors, which is a problem when decoding is ordered on a bunch of files (for example `zstd -t *`).
A previous patch added the ability to continue processing the list of files in case of `zstd` decoding errors. This patch extends this capability to `gzip`, `lzma` and `lz4` formats.
> No exit() on decoding errors

- Makefile
- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstdmt_compress.c
- lib/compress/zstdmt_compress.h
- lib/decompress/zstd_decompress.c
- tests/Makefile
- tests/fullbench.c
- tests/zstreamtest.c
`ZSTD_compress_generic()` can automatically detect it is in "single pass" scenario when provided with right set of conditions. This improves performance (~+15%) as well as reduces memory requirements.
The optimization has also been ported to Multi-threading mode, where it works very well with "small" sources (a few MB). `ZSTDMT_compress()` has also been updated to perform better with "large" sources (several hundreds MB), as previous method produced too large jobs, and overall speed was limited by slowest job. The new strategy is providing a nice boost to compression speed (~+15%), and `ZSTD_compress_generic()` benefits it.
Also : created `ZSTDMT_compress_advanced()` which provides a more complete support for advanced scenarios, such as custom compression parameters and dictionary.
There …
> compress_generic() automatic optimization opportunities

- lib/compress/zstdmt_compress.c
- tests/Makefile
A single job created by ZSTDMT_compress() can be < 256KB
if data to compress is < 256 KB
(in which case it is delegated to single thread mode)
> fixed wrong assert() condition

- NEWS
- lib/common/pool.c
- lib/common/pool.h
- lib/compress/zstd_compress.c
- lib/compress/zstdmt_compress.c
- lib/compress/zstdmt_compress.h
- tests/Makefile
- tests/fuzzer.c
- tests/playTests.sh
- tests/zstreamtest.c
This patches substantially improves memory usage of `ZSTDMT_*()` API
by making sure resources are allocated "just in time" and released "as soon as possible",
typically directly from within workers.
The new test `fuzzer --memtest` make it possible to measure memory usage of different variants.
For streaming with 2 threads and compression level 1, memory usage drops from ~30 MB to ~18 MB.
More savings are possible by reducing `queueSize` in the thread pool,
so that we have less jobs, hence less buffers, prepared in advanced of workers.
The patch also fixes some issues found during investigation : 
- custom allocator is properly propagated into `ZSTDMT_CCtx*` and child `ZSTD_CCtx*`. Only the thread pool itself now directly calls `stdlib.h`.
- `ZSTDMT_compress_advanced()` (single pass …
> Memory optimisations for ZSTDMT

- lib/common/fse.h
- lib/common/huf.h
- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/decompress/zstd_decompress.c
* Fix `{FSE,HUF}_STATIC_LINKING_ONLY` for double includes
* Pull CTables and entropy related fields into a sub-structure
* Put the `ZSTD_entropyCTables_t` into `zstd_internal.h` because I will need it for block splitting
> [libzstd] Pull CTables into sub-structure

- lib/common/fse.h
- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
* Increase granularity of FSE CTable repeat mode by handling each CTable separately.
* Split `ZSTD_encodeSequences()` into its own function.
* Split up CTable type selection and CTable building into `ZSTD_selectEncodingType()` and `ZSTD_buildCTable()`.
Benchmarks:
```
$ ./zstd.dev -b1e5
Benchmarking levels from 1 to 5
1#Synthetic 50%     :  10000000 ->   3139163 (3.186), 534.7 MB/s ,1890.0 MB/s
2#Synthetic 50%     :  10000000 ->   3115138 (3.210), 370.0 MB/s ,1830.2 MB/s
3#Synthetic 50%     :  10000000 ->   3222672 (3.103), 221.2 MB/s ,1400.2 MB/s
4#Synthetic 50%     :  10000000 ->   3276678 (3.052), 194.2 MB/s ,1280.1 MB/s
5#Synthetic 50%     :  10000000 ->   3271570 (3.057), 106.8 MB/s ,1200.0 MB/s
$ ./zstd -b1e5
Benchmarking levels from 1 to 5
1#Synthetic 50%     :  10000000 -> …
```
> [libzstd] Refactor ZSTD_compressSequences()

- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_opt.h
* Move `rep` and `repToConfirm` to `seqStore_t`.
* Remove `ZSTD_CCtx*` argument from `ZSTD_compressLiterals()` and `ZSTD_compressSequences()` and pass only the sub-structures required.
* Benchmarks did not regress.
> [libzstd] Remove ZSTD_CCtx* argument of ZSTD_compressSequences()

- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_opt.h
Separate optimal parser state into it's own structure, since it doesn't really belong in `seqStore_t`.
> [libzstd] Pull optimal parser state out of seqStore_t

- lib/compress/huf_compress.c
- tests/fuzzer.c
Summary:
Huffman encoding with a bad dictionary can encode worse than the
HUF_BLOCKBOUND(srcSize), since we don't filter out incompressible
input, and even if we did, the dictionaries Huffman table could be
ill suited to compressing actual data.
The fast optimization doesn't seem to improve compression speed,
even when I hard coded fast = 1, the speed didn't improve over hard coding
it to 0.
Benchmarks:
```
$ ./zstd.dev -b1e5
Benchmarking levels from 1 to 5
1#Synthetic 50%     :  10000000 ->   3139163 (3.186), 524.8 MB/s ,1890.0 MB/s
2#Synthetic 50%     :  10000000 ->   3115138 (3.210), 372.6 MB/s ,1830.2 MB/s
3#Synthetic 50%     :  10000000 ->   3222672 (3.103), 223.3 MB/s ,1400.2 MB/s
4#Synthetic 50%     :  10000000 ->   3276678 (3.052), 198.0 MB/s ,1280.1 MB/s
5#Synthetic 50%     : …
```
> [libzstd] Fix bug in Huffman encoding

- programs/zstdcli.c
- tests/playTests.sh
It would fail in streaming mode because stdout is a console, but it is actually `/dev/null`, since it got overwritten later.
> [zstdcli] Fix -t in streaming mode

- contrib/linux-kernel/0000-cover-letter.patch
- contrib/linux-kernel/0001-lib-Add-xxhash-module.patch
- contrib/linux-kernel/0002-lib-Add-zstd-modules.patch
- contrib/linux-kernel/0003-btrfs-Add-zstd-support.patch
- contrib/linux-kernel/0004-squashfs-Add-zstd-support.patch
- contrib/linux-kernel/fs/btrfs/zstd.c
- contrib/linux-kernel/lib/zstd/huf_compress.c
- contrib/linux-kernel/lib/zstd/zstd_internal.h
- Work around gcc-7 bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81388 (2/4)
- Fix bug in dictionary compression from upstream commit cc1522351f (2/4)
- Port upstream BtrFS commits e1ddce71d6, 389a6cfc2a, and 6acafd1eff (3/4)
- Change default compression level for BtrFS to 3 (3/4)
> [linux] Update patches for v3

- contrib/adaptive-compression/Makefile
- contrib/adaptive-compression/README.md
- contrib/adaptive-compression/adapt.c
- contrib/adaptive-compression/test-correctness.sh
- contrib/adaptive-compression/test-performance.sh
- lib/compress/zstd_compress.c
- lib/zstd.h
- compression level adapts based on which thread is waiting
- 3 separate threads in charge of creating jobs, compression, and writing
> adaptive compression v1

- contrib/linux-kernel/0000-cover-letter.patch
- contrib/linux-kernel/0001-lib-Add-xxhash-module.patch
- contrib/linux-kernel/0002-lib-Add-zstd-modules.patch
- contrib/linux-kernel/0003-btrfs-Add-zstd-support.patch
- contrib/linux-kernel/0004-squashfs-Add-zstd-support.patch
- contrib/linux-kernel/0005-crypto-Add-zstd-support.patch
- contrib/linux-kernel/0006-squashfs-tools-Add-zstd-support.patch
- contrib/linux-kernel/README.md
- contrib/linux-kernel/fs/btrfs/zstd.c
- contrib/linux-kernel/fs/squashfs/zstd_wrapper.c
- contrib/linux-kernel/lib/zstd/compress.c
- contrib/linux-kernel/lib/zstd/decompress.c
- contrib/linux-kernel/lib/zstd/zstd_internal.h
v3 -> v4:
- Fix compiler warnings (2/5)
- Add missing includes (3/5)
- Fix minor linter warnings (3/5, 4/5)
- Add crypto patch (5/5)
v4 -> v5:
- Fix rare compression bug from upstream commit 308047eb5d (2/5)
- Fix bug introduced in v3 when working around the gcc-7 bug (2/5)
- Fix ZSTD_DStream initialization code in squashfs (4/5)
- Fix patch documentation for patches written by Sean Purcell (4/5)
Switching `ZSTD_wildCopy()` to just call memcpy when `length > 0` is wrong, because `ZSTD_wilcopy()` is called on overlapping inputs as long as they are at least 8 bytes apart. I've found that explicitly special casing `length <= 8` prevents the bug https://godbolt.org/g/MnvWHb.
Fixes #784
> [linux-kernel] Update patches for v4 and v5

- lib/common/compiler.h
- lib/common/fse_decompress.c
- lib/common/xxhash.c
- lib/common/zstd_internal.h
- lib/compress/fse_compress.c
- lib/compress/zstd_compress.c
- lib/compress/zstd_opt.h
- lib/decompress/huf_decompress.c
- lib/decompress/zstd_decompress.c
* Pull compiler specific macros into `compiler.h`, which will work for zstd and fse.
* Split into `FORCE_INLINE_TEMPLATE` and `HINT_INLINE`. For gcc-4.8 and gcc-4.9 removing the `always_inline` attribute from `HINT_INLINE` gave 5-10 MB/s more decompression speed. Removing it from clang reduced decompression speed by 50 MB/s.
I ran on level 1 and 2 on silesia with `-b1e2i10`. I've listed the level 1 results blow, the level 2 results are consistent.
| Compiler  | Before (MB/s) | After (MB/s) |
|-----------|---------------|--------------|
| gcc-5     |         438.6 |        438.6 |
| gcc-6     |         426.8 |        426.8 |
| gcc-7     |         438.6 |        441.6 |
| clang-3.8 |         444.7 |        444.7 |
| clang-3.9 |         429.7 |        426.8 |
| Compiler  | Before (MB/s) | …
> [libzstd] Fix FORCE_INLINE macro

- doc/zstd_compression_format.md
> fix #803 : wrong example in huffman bitstream section

- lib/dictBuilder/cover.c
- tests/playTests.sh
Divide by zero occurred when the maximum dictionary size was less than 2048.
Fixes #792.
> [cover] Fix divide by zero

- lib/dictBuilder/cover.c
* If the segment size has score `0`, or is less than `d` bytes, then we are out of content to add to the dictionary.
* Convert `score` to a `U32`, since only integer arithmetic is needed.
* When benchmarking dictionaries add dictionary size to total compressed size once.
* Turn down notifications for `ZDICT` subroutines during optimization.
Fixes #792.
> [cover] Fix end condition for small dictionary

- lib/dictBuilder/cover.c
When `ZDICT_trainFromBuffer` is called `notificationLevel` set to `0` which leads to int overflow. As a result there is some stderr-garbage on building dict with libzstd.
> Fix displayLevel overflow

- lib/common/bitstream.h
- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
When `ZSTD_adjustCParams_internal` is called with `srcSize==1`  and `dictSize==0`,  `ZSTD_highBits32` is called with a value of `0`.  With gcc, this calls `__builtin_clz` with a value of `0` which is undefined.
> Fix undefined behavior when srcSize==1

- lib/compress/zstd_compress.c
can only happen if windowLog>=27  (level 22 --ultra)
> fixed extraordinary scenario where all fields use maximum nbBits

- lib/dictBuilder/zdict.c
I'm not sure why it was 6, but shouldn't it match the default compression level in the library/CLI?
> [dictBuilder] Set default compression level to 3

- lib/Makefile
- programs/Makefile
in order to make builds reproducible
in spite of indeterministic filesystem readdir order.
See https://reproducible-builds.org/ for why this is good.
> Sort input file list

- lib/common/pool.c
Should fix the 32-bit Travis-CI failure; it is fixed for me.
> [POOL] Allow free on NULL when multithreading is disabled

- tests/fuzz/regression_driver.c
The function was renamed from `UTIL_isRegFile` to `UTIL_isRegularFile` in `programs/util.h`.
> Fix function name in tests/fuzz/regression_driver

- doc/zstd_manual.html
- lib/decompress/zstd_decompress.c
- lib/zstd.h
- tests/fuzzer.c
- tests/zstreamtest.c
- zlibWrapper/Makefile
fix #835 : 
gives ability to users of bufferless streaming API `ZSTD_decompressContinue()`
to size their own decoding buffer, using same methodology as `ZSTD_decompressStream()`,
aka a round buffer of minimal size, taking into consideration current limitations of reference decoder.
To this end, add prototype `ZSTD_decodingBufferSize_min()`,
which is now also used in `ZSTD_decompressStream()`.
> Decoding buffer size min

- programs/bench.c
- programs/util.h
- tests/fullbench.c
- zlibWrapper/examples/zwrapbench.c
for easier invocation.
- no longer expose frequency timer :
it's either useless, or stored internally in a static variable (init is only necessary once).
- UTIL_getTime() provides result by function return.
> modified util::time API (T19505791)

- doc/zstd_manual.html
- lib/dictBuilder/zdict.c
- programs/dibio.c
- programs/dibio.h
- programs/zstd.1.md
- programs/zstdcli.c
added ability to split input files for dictionary training using command `-B#`
This is a similar behaviour as benchmark module,
which can also also split input into independent blocks using `-B#`.
> Split dict

- programs/zstdcli.c
- tests/playTests.sh
Tested with:
```
./zstd --zstd=ldmhevery=7,ldmblog=3,ldmhlog=20 Makefile -c > /dev/null
```
> [zstdcli] Fix LDM advanced options parsing

- lib/compress/zstd_ldm.c
- lib/decompress/zstd_decompress.c
* Fix bad window size assert during decompression
* Fix buffer overflow in the long distance matcher when LDM min match < 8 (default is 64)
> Fix minor fuzz test failures

- lib/compress/fse_compress.c
* Normally when nbSeq == 1, we use the predefined tables, but if the ofcode > 28 we can't, so we run into this issue.
> [fse] Fix FSE_optimalTableLog() for srcSize==1

- lib/decompress/zstd_decompress.c
- tests/fuzzer.c
adding check at end of single-pass function `ZSTD_decompressFrame()`.
Check within `ZSTD_decompressContinue()` was already added in a previous patch : b3f33ccfb3b4fcc73df82126fd5ecfb751268fc6
> added control of frame content size at end of decompression

- lib/compress/fse_compress.c
* Make the U32 table in `FSE_normalizeCount()` static.
* Patch from https://lkml.kernel.org/r/20170922145946.14316-1-colin.king@canonical.com.
* Clang makes non-static tables static anyways. gcc however, does [weird things](https://godbolt.org/g/fvTcED).
* Benchmarks showed no difference in speed.
> [zstd] Backport kernel patch from @ColinIanKing

- tests/fuzz/block_round_trip.c
- tests/fuzz/simple_round_trip.c
- tests/fuzz/stream_round_trip.c
- tests/fuzz/zstd_helpers.c
- tests/fuzz/zstd_helpers.h
* Enforce smaller maximum values for parameters
* Adjust parameters to the source size
The memory usage is reduced by about 5x, which makes the fuzzers run at
least twice as fast, even more so with ASAN/MSAN enabled.
> [fuzz] Speed up round trip tests

- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_ldm.c
- lib/compress/zstd_ldm.h
- lib/decompress/zstd_decompress.c
- lib/zstd.h
- programs/fileio.c
- programs/zstd.1
- programs/zstd.1.md
- programs/zstdcli.c
- tests/playTests.sh
- tests/zstreamtest.c
* Maximum window size in 32-bit mode is 1GB, since allocations for 2GB fail
on my Mac.
* Maximum window size in 64-bit mode is 2GB, since that is the largest
power of 2 that works with the overflow prevention.
* Allow `--long=windowLog` to set the window log, along with
`--zstd=wlog=#`. These options also set the window size during
decompression, but don't override `--memory=#` if it is set.
* Present a helpful error message when the window size is too large during
decompression.
* The long range matcher defaults to a hash log 7 less than the window log,
which keeps it at 20 for window log 27.
* Keep the default long range matcher window size and the default maximum
window size at 2^27 for the API and CLI.
* Add tests that use the maximum window size and hash size for compression
and …
> Increase maximum window size

- Makefile
Fix OS-X warning on compiling `.c` files with `clang++`
Also changed test name from `gpptest` to `cpptest`, since it's no longer `g++` specific
note : I've also been considering `c++test` as the new name for this test, since it avoids potential confusion with `CPPFLAGS`, but ultimately avoided it in case `+` character could cause problem on some platform such as Windows, or any other intermediate parsing scheme. 
`cxxtest` is another potential candidate.
> Change c++ test to use CXX and CXXFLAGS environment variables

- lib/compress/zstd_opt.c
Simplify optimal parser repcode logic so that static analyzers (and people) don't think that it is possible for `opt[cur].off == ZSTD_REP_MOVE_OPT && mlen == 1` to be true and cause a buffer overflow.
> [libzstd][opt] Simplify repcode logic

- programs/fileio.c
New display more compact, more in line with `xz` output.
Before : 
```
./zstd NEWS
./zstd README.md
./zstd Makefile
./zstd --list *.zst
===========================================
Printing information about compressed files
===========================================
Number of files listed: 3
Makefile.zst (1/3):
Skippable  Non-Skippable  Compressed  Uncompressed  Ratio  Check  Filename
0              1     2.84 KB      10.33 KB  3.635  XXH64  Makefile.zst
NEWS.zst (2/3):
Skippable  Non-Skippable  Compressed  Uncompressed  Ratio  Check  Filename
0              1     6.01 KB      14.99 KB  2.496  XXH64  NEWS.zst
README.md.zst (3/3):
Skippable  Non-Skippable  Compressed  Uncompressed  Ratio  Check  Filename
0              1     3.17 KB       7.33 KB  2.309  XXH64  README.md.zst
```
After …
> improved --list display

- Makefile
- lib/common/pool.c
- lib/compress/zstd_compress.c
- lib/compress/zstdmt_compress.c
- lib/zstd.h
- tests/Makefile
- tests/fuzz/Makefile
- tests/fuzzer.c
- tests/playTests.sh
- tests/zstreamtest.c
Adjustments to tests to make them compatible with a memory-starved VM
(tested on Ubuntu Xenial VM with 768 MB RAM).
Works also for `qemu` related tests, notably ARM ones which have been quite flaky.
Longer tests are also tamed, to run faster, hence avoid triggering time-out on travisCI.
Incidentally, this patch also improves behaviour of parameter adjustment in presence of weird compression parameters, and behaviour of `zstdmt` in situation of memory allocation error.
> Leaner tests

- lib/compress/zstd_compress.c
* The window size could end up too small if the source size is 2^n + 1.
* Reproducing test case will be added to the corpus once this PR is merged.
> Don't `size -= 1` in ZSTD_adjustCParams()

- lib/compress/zstd_compress.c
- lib/zstd.h
ZSTD_compressBound() works fine, but is only useful for dynamic allocation.
For static allocation purposes, a macro is needed to provide a value at compilation time.
> added ZSTD_COMPRESSBOUND() as a macro

- lib/compress/zstd_compress.c
In `ZSTD_compressBegin_advanced()`, `ZSTD_parameters` are used to set the
compression parameters, but the level didn't get set to `CLEVEL_CUSTOM`, so
`ZSTD_compressBlock()` used the wrong parameters when checking the source
size.
> [libzstd] Set CLEVEL_CUSTOM correctly

- lib/compress/zstd_compress.c
- programs/fileio.c
It used to be disabled, likely to circumvent a bug that this patch fix 
(bad usage of the new api by `fileio.c`).
> CLI Fix : srcSize written in frame headers when compressing multiple files

- lib/common/huf.h
- lib/compress/huf_compress.c
- lib/compress/zstd_compress.c
* Ensure that the dictionary Huffman CTable has maxSymbolValue 255.
* Fix a stack buffer overflow during compression dictionary loading.
> Ensure dictionary Huff table can encode any symbol

- doc/zstd_manual.html
- lib/decompress/zstd_decompress.c
- tests/Makefile
- tests/decodecorpus.c
a compressed block must be strictly smaller than its decompressed size.
> fixed a small error in decodeCorpus

- tests/Makefile
- tests/seqgen.c
- tests/seqgen.h
- tests/zstreamtest.c
* Test for issue fixed in #889. Tested with and without the change applied. The test failed before, and passed after.
* Adds a generic sequence generator. It can generate arbitrary offsets, match lengths, and literal lengths.
> [test] Exercise all codes in dictionary tables

- lib/compress/zstd_compress.c
It isn't useful in any case to repeat default tables.
Saves a few bytes on Silesia, since we don't trigger the dictionary heuristic.
Before: 211988480 => 73651998 bytes
After:  211988480 => 73651721 bytes
> Don't allow default tables to repeat

- programs/bench.c
- programs/dibio.c
- programs/fileio.c
- programs/util.h
- tests/fullbench.c
- tests/paramgrill.c
- tests/playTests.sh
- zlibWrapper/examples/zwrapbench.c
This patch introduces an error code for `UTIL_getFileSize()`, called `UTIL_FILESIZE_UNKNOWN`.
Up to now, `UTIL_getFileSize()` would answer `0` to mean "error", making it impossible to separate from a genuine empty file.
Most users of `UTIL_getFileSize()` were hard-wired to consider `0` as "error", so this change introduces many corrections throughout the code base.
0-size files are now correctly reported (header includes the `0` content size), while non-files (pipes) continue having an unknown size.
Is this functionality worth its complexity ?
Not sure, though I like the fact that checking for a file size error is now more explicit.
> Distinguish 0-size from size-unavailable

- programs/Makefile
- programs/bench.c
- programs/fileio.c
removed the other 2 code paths (single thread, and ZSTDMT ones)
keeping only the new advanced API, for easier code coverage.
It shall also fix identified issue with Visual Studio
which doesn't have ZSTD_NEWAPI defined.
> fileio and bench : ZSTD_NEWAPI as the only code path

- index.html
@martint seems to have use the Presto Zstandard code as part of airlift.
Given airlift aircompressor is on Maven Central it makes more sense to use it as the reference of his implementation of Zstd in pure Java.
> Update link to Java decoder from Presto to Airlift

- lib/compress/zstd_compress.c
- tests/fuzzer.c
ZSTD_compress() and friends would treat an empty input as an unknown size
when selecting parameters. Thus, they would drastically overallocate the
context. Tell ZSTD_getParams() that the source size is 1 when it is empty.
> [libzstd] Fix parameter selection for empty input

- lib/decompress/zstd_decompress.c
- tests/fuzzer.c
- tests/zstreamtest.c
Previously we were only able to decode skippable frames that are smaller than `zds->inBuffSize`.
Fixes #904.
> Allow skippable frames of any size

- lib/compress/zstd_compress.c
- programs/bench.c
as per documentation, on `ZSTD_setPledgedSrcSize()` :
> If all data is provided and consumed in a single round,
> this value (pledgedSrcSize) is overriden by srcSize instead.
This wasn't applied before compression level is transformed into compression parameters.
As a consequence, small input missed compression parameters adaptation.
It works fine now : compression was compared with `ZSTD_compress_advanced()`,
results were the same.
> fix : ZSTD_compress_generic(,,,ZSTD_e_end) automatically sets pledgedSrcSize

- build/cmake/lib/CMakeLists.txt
- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress.h
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_double_fast.c
- lib/compress/zstd_double_fast.h
- lib/compress/zstd_fast.c
- lib/compress/zstd_fast.h
- lib/compress/zstd_lazy.c
- lib/compress/zstd_lazy.h
- lib/compress/zstd_ldm.h
- lib/compress/zstd_opt.c
- lib/compress/zstd_opt.h
- lib/compress/zstdmt_compress.c
This patch doesn't change functionality nor performance.
Its objective is mostly to rewrite the optimal parser in a way which makes it easier to understand and modify. "Aggressive scoping" is the most relevant rule applied in this patch.
On the noticeable changes : 
- `zstd_compress.h` becomes `zstd_compress_internal.h`, to emphasise that its definitions are strictly internal, meant to be used solely by `/lib/compress` modules.
- Many definitions were moved from `zstd_internal.h` into `zstd_compress_internal.h`. `zstd_internal.h` is reserved for definitions that need to be shared across `/lib` sub-directories, namely `/compress`, `/decompress` and `/dictBuilder`.
The next important change will be the modification of `zstd_opt`'s match finder to transparently manage rep codes, so that it's …
> Optimal parser refactoring

- Makefile
- lib/common/mem.h
- lib/common/zstd_common.c
- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_lazy.c
- lib/compress/zstd_opt.c
- lib/compress/zstdmt_compress.c
- lib/compress/zstdmt_compress.h
- lib/zstd.h
- programs/bench.c
- tests/zstreamtest.c
There is now a single optimal parser for both normal and _extDict modes.
The enabler was to isolate _extDict specificities into the match finder.
The new parser code is highly simplified compared to earlier versions.
This should help reviews, and future modifications.
This new version does not compress identically compared with `dev` nor `v1.3.1`,
but it's within the same range. Speed is about the same. Compression ratio is similar, though exact compressed size vary.
```
calgary.tar : -b19 :  903756 (v1.3.1) ==>  903635 (patch)
enwik7      : -b19 : 2830032 (v1.3.1) ==> 2830756 (patch)
```
The difference is likely because search used to stop immediately after repcode when finding `sufficient_len`, while it will continue searching now. Searching more is supposed to be better, or so I …
> Optimal parser part 2 : Merge normal and _extDict parsers

- Makefile
- circle.yml
- programs/bench.c
- programs/bench.h
- programs/util.h
- programs/zstdcli.c
Added (hidden) cli command `-S` to benchmark multiple files separately
Currently, when multiple files are provided on command line for benchmark,
all files are joined by default,
which means they are compressed separately but benchmarked together,
providing a single final result.
Benchmarking files separately makes it possible to accurately measure differences for each individual file. This is expected to be useful while tuning optimal parser.
> Bench multiple files

- doc/zstd_manual.html
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_lazy.c
- lib/compress/zstd_opt.c
- tests/paramgrill.c
`zstd_opt.c` now supports 3 variants, through `optLevel` parameter.
- btultra -> (2)
- old btopt -> (1)
- new btopt -> (0)
btopt(0) is about +15% faster compared to btopt(1), at the cost of -0.02 ratio. This is merely an "average" : variance can be large depending on file content. Direction though is always the same.
I initially considered exposing the 3 different variants, by my feeling is that the performance gap between (0) and (1) is too small to deserve creating a new strategy. So this patch makes `btopt` adopt the faster setting.
> faster btopt variant

- programs/fileio.c
- tests/Makefile
Fixes issue where, when `zstd --format=lz4` is fed an input larger than 128KB,
the read overruns the input buffer.
> Fix LZ4 Compression Bug

- lib/common/zstd_internal.h
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_opt.c
- programs/bench.c
There was a flaw in the formula
which compared literal cost with match cost at a given position :
a non-null literal suite is going to be part of next sequence,
while if position ends a previous match, to immediately start another match,
next sequence will have a litlength of zero.
A litlength of zero has a non-null cost.
It follows that literals cost should be compared to match cost + litlength==0.
Not doing so gave a structural advantage to matches, which would be selected more often.
I believe that's what led to the creation of the strange `factor` heuristic which adds a fixed (but complex to calculate) cost to each match.
The heuristic was actually compensating.
It was probably created through multiple trials, settling for best outcome on a given scenario (I suspect `silesia.tar`), …
>  zstd_opt: changed cost formula

- Makefile
- circle.yml
- programs/zstdcli.c
This patch reduces CircleCI tests duration from ~30mn to around ~6mn.
Main drivers are : 
- Compilation tests run without optimization (`-O0`)
- Big packages no longer installer (gcc5-6-7, clang, i386), as they were introducing major delays
- Associated tests removed (gcc5-6-7, clang, -m32)
- `cmake` test removed due to a bug in `pthread` detection
- on the "plus" side : all compilation tests are now run with `-Werror`, ensuring a clear signal, so that no warning remain unnoticed (one such warning has been caught and fixed in this patch).
There are less tests, but most important results we are looking for (mostly compilation results under various platforms) remain active.
Missing tests are still run on TravisCI, on `dev` branch, which has a more complete setup (including fuzzer and …
> Faster CircleCI tests

- lib/compress/zstd_compress.c
- lib/compress/zstdmt_compress.c
- programs/fileio.c
- tests/zstreamtest.c
`zstreamtest --newapi` tends to fail on qemu-arm and qemu-ppc targets (32-bits).
I suspect that's because some of these tests require too much resource.
A complementary directive `--no-big-tests`, is supposed to avoid that.
However, the test still fails from time to time on travis CI.
Unfortunately, I've been unable to reproduce it, so I'm left speculating.
Considering the issue might be a too large resource requirement, I tried to find which case could trigger such requirement, and found that `ZSTD_p_enableLongDistanceMatching` could be enabled, and even associated with multithreading ! Combined with an undisclosed input length, it leads to the creation of several 256 MB buffers. That sounds like a possible reason.
This patch just turns off `ZSTD_p_enableLongDistanceMatching` tests when …
> Reduce memory stress for qemu tests

- programs/util.h
The new macro might be a bit too restrictive.
Impact is limited though : systems which do not support the new test will simply default to `<time.h>`'s `clock_t clock()`, suffering lesser benchmark accuracy.
Should it matter, the detection macro can be upgraded later.
>  fix #911 : changed detection macro for `clock_gettime()`

- contrib/long_distance_matching/ldm.c
- lib/common/bitstream.h
- lib/compress/zstd_compress_internal.h
- lib/dictBuilder/zdict.c
- lib/legacy/zstd_v01.c
- lib/legacy/zstd_v02.c
- lib/legacy/zstd_v03.c
- lib/legacy/zstd_v04.c
- lib/legacy/zstd_v05.c
- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
no longer supported starting C++17
Fixes #937
> remove `register` keyword

- programs/fileio.c
Test command:
```
head -c 10000 /dev/zero | ./zstd -c --zstd=wlog=12 | ./zstd -M2048 -t
```
> [fileio] Fix window size MB calculation

- lib/compress/zstd_compress.c
- tests/fuzzer.c
The compressor wasn't using the repcodes from the cdict. If the repcodes aren't the default, which is never the case right now, and the repcode is used, the data will be corrupt.
> Fix cdict compressor repcodes

- programs/fileio.c
- tests/playTests.sh
We avoid removing `/dev/null`, but don't handle other non-regular files like `/dev/stdout` or `/DEV/null`.
* Switch the overwrite code to not try to remove non-regular files.
* `FIO_remove()` also refuses to remove non-regular files.
> [fileio] Refuse to remove non-regular file

- lib/compress/zstd_compress.c
- programs/fileio.c
This patch restores capability for each frame to receive adapted compression parameters depending on its size.
There was a bug breaking this feature :
setting a parameter with value `0` is supposed to be a no-op, a feature which is used in `fileio`.
Unfortunately, it would pin down compression parameters as if they were manually set,
preventing later automatic adaptation.
Unfortunately, I'm short of a test case to detect this situation and trigger an error if it happens.
Compression parameters selection (starting with tableID {0,1,2,3}) is largely internal,
leaving no trace to outside world, not even in frame header.
> fix adaptation on srcSize

- lib/compress/zstd_compress.c
- tests/playTests.sh
zstd streaming API was adding a null-block at end of frame for small input.
Reason is : on small input, a single block is enough.
ZSTD_CStream would size its input buffer to expect a single block of this size,
automatically triggering a flush on reaching this size.
Unfortunately, that last byte was generally received before the "end" directive (at least in `fileio`).
The later "end" directive would force the creation of a 3-bytes last block to indicate end of frame.
The solution is to not flush automatically, which is btw the expected behavior.
It happens in this case because blocksize is defined with exactly the same size as input.
Just adding one-byte is enough to stop triggering the automatic flush.
I initially looked at another solution, solving the problem directly in the compression …
> saves 3-bytes on small input with streaming API

- lib/compress/zstd_compress.c
taking advantage of improved `btopt` speed to tune parameters.
The most important change is level 16, updated from `btlazy2` to `btopt`, resulting in stronger and faster compression while using less memory, so a net win.
The other `btopt` levels (17-19) are mostly reinforced to provide better compression ratio.
15 is made a little bit faster, and 20 a little bit stronger, to increase the difference with neighbouring  `btopt`.
In theory, I should also update small-size tables,
but I got lazy on that one ...
> update levels 15-20

- lib/compress/zstd_compress.c
- lib/compress/zstdmt_compress.c
- lib/compress/zstdmt_compress.h
`zstreamtest --newapi` (and `--opaqueapi`) creates and destroys way too many threads
resulting in failure of tsan tests.
This issue is potentially connected to the `qemu` flaky tests on travis CI.
This is because, in `--newapi` mode, the nb of threads can be changed at each test.
The `--no-big-tests` directive reduces this choice to 1/2 threads,
in order to limit memory usage, especially for qemu and 32-bits builds.
Unfortunately, swapping between 1 and 2 threads is enough to constantly create/destroy new mtctx.
This patch takes advantage of the following property :
via compress_generic, no internal mtctx is needed for nbThreads < 2.
As a consequence, when nbThreads == 2, the currently active mtctx is fine, and can be re-used.
The strategy is generalized through control of current …
> zstdmt via compress_generic: reduce opportunity to free/create mtctx

- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstdmt_compress.c
- tests/fuzzer.c
- tests/zstreamtest.c
Long fuzzer tests caught a subtle bug that was probably there for some time.
The impact of the bug is not a crash, or any other clear error signal,
rather, it reduces performance, by cutting data into smaller blocks.
Eventually, the following test would fail because it produces too many 1-byte blocks,
requiring more space than buffer can provide :
`./zstreamtest_asan --mt -s3514 -t1678312 -i1678314`
The root scenario is as follows :
- Create context, initialize it using explicit parameters or a `cdict` to pin them down, set `pledgedSrcSize=1`
- The compression parameters will not be adapted, but `windowSize` and `blockSize` will be automatically set to `1`.
`windowSize` and `blockSize` are dynamic values, set within `ZSTD_resetCCtx_internal()`.
The automatic adaptation makes it possible …
> fix a subtle issue in continue mode 

- contrib/meson/meson.build
fix use of absolute paths which are deprecated to build failure in meson, also missing some sources
that got split
also move source files each to their own line so future diffs are clearer.
> meson: fix build

- doc/zstd_compression_format.md
I think you meant 8 MiB or smaller, instead of an unbounded (and illogical) range
> fix unbounded range

- programs/fileio.c
This fixes the following crash:
$ touch exists
$ programs/zstd -r examples/ -o exists
zstd: exists already exists; not overwritten
Segmentation fault (core dumped)
* programs/fileio.c (FIO_compressMultipleFilenames):
Handle the case where we're not overwriting the destination.
Reported at https://bugzilla.redhat.com/1530049
> zstd: fix crash when not overwriting existing files

- programs/bench.c
- programs/zstdcli.c
was previously ignored during bench initialization
> fix: bench can accept hlog custom parameter

- programs/fileio.c
- programs/util.h
* Refuse to set file stat on non-regular file
* Use `FIO_remove()` everywhere to ensure we don't ever remove non-regular files.
* Don't call `FIO_remove()` during compression on `stdout` or `/dev/null` to quiet the message.
> [fileio] Improve safety of output file modifications

- lib/compress/zstd_compress.c
- lib/zstd.h
This patch doesn't change the code,
its only purpose is to update `zstd.h` API documentation
by regrouping all functions related to memory management together.
This section of the API now lists, in order :
- `ZSTD_sizeof_*()` 
- `ZSTD_estimate*Size*()`
- `ZSTD_initStatic*()`, which needs `ZSTD_estimate*Size*()` to correctly set size of buffers
- `ZSTD_create*_advanced()`, because related to `ZSTD_customMem`
This order feels like a natural progression in complexity.
> Update API documentation related to memory management capabilities

- tests/fuzzer.c
The bug prevents noise being added
> Fix break condition in decompression noise test

- lib/common/huf.h
- lib/compress/huf_compress.c
- lib/compress/zstd_compress.c
- lib/dictBuilder/cover.c
- lib/dictBuilder/zdict.c
- lib/dictBuilder/zdict.h
- tests/fuzzer.c
This patch fixes situations where samples provided to the dictionary builder
are either not compressible, or too regular,
resulting in an error in the literals statistics module.
The pathological situation is now detected, and literals statistics are swapped for fake ones, which can be written into the dictionary header.
The impact of the "fake" huffman table on compression ratio is minimal, if any.
> Fix for #304 and #977 : error during dictionary creation 

- lib/compress/zstd_compress.c
- tests/fuzzer.c
During compression with a CDict, when the source size is known, we want to increase the window log to fit the dictionary and the source. However, since we don't know the compression level at this point, we need to limit how large we make the window size. Since dictionary compression is meant for small sources, we can prefer a smaller limit. The limit I used is 19, which is the window log of compression level 1 with the largest source size.
Fixes #975.
> Increase windowLog from CDict based on the srcSize when known

- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_double_fast.c
- lib/compress/zstd_double_fast.h
- lib/compress/zstd_fast.c
- lib/compress/zstd_fast.h
- lib/compress/zstd_lazy.c
- lib/compress/zstd_lazy.h
- lib/compress/zstd_ldm.c
- lib/compress/zstd_ldm.h
- lib/compress/zstd_opt.c
- lib/compress/zstd_opt.h
* Split out `ZSTD_matchState_t`.
* Move repcodes to `ZSTD_blockState_t` together with `ZSTD_entropyCTables_t`. Now there are two `ZSTD_blockState_t` objects, `prev` and `next`. When the block is confirmed we swap `prev` and `next`.
* Pass the match finders and dictionary builders only the pieces of the context that they need.
Notes to review the patch:
* The changes to the match finders are mechanical, and I don't expect issues (though still take a look!). The biggest change is that it reads/writes to the parameter `rep` instead of reading from `rep` and writing to `repToConfirm`.
* The biggest change is switching to `ZSTD_blockState_t`, and making the confirmation a pointer swap. This gives us the ability to always have valid entropy tables, instead of losing history when we reach an …
> Split ZSTD_CCtx into smaller sub-structures

- lib/compress/zstd_compress.c
Shaves 492,076 B off of the `ZSTD_CDict`.
The size of a `ZSTD_CDict` created from a 112,640 B dictionary is:
| Level | Before (B) | After (B) |
|-------|------------|-----------|
| 1     | 648,448    | 156,412   |
| 3     | 1,140,008  | 647,932   |
> Reduce size of ZSTD_CDict

- lib/compress/zstd_compress.c
When the dictionary is <= 8 bytes, no data is loaded from the dictionary.
In this case the repcodes weren't set, because they were inserted after the
size check. Fix this problem in general by first setting the cdict state to
a clean state of an empty dictionary, then filling the state from there.
> Set repcodes for empty ZSTD_CDict

- doc/zstd_manual.html
- lib/compress/zstd_compress.c
- lib/decompress/zstd_decompress.c
- lib/zstd.h
- tests/fuzzer.c
`ZSTD_create?Dict()` is required to produce a `?Dict*` return type
because `free()` does not accept a `const type*` argument.
If it wasn't for this restriction, I would have preferred to create a `const ?Dict*` object
to emphasize the fact that, once created, a dictionary never changes
(hence can be shared concurrently until the end of its lifetime).
There is no such limitation with `initStatic?Dict()` :
as stated in the doc, there is no corresponding `free()` function,
because `workspace` is provided, hence allocated, externally,
it can only be `free()` externally.
As a consequence, `ZSTD_initStatic?Dict()` can return a `const ZSTD_?Dict*` pointer.
This is proposed in this patch.
Tested with `make all`, to catch and fix `initStatic`'s users,
which, incidentally, also updated `zstd.h` …
> changed initStatic?Dict() return type to const ZSTD_?Dict*

- doc/zstd_manual.html
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstdmt_compress.c
- lib/compress/zstdmt_compress.h
- lib/zstd.h
- programs/fileio.c
`ZSTD_getFrameProgression()` produces 3 statistics for ongoing frame compression :
- `ingested`
- `consumed` (effectively compressed)
- `produced`
`ingested` can be larger than `consumed` due to buffering effect.
For the time being, this patch mostly fixes display of % ratio,
since it computes `consumed / produced`,
instead of `ingested / produced`.
That being said, update is not yet "smooth",
because `fileio` spends most of its time stuck waiting for a worker to complete its job
(due to the rule of guaranteed forward progress).
This could be improved thanks to more granular flushing
i.e. start flushing before ongoing job is fully completed.
> Progressive mt

- Makefile
- programs/README.md
- programs/zstdcli.c
- tests/.gitignore
- tests/playTests.sh
added some test, also updated relevant doc
+ fixed a mistake in `lz4` symlink support :
`lz4` utility doesn't remove source files by default (like `zstd`, but unlike `gzip`).
The symlink must behave the same.
> add `zcat` symlink support, suggested by @wtarreau

- doc/zstd_manual.html
- lib/common/pool.c
- lib/common/pool.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstdmt_compress.c
- lib/compress/zstdmt_compress.h
- lib/zstd.h
- programs/fileio.c
- tests/zstreamtest.c
This patch was more difficult than anticipated to get correct.
I'm thankful we have fuzzer tools which are unforgiving and produce crazy combinations to test.
Nonetheless, please review this patch carefully.
In the end, the only visible feature this patch enables is to receive regular feedback on the compression process, ensuring smooth display on console during compression with large window sizes.
Try it on some large file with `zstd --long`, the difference with current `dev` branch will be obvious.
It also flushes jobs immediately, before it ends, which also improves latency when window is large, hence when job is large, though it requires a rate-limited I/O to see its impacts (by default, files are cached by OS, so flush speed is too fast to notice a difference).
If it was the only …
> Progressive flush

- lib/compress/zstd_compress.c
- lib/compress/zstd_opt.c
- tests/fuzzer.c
- tests/zstreamtest.c
Fixes #1004. The window log can't shrink so far as to shrink the `hashLog3`, but we can allow it to grow, and increase `hashLog3`.
> Fix hashLog3 size when copying cdict tables

- lib/compress/zstd_compress.c
- tests/zstreamtest.c
We can detect incorrect source size earlier if `consumedSrcSize > pledgedSrcSize`.
> Test for incorrect pledgeSrcSize earlier

- lib/common/fse_decompress.c
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_lazy.c
- lib/decompress/zstd_decompress.c
faster decoding in 32-bits mode for long offsets
On my laptop:
Before:
```
./zstd32 -b --zstd=wlog=27 silesia.tar enwik8 -S
3#silesia.tar       : 211984896 ->  66683478 (3.179),  97.6 MB/s , 400.7 MB/s
3#enwik8            : 100000000 ->  35643153 (2.806),  76.5 MB/s , 303.2 MB/s
```
After:
```
./zstd32 -b --zstd=wlog=27 silesia.tar enwik8 -S
3#silesia.tar       : 211984896 ->  66683478 (3.179),  97.4 MB/s , 435.0 MB/s
3#enwik8            : 100000000 ->  35643153 (2.806),  76.2 MB/s , 338.1 MB/s
```
Mileage vary, depending on file, and cpu type.
A generic rule of thumb : x86 benefits less from "long-offset mode" than x64, maybe due to register pressure.
On "entropy", long-mode is _never_ a win for x86.
On my laptop, it may, depending on file and compression level
(`enwik8` typically …
> Disable Long Offset mode in 32-bits

- doc/zstd_manual.html
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_double_fast.c
- lib/compress/zstd_fast.c
- lib/compress/zstd_lazy.c
- lib/compress/zstdmt_compress.c
- lib/compress/zstdmt_compress.h
- lib/zstd.h
- programs/bench.c
- programs/bench.h
- programs/fileio.c
- programs/fileio.h
- programs/zstd.1.md
- programs/zstdcli.c
- tests/fullbench.c
- tests/fuzzer.c
- tests/playTests.sh
- tests/roundTripCrash.c
- tests/zstreamtest.c
This patch makes it possible to change compression parameters *during* compression.
Only compression level and compression parameters (except `windowLog`) can be updated mid-course.
Any other parameter will trigger an error.
How it works : just invoke `ZSTD_CCtx_setParameter()` as usual. If the updated parameter belongs to the authorised list, it will be pushed to zstdmt at next invocation of `ZSTD_compress_generic()`, and then applied on next job.
Note that there is some latency while waiting for next job, especially at slower compression level.
Note also that this capability has no impact on single-threaded compression : compression parameters remain the same up to the end (`ZSTD_e_end`) of current frame.
On CLI, the compression level is now displayed at the beginning of the status …
> Updatable compression parameters

- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/decompress/zstd_decompress.c
- tests/fuzzer.c
A little patch written under pain killer medicine. Hopefully, not too insane.
This one offers a generic +5-10% decoding speed improvement to most sources I benchmarked under `gcc`.
The cost is that fse decoding tables are now twice larger, inflating from 5kb to 10kb.
I believe it's a reasonable trade-off.
All related fse decoding function had to be rewritten to adopt the new data structure.
They are included directly within `zstd_decompress.c`.
A few numbers from "entropy" : 
before : 
```
./zstd -b silesia.tar enwik8 calgary.tar -S
3#silesia.tar       : 211948032 ->  66994707 (3.164), 262.3 MB/s ,1029.8 MB/s
3#enwik8            : 100000000 ->  35687378 (2.802), 192.6 MB/s , 832.2 MB/s
3#calgary.tar       :   3265536 ->   1065161 (3.066), 214.4 MB/s , 921.7 MB/s
```
after :
```
./zstd -b …
```
> Faster decoding speed

- lib/BUCK
- lib/common/compiler.h
- lib/common/cpu.h
- lib/common/huf.h
- lib/decompress/huf_decompress.c
- lib/decompress/huf_decompress_impl.h
- lib/decompress/zstd_decompress.c
- lib/decompress/zstd_decompress_impl.h
Initial support for BMI2 in the decompression code. Initial benchmarks show this gets all or nearly all the benefits from `-mbmi2`, more details to come later. This patch is to show what the implementation looks like.
It seems clang only benefits from the HUF BMI2, and gcc benefits from HUF and FSE.
Comparing zstd decompression on Silesia before, with `-mbmi2`, and after on levels 1 and 2 with different compilers.
```
zstd.before.apple
Benchmarking levels from 1 to 2
1#silesia.tar       : 211988480 ->  73651689 (2.878), 295.0 MB/s , 678.0 MB/s
2#silesia.tar       : 211988480 ->  70158789 (3.022), 225.7 MB/s , 623.6 MB/s
zstd.after.apple
Benchmarking levels from 1 to 2
1#silesia.tar       : 211988480 ->  73651689 (2.878), 295.9 MB/s , 716.7 MB/s
2#silesia.tar       : 211988480 ->  70158789 …
```
> [decompress] Support BMI2

- lib/common/huf.h
- lib/compress/huf_compress.c
- lib/compress/huf_compress_impl.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_impl.h
- lib/compress/zstd_compress_internal.h
- lib/decompress/zstd_decompress.c
Compile the `ZSTD_encodeSequences()` and the two Huffman compression functions with and without BMI2 and select the version at runtime.
These measurements are pretty noisy, the devserver measurements are much better.
```
zstd.before.apple
Benchmarking levels from 1 to 2
1#silesia.tar       : 211988480 ->  73651689 (2.878), 272.9 MB/s , 637.5 MB/s
2#silesia.tar       : 211988480 ->  70158789 (3.022), 206.5 MB/s , 583.8 MB/s
zstd.after.apple
Benchmarking levels from 1 to 2
1#silesia.tar       : 211988480 ->  73651689 (2.878), 317.5 MB/s , 696.3 MB/s
2#silesia.tar       : 211988480 ->  70158789 (3.022), 235.4 MB/s , 662.5 MB/s
zstd.mbmi2.apple
Benchmarking levels from 1 to 2
1#silesia.tar       : 211988480 ->  73651689 (2.878), 302.1 MB/s , 661.3 MB/s
2#silesia.tar       : 211988480 -> …
```
> [compress] Support BMI2

- programs/bench.c
- programs/util.h
by invoking `time()` once per batch, instead of once per compression / decompression.
Batch is dynamically resized so that each round lasts approximately 1 second.
Also : time accuracy upgraded to nanosecond
> improve benchmark measurement for small inputs

- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_ldm.c
- lib/compress/zstd_ldm.h
* `ZSTD_ldm_generateSequences()` generates the LDM sequences and
stores them in a table. It should work with any chunk size, but
is currently only called one block at a time.
* `ZSTD_ldm_blockCompress()` emits the pre-defined sequences, and
instead of encoding the literals directly, it passes them to a
secondary block compressor. The code to handle chunk sizes greater
than the block size is currently commented out, since it is unused.
The next PR will uncomment exercise this code.
* During optimal parsing, ensure LDM `minMatchLength` is at least
`targetLength`. Also don't emit repcode matches in the LDM block
compressor. Enabling the LDM with the optimal parser now actually improves
the compression ratio.
* The compression ratio is about 0.01% worse than before, because I removed the …
> Split block compresser out of long range matcher

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_ldm.c
- lib/compress/zstd_ldm.h
* Give the LDM its own `windowLog` parameter, which can't yet be set to anything other than the `ZSTD_CCtx`'s window log.
* Give the LDM its own round buffer management, separate from the `ZSTD_CCtx`'s.
> LDM manages its own window round buffer

- lib/common/compiler.h
- lib/decompress/huf_decompress.c
`gcc v4.8` failed inlining these small functions,
resulting in major performance impact, especially for `bmi2`.
ex :
```
zstd -b1 silesia.tar
before : dec 680 MB/s
after  : dec 710 MB/s  (without bmi2)
after  : dec 770 MB/s  (with DYNAMIC_BMI2)
```
Also : 
limit `DYNAMIC_BMI2` to `gcc` >= 4.8
> force_inline HUF_decodeSymbol*()

- programs/fileio.c
Silence a Coverity warning about 'windowSize' being uninitialized.
(Yes, nothing that calls this routine actually uses the windowSize
value.  Still, appeasing Coverity is pretty harmless in this case.)
> FIO_addFInfo: Fully initialize output 'total' struct

- lib/common/compiler.h
`clang` only claims compatibility with `gcc` 4.2,
which is a problem for `DYNAMIC_BMI2`,
which is only enabled when `gcc` >= 4.8.
Add `__clang__` macro detection
to enable `DYNAMIC_BMI2` in this case.
> Enable DYNAMIC_BMI2 for clang

- programs/bench.c
- programs/zstdcli.c
zstd bench module can focus on decompression speed _only_.
This is useful when trying to measure decompression speed
on some large input data compressed using a high level,
as compression time becomes problematic (too long).
This mode is triggered by command : `zstd -b -d`
Problem was : in such a mode,
measured decoding speed was > 10% slower
than in nominal mode (compression + decompression).
The reason for such difference wasn't clear, and still isn't.
Nonetheless, this patch fixes the issue.
Moving the `memcpy()` operation sooner in the pipeline fixed it.
I can still measure small differences, but they are in the < 2% range,
so it's much more tolerable.
also : it doesn't matter anymore in which order are selected
commands `-b` and `-d`.
This combination always triggers bench_decodeOnly …
> fix benchmark issue when measuring decoding speed only

- lib/common/threading.h
Silences some warnings that showed up in my future patches.
> [threading] Cast unused arguments to void

- README.md
- build/VS_scripts/build.VS2017Community.cmd
- build/VS_scripts/build.VS2017Enterprise.cmd
- build/VS_scripts/build.VS2017Professional.cmd
- build/VS_scripts/build.generic.cmd
These scripts allow building through Visual Studio 2017 and separate VS installations for Community, Professional, and Enterprise
> Visual Studio 2017 build scripts

- lib/common/bitstream.h
- programs/platform.h
Currently there's a couple of UTF-8 characters in two header files, an en-dash & a non-breaking space. I guess they come out of copy-paste from elsewhere since I didn't see a reason for them otherwise. Without a UTF-8 BOM if the system codepage doesn't include the character this can lead to compile warnings in visual studio at least. I think this change is preferable to adding a BOM and potential headaches from that.
If this change isn't desired then feel free to reject the PR, though I'd like to fix the issue another way if possible.
> Remove non-ASCII characters in header file comments

- doc/zstd_manual.html
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_fast.c
- lib/compress/zstdmt_compress.c
- lib/zstd.h
- programs/bench.c
- programs/fileio.c
- programs/zstd.1.md
- programs/zstdcli.c
- tests/fuzzer.c
- tests/playTests.sh
This patch introduces faster compression levels, using negative values.
On the command line, they can be triggered using `--fast[=#]` command.
Negative compression levels use a new baseline level, stored at row `0`,
adding a `skip distance` between samples (simple rule : compression level `-3`, skip distance `3`), 
stored in field `ZSTD_p_targetLength`
Negative compression levels also disable Huffman compression of literals, translating into faster decoding speed.
It's possible to create one's own custom fast compression level
by using strategy `ZSTD_fast`, increasing `ZSTD_p_targetLength` to desired value,
and turning on or off literals compression, using `ZSTD_p_compressLiterals`.
Performance is generally on par or better than typical high speed algorithms such as `snappy` or `quicklz`. …
> Negative compression levels

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_ldm.c
- tests/fuzzer.c
The overflow protection is broken when the window log is `> (3U << 29)`, so 31.
It doesn't work when `current` isn't around `1U << windowLog` ahead of `lowLimit`,
and the the assertion `current > newCurrent` fails. This happens when the same
context is used many times over, but with a large window log, like in zstdmt.
Fix it by triggering correction based on `nextSrc - base` instead of `lowLimit`.
The added test fails before the patch, and passes after.
> Fix overflow protection with wlog=31

- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_ldm.c
- lib/compress/zstd_ldm.h
* Expose the reference external sequences API for zstdmt.
Allows external sequences of any length, which get split when necessary.
* Reset the LDM window when the context is reset.
* Store the maximum number of LDM sequences.
* Sequence generation now returns the number of last literals.
* Fix sequence generation to not throw out the last literals when blocks of
more than 1 MB are encountered.
> Expose reference external sequence API

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_ldm.c
Setting `loadedDictEnd` was accidently removed from `ZSTD_loadDictionaryContent()`,
which means that dictionary compression will only be able to reference the parts of
the dictionary within the window. The spec allows us to reference the entire
dictionary so long as even one byte is in the window.
`ZSTD_enforceMaxDist()` incorrectly always allowed offsets up to `loadedDictEnd`
beyond the window, even once the dictionary was out of range.
When overflow protection kicked in, the check `current > loadedDictEnd + maxDist`
is incorrect if `loadedDictEnd` isn't reset back to zero. `current` could be reset
below the value, which would incorrectly allow references beyond the window. This
bug is present in `master`, but is very hard to trigger, since it requires both
dictionaries and data which …
> Restore setting loadedDictEnd

- snap/snapcraft.yaml
This package will let you publish the latest zstd in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and Linux distributions. You just have to go to https://build.snapcraft.io and enable the automated continuous delivery.
> Add the packaging metadata to build the zstd snap

- index.html
This PR adds a link to the [FFI based ruby bindings for zstd](https://github.com/msievers/zstandard-ruby). The differences to the already mentioned ruby bindings provided by SpringMT are
* the FFI bindings do not ship with a zstd implementation, but use the version which is installed on the system
* tested to work with zstd 0.6.0 - 1.3.3
* work with both major Ruby implementations MRI (CRuby) and JRuby (Java)
> Add reference to Ruby FFI bindings

- doc/zstd_manual.html
- lib/compress/zstd_compress.c
- lib/zstd.h
to respect naming convention :
`ZSTD_CCtxParams_*()`
> updated CCtxParams API

- lib/compress/zstd_compress.c
- lib/compress/zstd_ldm.c
- lib/compress/zstd_ldm.h
- lib/compress/zstdmt_compress.c
Integrate ldm into zstdmt by running it in serial and in order in the first
step of each job, in the same place as the hash gets updated. The input
buffer is sized to fit the whole LDM window and 2 full buffers of slack.
Input buffers cannot be reused until the LDM step is done with them.
After the LDM step is finished, the jobs don't actually have access to the
full window, only the overlap.
Tested on a few different multi-GB files with and without sanitizers,
and with different numbers of threads.
> Integrate ldm with zstdmt

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_ldm.c
- lib/compress/zstd_ldm.h
- lib/compress/zstdmt_compress.c
- lib/compress/zstdmt_compress.h
- lib/zstd.h
- tests/fuzzer.c
This patch moves the LRM parameters from "experimental" section to the "supported" section of `ZSTD_cParameter`.
It also makes it possible to provide LRM parameters in any order. So `windowLog` can be specified before `enableLongDistanceMatching` for example, and still remain valid.
This capability is also extended to all compression parameters. It's now possible to specify `windowLog` or `hashLog` before `compressionLevel` (which used to reset all `cParams` members).
In order to introduce this feature, it was necessary to change the meaning of value `0` for most impacted parameters : previously, `0` meant "don't change the parameter". Now, it means "this parameter uses default settings". This is required because now parameters survive sessions and are not reset when setting compression …
> LRM parameters

- doc/zstd_manual.html
- lib/compress/zstd_compress.c
- lib/zstd.h
- programs/zstdcli.c
- tests/fuzz/zstd_helpers.c
- tests/paramgrill.c
- tests/playTests.sh
this makes it possible to specify extremely large negative compression levels,
achieving practically the same effect as "no compression" (when `-level` > `blockSize`).
It also becomes possible to define larger `targetLength` values for ultra compression mode
(note: in this case, it is automatically clamped to `ZSTD_OPT_NUM`).
> removed limit ZSTD_TARGETLENGTH_MAX

- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
Fixed build error while compiling with slightly older GCCs, such as gcc-4.2.x on my am386dx40 by guarding the builtin_* as in other files.
> fixed legacy/zstd_v* with older gcc version, by guarding builtin_*

- build/VS_scripts/build.VS2017.cmd
- build/VS_scripts/build.generic.cmd
This new build script automatically selects the installed Visual Studio 2017 implementation to use in order of Enterprise, Professional, and Community. This should be easier for people to reference without needing to specify which specific version of Visual Studio to use.
If a specific version is required, I have left the `build.VS2017Community` `build.VS2017Enterprise` and `build.VS2017Professional` build scripts so they can still be referenced.
There are now four `msbuild_version` options for 2017 `VS2017Community` `VS2017Professional` `VS2017Enterprise` and `VS2017` which automatically chooses the version to use.
> Generic Visual Studio 2017 build script

- build/cmake/programs/CMakeLists.txt
`MAN_INSTALL_DIR` was undefined.
Tested with `make cmakebuild`, and saw that the man pages got installed to the right place:
```
-- Installing: /Users/terrelln/install_test_dir/lib/pkgconfig/libzstd.pc
-- Installing: /Users/terrelln/install_test_dir/include/zstd.h
-- Installing: /Users/terrelln/install_test_dir/include/zbuff.h
-- Installing: /Users/terrelln/install_test_dir/include/zdict.h
-- Installing: /Users/terrelln/install_test_dir/include/zstd_errors.h
-- Installing: /Users/terrelln/install_test_dir/lib/libzstd.1.3.4.dylib
-- Installing: /Users/terrelln/install_test_dir/lib/libzstd.dylib
-- Installing: /Users/terrelln/install_test_dir/lib/libzstd.a
-- Installing: /Users/terrelln/install_test_dir/bin/zstd
-- Up-to-date: /Users/terrelln/install_test_dir/bin/zstd
-- Installing: …
```
> Fix CMake build

- programs/fileio.c
- tests/playTests.sh
and restore `ovlog==9` when `compressionLevel==ZSTD_maxCLevel()`.
added some tests checking that `ovlog` is not silently ignored,
hence has a direct impact on compression ratio.
> restore ability to set overlapLog

- lib/decompress/zstd_decompress.c
- lib/zstd.h
- tests/fuzzer.c
fix #1078
Improved code documentation of `ZSTD_getFrameHeader()`
Added `ZSTD_getFrameHeader_advanced()`, which makes it possible to request detailed frame header information from a magic-less frame.
Added a test to check it works.
>  added ZSTD_getFrameHeader_advanced()

- tests/playTests.sh
OpenBSD uses md5 instead of md5sum, and has no device called full.
With this patch, make check runs until issue #1088. With the assumption made
in the issue, make check runs succesfully.
> Make sure that make check runs on OpenBSD.

- examples/Makefile
This fixes a building issue on systems that default to a different
flavour of make (as is the case with OpenBSD).
> examples/Makefile assumes GNU make.

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_double_fast.c
- lib/compress/zstd_double_fast.h
- lib/compress/zstd_fast.c
- lib/compress/zstd_fast.h
- lib/compress/zstd_ldm.c
- lib/compress/zstdmt_compress.c
Zstdmt uses prefixes to load the overlap between segments. Loading extra
positions makes compression non-deterministic, depending on the previous
job the context was used for. Since loading extra position takes extra
time as well, only do it when creating a `ZSTD_CDict`.
Fixes #1077.
> Only load extra table positions for CDicts

- programs/zstd.1
- programs/zstd.1.md
> fix typo in programs/zstd.{1,1.md}

- lib/dictBuilder/cover.c
On OpenBSD qsort() is not guaranteed to be stable, their mergesort() is.
This fixes issue #1088. All the hard work has been done by @terrelln.
> zstd requires a stable sort.

- contrib/pzstd/Makefile
On riscv64, 4- and 8-byte accesses are atomic, 1- and 2-byte need library support (-latomic).  This is usually automatically added by ``-pthread``, but pzstd said ``-lpthread`` instead.
> Fix riscv.

- lib/dictBuilder/zdict.c
- programs/zstdcli.c
* Set `dictCLevel` in `zstdcli.c`.
* Only set to default level if the compression level `== 0`, not `<= 0`.
> Allow negative compression levels in training

- lib/compress/zstd_compress.c
- tests/zstreamtest.c
The test fails before the patch and passes after.
Fixes #1095.
> Enforce pledgeSrcSize whenever known

- lib/common/compiler.h
Just an operator precedence problem.
> Fix the DYNAMIC_BMI2 macro enables by mistake on ARM architecture with Clang

- programs/fileio.c
`FIO_decompressLz4Frame()` would keep presenting bogus data 
after an `LZ4F_decompress()` decoding error
resulting in a `NULL` pointer dereference
when associated with older `liblz4` version (< v1.8.1.2).
This fixes it, by exiting the outer loop  too.
Note: I would have liked to add a test case featuring the bug with `liblz4` v1.8.0,
but I was unable to generate one with existing tools
(beyond copy / pasting the reference file in the repository, which would be too heavy weight).
> fixed decoding bogus lz4 frame

- lib/Makefile
Enables fine grain compile/install (e.g. static/dyanamic library only, header-/pc-files only), used
for example by buildroot, see [1].
[1] https://git.buildroot.net/buildroot/tree/package/zstd/zstd.mk
Signed-off-by: Peter Seiderer <ps.report@gmx.net>
> Split library install target into pc, static, shared and include only target

- contrib/pzstd/Options.cpp
Whilst working on the Reproducible Builds effort [0], we noticed
that zstd could not be built reproducibly.
This is due to the manual page encoding the number of CPUs from the
build machine and thus varies across builds.
This was originally filed in Debian as #897904 [1].
[0] https://reproducible-builds.org/
[1] https://bugs.debian.org/897904
Signed-off-by: Chris Lamb <lamby@debian.org>
> Make the build reproducible

- lib/compress/zstd_compress.c
- lib/compress/zstd_double_fast.c
- tests/fuzzer.c
reported by @let-def.
It's actually a bug in `ZSTD_compressBegin_usingCDict()`
which would pass a wrong `pledgedSrcSize` value (`0` instead of `ZSTD_CONTENTSIZE_UNKNOWN`)
resulting in wrong window size, resulting in downsized seqStore,
resulting in segfault when writing into the seqStore later in the process.
Added a test in `fuzzer` to cover this use case.
> fix ZSTD_compressBlock() associated with ZSTD_CDict

- lib/Makefile
Make sure that $(INCLUDEDIR) exists before copying the headers there.
Otherwise, the contest of header files is copied over
$(DESTDIR)$(INCLUDEDIR), making it a regular file.
While at it, remove $(DESTDIR)$(INCLUDEDIR) from the list of directories
to create in the install-pc target. The install-pc target does not need
this directory.
> lib/Makefile: create include directory before headers installation

- programs/zstdcli.c
- tests/playTests.sh
backported from `paramgrill`
`exit()` when numeric argument overflows (>= 4GB)
added associated test case
> minor: control numeric argument overflow

- lib/decompress/zstd_decompress.c
- tests/fuzzer.c
`ZSTD_decompress()` can decompress multiple frames provided as a single input.
But the input size must be the exact sum of all compressed frames, no more.
In the case of a mistake on `srcSize`, being larger than required,
`ZSTD_decompress()` will try to decompress another frame after current one, and fail.
As a consequence, it will issue an error code, `ERROR(prefix_unknown)`.
While the error is technically correct
(the decoder could not recognise the header of _next_ frame),
it's confusing, as users will believe that the first header of the first frame is wrong,
which is not the case (it's correct).
It makes it more difficult to understand that the error is in the source size, which is too large.
This patch changes the error code provided in such a scenario.
If (at least) a first frame …
> decompress: changed error code when input is too large

- lib/dictBuilder/cover.c
The cover algorithm selects one segment per epoch, and it selects the epoch
size such that `epochs * segmentSize ~= dictSize`. Selecting less epochs
gives the algorithm more candidates to choose from for each segment it
selects, and then it will loop back to the first epoch when it hits the
last one.
The trade off is that now it takes longer to select each segment, since it
has to look at more data before making a choice.
I benchmarked on the following data sets using this command:
```sh
$ZSTD -T0 -3 --train-cover=d=8,steps=256 $DIR -r -o dict && $ZSTD -3 -D dict -rc $DIR | wc -c
```
| Data set     | k (approx) |  Before  |  After   | % difference |
|--------------|------------|----------|----------|--------------|
| GitHub       | ~1000      |   738138 |   746610 |       +1.14% |
| …
> [cover] Small compression ratio improvement

- lib/common/entropy_common.c
This edge case is only possible with the new optimal encoding selector,
since before zstd would always choose `set_basic` for small numbers of
sequences.
Fix `FSE_readNCount()` to support buffers < 4 bytes.
> [zstd] Fix decompression edge case

- tests/fuzz/fuzz.py
- tests/fuzz/regression_driver.c
* Fix a typo.
* Make `zip` work for larger corpora, tested it by updating the regression test corpora.
* Define `BIT_DEBUG` in addition to `ZSTD_DEBUG`.
* Increase the maximum allowed file size to 128 MB.
> Small fixes to fuzz.py

- lib/compress/zstd_compress.c
recent experienced showed that
default distribution table for offset
can get it wrong pretty quickly with the nb of symbols,
while it remains a reasonable choice much longer for lengths symbols.
Changed the formula,
so that dynamic threshold is now 32 symbols for offsets.
It remains at 64 symbols for lengths.
Detection based on `defaultNormLog`
> changed dynamic fse threshold for offset

- lib/common/zstd_common.c
- lib/common/zstd_internal.h
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_opt.c
- lib/legacy/zstd_v04.c
This is mostly a simplification of the optimal parser.
It gets rid of the "cache" structure for literals.
The cache was required for performance because the previous version of optimal parser would recalculate the full cost of all literals + litLength at each position.
In this new version, this cost is simply saved into the path table.
This removes a bunch of functions,
and slightly improves speed (mostly visible for small files).
Used this opportunity to change a few variable names, for clarity.
There are some minor ramifications beyond `zstd_opt.c` as I had to improve the debugging log functionality to properly validate this patch.
> minor optimal parser optimization

- lib/compress/zstd_compress.c
- lib/compress/zstd_double_fast.c
- lib/compress/zstd_double_fast.h
This PR has some additional refactoring on top of #1138 that rewrites `ZSTD_compressBlock_doubleFast_generic` to control flow with `goto`s rather than deeply nested if/else blocks. In doing so, it is able to more closely match the existing compression strategy.
> ZSTD_dfast: Support Searching the Dictionary Context In-Place (Alternate `goto` Implementation)

- lib/zstd.h
Extend guarantee that `ZSTD_getFrameContentSize()` will deliver the decompressed size
to frames compressed by any single-pass compression function.
Answer #1156
> minor : improved zstd.h API code comment

- programs/zstd.1.md
- programs/zstdcli.c
- tests/playTests.sh
for scripts
Test Plan:
Ran with new flag over an old flag
gclu-mbp:programs gclu$ ./zstd --rm --format=gzip --format=zstd blah.txt
blah.txt             :183.33%   (    12 =>     22 bytes, blah.txt.zst)         
gclu-mbp:programs gclu$ ./zstd -d --rm --format=gzip --format=zstd blah.txt.zst
blah.txt.zst        : 12 bytes
Overrides previous format flags (and doesn't give error)
> Added --format=zstd

- programs/fileio.c
- tests/playTests.sh
Changed so only compiled formats are printed in list of supported extensions
Test Plan: Compiled w/o support for lzma/xz/lz4, did in fact print out the right thing.
zstd -d blah.abc
zstd: blah.abc: unknown suffix (.zst/.gz expected) -- ignored
> Unknown Suffix Error

- tests/paramgrill.c
Previous: paramgrill -Sw23c23h22s06l3t048S6
Added: paramgrill --zstd=windowLog=23,chainLog=23,hashLog=22,searchLog=6,searchLength=3,targetLength=48,strategy=6
Should behave equivalently to old command (which still exists)
Test Plan:
Ran above commands, produced same result.
> Added zstdcli-style format for compression parameters in paramgrill

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_double_fast.c
- lib/compress/zstd_fast.c
- lib/decompress/zstd_decompress.c
- tests/zstreamtest.c
recently introduced within the new dictionary mode (not part of any release).
The bug can be reproduced with this command :
`./zstreamtest -v --opaqueapi --no-big-tests -s4092 -t639`
Error was when invoking `ZSTD_count_2segments()` :
the beginning of the 2nd segment corresponds to `prefixStart`
as opposed to the beginning of the current block (`istart == src`).
Both pointers are identical during the first block,
so the issue only appears if `src` is large enough to require at least 2 blocks.
Then it results in comparing the wrong byte(s).
The bug was detected in `compressBlock_fast`
but is also present in `compressBlock_doubleFast`.
This patch fix both.
Changed a few variable names in the process,
in the hope to improve clarity.
> Fixed a corruption bug

- .travis.yml
- Makefile
- contrib/seekable_format/examples/Makefile
- contrib/seekable_format/zstd_seekable.h
- contrib/seekable_format/zstdseek_decompress.c
- doc/zstd_manual.html
Fixes #1166 .
There were some unfortunate type mismatch in `seekable_format`,
of the kind `U64` <==> `unsigned long long`.
This is only a problem in some situations. It happens for example with Linux + gcc5.
No issue with Mac OS-X llvm, or Linux + gcc4.8,
which were unfortunately the platforms used for the relevant test (`make all`).
This patch also ensures the test `make all` is played with `gcc6` on travis CI.
It also improved `make -j all`, by ensuring `libzstd` is only built once and then shared by dependencies.
> contrib/seekable_format on gcc5+

- .travis.yml
- Makefile
- doc/zstd_manual.html
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- tests/fuzzer.c
In order to skip some allocation and initialization work,
it's recommended to preserve and re-use a compression context
across multiple compression jobs.
This can translate into substantial savings when dealing with a lot of small data.
The baseline scenario was that a process would fire up,
proceed with a batch of compression job, re-using a context in the process,
and then release the context at the end.
The context resizes up when it needs more than it has already allocated.
But it never resizes down.
In some cases though, some context might be preserved for a very long time (multiple days),
and have to process some various workload,
containing some rare random outliers (large files, high compression ratio).
This would result in a context being sized for this rare outlier,
even if the …
> Dynamic context downsize

- programs/bench.c
- programs/bench.h
- programs/zstdcli.c
- tests/Makefile
- tests/paramgrill.c
- tests/playTests.sh
Delete paramgrill's old benchmarking function to use bench.c's instead. Make bench.c's benchmarking return results instead of just printing.
> Have paramgrill share bench.c benchmarking function

- lib/compress/zstd_compress.c
- lib/compress/zstd_lazy.c
- lib/compress/zstd_lazy.h
Extending the work of #1151 and #1117, this change set allows the `ZSTD_greedy`, `ZSTD_lazy`, and `ZSTD_lazy2` strategies to reference a separate dictionary context in-place. Performance figures are being prepared.
> ZSTD_lazy: Support Searching the Dictionary Context In-Place

- Makefile
- lib/common/bitstream.h
- lib/common/debug.c
- lib/common/debug.h
- lib/common/fse_decompress.c
- lib/common/zstd_common.c
- lib/common/zstd_internal.h
- lib/compress/fse_compress.c
- lib/compress/huf_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstdmt_compress.c
- lib/decompress/huf_decompress.c
- lib/dictBuilder/zdict.c
- lib/legacy/zstd_v04.c
- tests/Makefile
- tests/fuzz/fuzz.h
- tests/fuzz/fuzz.py
There were 2 competing set of debug functions
within `zstd_internal.h` and `bitstream.h`.
They were mostly duplicate, and required care to avoid messing with each other.
This patch proposed to keep a single implementation, shared by both.
Notable change :
The macro variable `ZSTD_DEBUG` does no longer exist,
it has been replaced by `DEBUGLEVEL` (more generic, can be used from `fse` project without dependency from `zstd`).
This required modifying several source files.
> Grouped debug functions into debug.h

- .travis.yml
- lib/decompress/zstd_decompress.c
- tests/Makefile
when `ZSTD_HEAPMODE=0` (which is not default).
Also : added an associated test (`test-fuzzer-stackmode`)
run on travis CI
fix #1186
> fix dctx initialization within ZSTD_decompress in stack mode

- build/VS2008/fullbench/fullbench.vcproj
- build/VS2008/fuzzer/fuzzer.vcproj
- build/VS2008/zstd/zstd.vcproj
- build/VS2008/zstdlib/zstdlib.vcproj
- build/VS2010/fullbench/fullbench.vcxproj
- build/VS2010/fuzzer/fuzzer.vcxproj
- build/VS2010/libzstd-dll/libzstd-dll.vcxproj
- build/VS2010/libzstd/libzstd.vcxproj
- build/VS2010/zstd/zstd.vcxproj
- build/cmake/lib/CMakeLists.txt
- build/cmake/tests/CMakeLists.txt
- doc/zstd_manual.html
- lib/common/fse.h
- lib/compress/fse_compress.c
- lib/compress/hist.c
- lib/compress/hist.h
- lib/compress/huf_compress.c
- lib/compress/zstd_compress.c
- lib/compress/zstd_opt.c
- tests/decodecorpus.c
It always bugged me that `HUF_compress()` needs to invoke `FSE_count()` to build its histogram.
Histogram functions can be useful for more than just FSE. As a recent example, the optimal parser uses this capability to populate its initial statistics.
This patch regroups all histogram functions into `hist.c`
and rename them with `HIST_*` prefix.
This focus also helped make the interface slightly cleaner (within `hist.h`).
> histogram module

- lib/compress/zstd_compress.c
- lib/compress/zstd_lazy.c
Continuing the work of #1169 (and #1151 and #1117), this PR allows the `ZSTD_btlazy2` to perform searches against an external, immutable dictionary context.
> ZSTD_btlazy2: Support Searching the Dictionary Context In-Place

- programs/fileio.c
- tests/playTests.sh
`--list` does not support piped input
This commit checks if the STDIN is not from a terminal and exits 1 
with a well formatted error message 
the output of this command may still be piped to another program
**examples of the code change below**
```
zstd [dev] :> ./zstd --list # exits 0
zstd [dev] :> echo "awdaw" | ./zstd --list
zstd --list does not support reading from standard input # exits 1
zstd [dev] :> ./zstd --list | echo # exits 0
```
I don't believe this type of code is usually tested.  Please inform me if i am incorrect and I will add tests.
closes task `T29991838` @Cyan4973
> Improves UX for --list command's lack of support for pipes

- lib/compress/zstd_compress.c
- lib/compress/zstd_ldm.c
- lib/compress/zstdmt_compress.c
- programs/fileio.c
When we know the `pledgedSrcSize`, adjust the LDM parameters to
reflect smaller file sizes.
> Adjust advanced parameters to source size

- lib/compress/huf_compress.c
for huffman compression.
It's a minor but impactful change.
When data is not compressible, it's not worth spending cpu time trying to compress it just to discard the result afterwards.
The heuristics `largest <= (srcSize >> 7)` works relatively well, but mostly for "large enough" data.
When data is small (for example ~1KB, typical for network packets), there are natural irregularity in a random source, which guarantee that the most frequent symbol will be `> (srcSize >> 8)`, to the point of being fairly close to current threshold.
Actually, measurements show that, for a small `srcSize`, a majority of distributions satisfy the condition. As a consequence, huffman compression is uselessly attempted. 
Any compression triggers a fixed cost, in the form of creating a huffman table, which …
> Increase threshold detection of poorly compressible data

- lib/common/pool.c
- lib/common/pool.h
- lib/compress/zstd_compress.c
- lib/compress/zstdmt_compress.c
- lib/compress/zstdmt_compress.h
- lib/decompress/zstd_decompress.c
- tests/poolTests.c
- tests/zstreamtest.c
This patch makes `POOL_ctx` resizable.
Up to now, when number of threads was changed, it was only possible to `free` and then `create` a new `POOL_ctx`.
This capability, combined with a few more resizable structures inside `ZSTDMT`, dramatically reduces the number of threads created in situation where the number of requested threads frequently changes,
which is the case with `zstreamtest --newapi`.
The expected benefits are :
- thread sanitizer : this test max out pretty quickly when the nb of threads created becomes large. It stops on reaching a limit. The limit should now be a lesser problem.
- less flaky qemu ARM test : we regularly have random crashes when testing ARM with qemu, but specifically during test of `zstreamtest --newapi`. This behavior is suspected related to the high …
> Thread Pool resize

- lib/compress/zstdmt_compress.c
- lib/compress/zstdmt_compress.h
- tests/zstreamtest.c
* `ZSTDMT_serialState_reset()` should use `targetSectionSize`, not `jobSize` when sizing the seqstore.
Add an assert that checks that we sized the seqstore using the right job size.
* `ZSTDMT_compressionJob()` should check if `rawSeqStore.seq == NULL`.
* `ZSTDMT_initCStream_internal()` should not modify `mtctx->params.jobSize`.
> [zstdmt] Fix jobsize bugs

- build/cmake/lib/CMakeLists.txt
The original conditions only worked, when both, static and shared variants where built, resulting in an inconsistency between programs and library. The program was built with MT support enabled, the library not. That lead to _error 11 'unsupported parameter'_ when compressing anything with the command line tool.
When changing the AND condition to `ZSTD_MULTITHREAD_SUPPORT AND (ZSTD_BUILD_SHARED OR ZSTD_BUILD_SHARED)`, cmake stopps complaining one of the targets wasn't built. This commit works for any case.
> Correct multithread logic, fixing 'unsupported parameter' error

- doc/zstd_manual.html
- lib/common/entropy_common.c
- lib/compress/zstd_compress.c
Target scenario : "github_users" sample set (small data), no dictionary
before (`dev`): 
```
1# 9114 files       :   7484607 ->   2611474 (2.866), 197.3 MB/s , 573.9 MB/s   (fast)
3# 9114 files       :   7484607 ->   2495167 (3.000), 183.9 MB/s , 438.5 MB/s   (dFast)
4# 9114 files       :   7484607 ->   2489981 (3.006), 151.1 MB/s , 442.6 MB/s   (greedy)
5# 9114 files       :   7484607 ->   2471124 (3.029), 121.0 MB/s , 443.3 MB/s   (lazy)
```
after (`decSpeed`): 
```
1# 9114 files       :   7484607 ->   2623874 (2.853), 204.2 MB/s , 627.4 MB/s   (fast)
3# 9114 files       :   7484607 ->   2495167 (3.000), 182.6 MB/s , 462.2 MB/s   (dFast)
4# 9114 files       :   7484607 ->   2489981 (3.006), 150.0 MB/s , 466.3 MB/s   (greedy)
5# 9114 files       :   7484607 ->   2471124 (3.029), 120.5 …
```
> Fix decoding speed

- .travis.yml
arm64 tests have been failing recently
due to some strange bug in `ld` after travis CI updated `ld` version for arm64.
Just attempting to re-enable arm64 tests, see if they work correctly again
> re-enable arm64 tests

- programs/zstd.1
- programs/zstd.1.md
regarding advanced parameter `tlen`
which was recently changed.
`0` in association with `ZSTD_fast` now means "normal fast mode".
> minor man page update

- .travis.yml
- programs/fileio.c
- tests/playTests.sh
Also now returns an error when no inputs are given.
New proposed behavior:
```
felix@odin:~/prog/zstd (list-stdin-check)$ ./zstd -l; echo $?
No files given
1
felix@odin:~/prog/zstd (list-stdin-check)$ ./zstd -l Makefile.zst; echo $?
Frames  Skips  Compressed  Uncompressed  Ratio  Check  Filename
1      0     3.08 KB      10.92 KB  3.544  XXH64  Makefile.zst
0
felix@odin:~/prog/zstd (list-stdin-check)$ ./zstd -l <Makefile.zst; echo $?
zstd: --list does not support reading from standard input
No files given
1
felix@odin:~/prog/zstd (list-stdin-check)$ ./zstd -l Makefile.zst <Makefile.zst; echo $?
Frames  Skips  Compressed  Uncompressed  Ratio  Check  Filename
1      0     3.08 KB      10.92 KB  3.544  XXH64  Makefile.zst
0
felix@odin:~/prog/zstd (list-stdin-check)$
```
> Allow Invoking `zstd --list` When `stdin` is not a `tty`

- tests/playTests.sh
1.) OpenBSD is unable to write to /dev/zero
#1124 fixes an issue with GNU/Hurd being unable to write to /dev/zero. Implemented fix is writing to /dev/random instead.
On OpenBSD a regular user is unable to write to /dev/random because of permissions set on this device. Result is failing a regression test.
Proposed solution should work for all platforms.
2.) xz/lzma warning causes test to fail
OpenBSD's port building infrastructure is able to build in a privilege separated mode. It uses a privilege drop model. Regression tests fail in this mode as xz/lzma is unable to set file group and errors out with:
```
xz: tmp.xz: Cannot set the file group: Operation not permitted
gmake[1]: *** [Makefile:307: zstd-playTests] Error 2
```
Actually it is not a xz/lzma error but a warning causing zstd's …
> 2 separate issues found when running zstd's tests on OpenBSD

- build/VS2010/fullbench-dll/fullbench-dll.vcxproj
- build/VS2010/fullbench/fullbench.vcxproj
- programs/bench.c
- programs/bench.h
- programs/zstdcli.c
- tests/Makefile
- tests/fullbench.c
- tests/paramgrill.c
Added -l and --zstd= flag support to fullbench to benchmark functions at custom compression levels / compression parameters respectively. 
Note: only last commit (fda87d9) is for this, written on BenchModule branch
> Fullbench Param

- lib/common/compiler.h
prevent usage of prefetch intrinsic commands
which are not supported by `c2rust`
(see https://github.com/immunant/c2rust/issues/13)
> add build macro NO_PREFETCH

- tests/playTests.sh
https://github.com/facebook/zstd/pull/1124 broke the test suite
on Linux.  Looks like GNU/Hurd is the only operating system where
/dev/random is available for writing by unprivileged processes.
https://github.com/facebook/zstd/pull/1222 reverted the change
introduced by https://github.com/facebook/zstd/pull/1124 for OpenBSD
only, other operating systems need that change to be reverted, too.
Fixes: 2dde9d5abaad ("Write to /dev/random for test")
Complements: 276988f7948d ("OpenBSD is unable to write to /dev/zero")
> tests: use /dev/zero instead of /dev/random on all systems except GNU/Hurd

- programs/fileio.c
We can write a corrupted file if the input file errors during a read.
We should return a non-zero error code in this case.
> fileio: Error in compression on read errors

- lib/compress/zstdmt_compress.c
since mingw does not have `sys/times.h`,
remove this path when detecting mingw compilation.
> zstdmt debug traces compatibles with mingw

- lib/compress/zstd_compress.c
- tests/zstreamtest.c
The correct parameters are used once, but once `ZSTD_resetCStream()` is
called the default parameters (level 3) are used. Fix this by setting
`requestedParams` in the `ZSTD_initCStream*()` functions.
The added tests both fail before this patch and pass after.
Fixes #1229.
> Set requestedParams in ZSTD_initCStream*()

- programs/zstdcli.c
- tests/playTests.sh
Only set the default value if `outFileName` is unset.
Fixes #1227.
> zstdcli: Allow -o before --train

- lib/compress/fse_compress.c
- tests/fuzzer.c
When the primary normalization method fails, and
`(1 << tableLog) == (maxSymbolValue + 1)`, and every symbol gets assigned
normalized weight 1 or -1 in the first loop, then the next division can
raise `SIGFPE`.
I'm looking into getting a test case.
> [FSE] Fix division by zero

- lib/compress/zstd_compress.c
CDicts were previously guaranteed to be generated with `lowLimit=dictLimit=0`.
This is no longer true, and so the old length and index calculations are no
longer valid. This diff fixes them to handle non-zero start indices in CDicts.
> Fix fix1241: Fix CDict Attachment to Handle CDicts with Non-Zero Starts

- .travis.yml
- Makefile
Added gcc-8 tests, ensure warnings break tests
note : currently break, due to existing issues that were not flagged
to be fixed in a separate PR
> gcc-8 travis test

- programs/README.md
presenting `zstdgrep` limit regarding dictionary compression
with workaround recommended by @tobwen (#1268)
> added zstdgrep documentation

- programs/bench.c
- programs/bench.h
- tests/Makefile
- tests/README.md
- tests/fullbench.c
- tests/paramgrill.c
Adds additional Functionality to paramgrill
-Accepts decompression speed and compression memory as constraints
-Accepts fixed parameters as constraints (ex: windowLog=8)
-Accepts dictionaries and multiple files
-Improves convergence speed
Testing:
Ran with various constraint configurations and files.
> ParamgrillConstraints

- tests/README.md
- tests/paramgrill.c
Based on forceAttachDict (Last 3 commits new)
Simplify adding new params
Add option for memoization table to be hash table or to be turned off altogether
Change format of speed/ratio tradeoff on command line
> memoTableOptions

- programs/fileio.c
- tests/.gitignore
Per warnings from flawfinder: "Does not check for buffer overflows when
copying to destination [MS-banned] (CWE-120). Consider using snprintf,
strcpy_s, or strlcpy (warning: strncpy easily misused).".
To reproduce warning:
./flawfinder.py ./programs/fileio.c
Replaced called to strcpy and strcat in `fileio.c` to calls with a
specified size (`strncpy` and `strncat`).
Tested the changes on OSX, Linux, Windows.
On OSX + Linux, changes were tested with ASAN. The following flags were
used: 'check_initialization_order=1:strict_init_order=1:detect_odr_violation=1:detect_stack_use_after_return=1'
All test suites were run (`make test`).
On Windows, building was done with visual studio and `fuzzer.c` binary was executed.
Also: added gitigignore entry for test byproduct `tm`.
> Fixed unsafe string copy and concat in `fileio.c`.

- build/cmake/contrib/gen_html/CMakeLists.txt
This allows installing the architecture independent data outside the prefix, for example on a multiarch layout where the prefix is /usr/{host-triplet}.
> Use GNUInstallDirs DOCDIR for installing the manual

- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/zstd.h
- tests/decodecorpus.c
* `ZSTD_sufficientBuff()` was pessimistic about having enough space for the `seqStore_t`.
* Improve documentation surrounding empty `ZSTD_CDict`s.
> Reuse the ZSTD_CCtx more often with small data.

- lib/compress/zstd_compress.c
- tests/zstreamtest.c
Credit to @terrelln for the heavy lifting.
In certain circumstances, it was possible for zstd to incorrectly reuse the offset FSE table. Specifically, we found this broke when all of the following were the case:
1. When compressing with a dictionary.
2. When the first block emitted was uncompressible.
3. When the second block tried reuse the existing tables.
4. When the second block included a long offset.
This patch closes this loophole. (The included test segfaults before the fix, and passes afterwards.)
> Fix Missing Offset Table Check

- lib/dictBuilder/zdict.c
cppcheck (which is run regularly in our CI environment)  detected a possible memory leak.
> Fixed memory leak detected by cppcheck

- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- tests/decodecorpus.c
- tests/fuzzer.c
We could undersize the literals buffer by up to 11 bytes,
due to a combination of 2 bugs:
* The literals buffer didn't have `WILDCOPY_OVERLENGTH` extra
space, like it is supposed to.
* We didn't check the literals buffer size in `ZSTD_sufficientBuff()`.
Add test cases for growth of the `seqStore` that would have caught the bug.
> [zstd] Fix seqStore growth

- lib/decompress/huf_decompress.c
- lib/decompress/zstd_decompress.c
- programs/util.h
by removing `workspace`
which is only needed while building huffman table.
`workspace` is now either present within `DCtx`,
or replaced by temporary use of available FSE table space.
>  reduce DDict size by 2KB

- lib/common/cpu.h
The `__cpuid()` and `__cpuidex()` intrinsics are only available on x86 and x86_64.
Fixes #1313.
> [libzstd] Fix cpu for MSFT ARM

- NEWS
- contrib/largeNbDicts/largeNbDicts.c
- doc/zstd_manual.html
- lib/common/compiler.h
- lib/decompress/zstd_decompress.c
- tests/zstreamtest.c
In situation where there are many (~ several thousands) dictionaries in memory accessed in random order, the speed of dictionary decompression can be noticeably impacted (#1289), because dictionaries are always "cold", generating a lot of cache misses.
This patch mitigates this detrimental effect, by detecting when it happens, and issuing selected prefetching orders before starting decompression.
This version is more general than previously created `mitigationXp`. 
It preserves current performance when dictionary is re-used. 
It carefully triggers prefetching only when tables are necessary, 
and only when the amount of associated work is "large enough". 
Different heuristics have been tested to define this criteria, 
I've been conservative during their selection, as the more a host is …
> Cold dictionary mitigation

- Makefile
- lib/compress/hist.h
Cleanup some typo to make clangbuild target working.
Clang-6.0.0 on ubuntu bionic emits errors on the broken doxygen comment.
> Fix clang build

- contrib/largeNbDicts/largeNbDicts.c
Remove unsigned to size_t promotion to fix implicit down conversion errors in clangbuild target on the dev branch.
nbDicts/nbBlocks. that represent number of some objects, were generated as unsigned by the command line parser. There is no need to declare as size_t to just pass them to another function.
> Fix largeNbDicts bench for clangbuild

- tests/playTests.sh
`tests/playTests.sh` uses `head -c` in a couple of tests to truncate the last byte of a file. The '-c' option is non-portable (not in POSIX). Instead use a wrapper around `dd` (truncateLastByte).
> 'head -c BYTES' is non-portable.

- lib/compress/zstd_double_fast.c
- lib/compress/zstd_fast.c
This PR causes `ZSTD_fast` and `ZSTD_dfast` in `ZSTD_dictMatchState` mode to actually perfectly mirror the behavior of `ZSTD_extDict` (aka copying the dict ctx into the working ctx). Previously, in DMS mode, these strategies would search the dictionary tables if the working tables didn't have an entry (`matchIndex < prefixLowestIndex`) **or** if the working tables' entry was a mismatch (`MEM_read32(match) != MEM_read32(ip)`). This latter situation caused behavior to differ, since in the copied-dict scenario, the existence of the mismatched entry would have overwritten the dictionary match.
So this PR changes their behaviors to only search the dictionary tables in the first situation, but not the second.
Perf results are forthcoming. I expect this to actually be perf-positive for these …
> Don't Search Dictionary Context When Working Context Search Resulted in Mismatch

- contrib/pzstd/Options.cpp
- contrib/pzstd/Pzstd.cpp
- lib/Makefile
- programs/fileio.c
- programs/util.h
- zlibWrapper/gzguts.h
only enable backtraces for platforms we know support it
aka mac OS-X and Linux.
can be extended later.
note : strangely enough, compilation was an issue only on my local `mingw` installation,
while Appveyor tests were running fine (???)
> fix mingw compatibility

- lib/common/mem.h
in order to ensure correct type mapping
when `stdint.h` is not available.
> added some tests based on limits.h

- .circleci/config.yml
- tests/fuzz/fuzz.py
* Updates CircleCI to use workflows.
We can now specify any number of test jobs to run in parallel.
* Switch the image to `buildpack-deps:trusty` which is only 500 MB
instead of 7 GB, so that saves 7 minutes to download it if it isn't
already cached on the host.
* Publish the source tarball and sha256sum as artifacts for tag builds only.
Whenever a new tag is created, a build is triggered that runs the tests,
and then publishes the artifacts to the job.
> Publish artifacts with CircleCI

- lib/compress/zstd_compress.c
- lib/compress/zstd_fast.c
- tests/fuzzer.c
Experimental function `ZSTD_compressBlock()` is designed for very small data in mind,
for situations where saving the ~12 bytes of frame header can actually make a difference.
Some systems though may have to deal with data blobs of any size, small and large entangled.
When data is larger than a block (> 128KB), `ZSTD_compressBlock()` cannot compress them in a single round.
That's why it's also possible to compress in multiple rounds.
This generates a chain of compressed blocks.
Some users push this extended capability to the limit, encoding gigantic chains of blocks.
On crossing the 4GB limit, some internal overflow occurs.
This fix moves the existing overflow correction mechanism higher in the call chain,
so that it's applied also to gigantic chains of blocks.
Added a test case in …
> fix : huge (>4GB) chain of blocks

- lib/Makefile
- lib/common/xxhash.c
- lib/compress/fse_compress.c
- lib/compress/huf_compress.c
- lib/compress/zstd_compress.c
- lib/compress/zstd_lazy.c
- lib/compress/zstd_opt.c
- lib/compress/zstdmt_compress.c
- lib/decompress/zstd_decompress.c
- lib/dictBuilder/zdict.c
- lib/legacy/zstd_v01.c
- lib/legacy/zstd_v04.c
- lib/legacy/zstd_v05.c
- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
- programs/Makefile
- programs/datagen.c
- programs/dibio.c
- programs/fileio.c
- tests/Makefile
- tests/fullbench.c
- tests/fuzzer.c
- tests/paramgrill.c
- tests/zstreamtest.c
This is the first batch of fixes for using upstream zstd in GRUB. There may be more, but it is building now, so I wanted to get this batch in now.
* Enable `-Wmissing-prototypes`. This is a generally useful flag, it found a bunch of functions that can be static. The ones that have "hidden" declarations, we now have to explicitly declare it right before the definition.
* Include `stddef.h` in xxhash for `size_t`.
* Rename a variable named `byte` because of a conflicting typedef.
> Fixes for GRUB

- tests/zstreamtest.c
We could allocate up to 2^28 bytes of memory for the zstdmt buffers when
using 2 threads with window log = 24. Now, we limit it to 2^26 bytes of memor
when not running big tests. It will also reduce the hashlog / chainlog memory.
I chose max window log = 22 since that is the maximum source size when
big tests are disabled. Hopefully this will be enough to reduce or
eliminate the test failures.
> [zstreamtest] Reduce memory of newapi tests

- lib/compress/zstd_compress.c
- tests/zstreamtest.c
If we emit many blocks that are too small to compress (<= 6 bytes) we never invalidate the dictionaries offset table. This will cause corruption if we have enough small blocks to allow an offset larger than the dictionary can support.
Refactor `ZSTD_compressBlock_internal()` to have an `out` label, which does the confirmation and validation work, which we `goto` at all exit points.
The added test fails before the patch, and succeeds afterwards.
> [zstd] Fix resetting FSE tables

- Makefile
- programs/util.h
- zlibWrapper/examples/minigzip.c
CircleCI build should pass `-Werror` to the build tests, instead of relying it on being set implicitly in the environment variables.
This exposes a warning about `lstat()` in `-std=c99` builds. `-std=c99` defines `__STRICT_ANSI__`, which hides the declaration of `lstat()` in the `<sys/stat.h>` header.
I also fixed warnings `minigzip.c`. Since it is just an example, I just removed `snprintf()`.
> Add -Werror to *build rules

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_double_fast.c
- lib/compress/zstd_double_fast.h
- lib/compress/zstd_fast.c
- lib/compress/zstd_fast.h
- lib/compress/zstd_lazy.c
- lib/compress/zstd_lazy.h
- lib/compress/zstd_ldm.c
- lib/compress/zstd_ldm.h
- lib/compress/zstd_opt.c
- lib/compress/zstd_opt.h
This PR includes two broad changes.
(I.e., this PR includes a resubmission of #1296.)
The `ZSTD_matchState_t` cannot be interpreted or manipulated without knowledge of the compression parameters it has been configured with. As a consequence, pretty much anywhere the match state is passed, a pointer to the cparams had to be passed as well. This changeset adds a copy of the cparams in the match state struct, which allows us to streamline the signatures of a great many functions.
This change is made here because, without it, the block compressors do not have access to the cdict's compression parameters. The only alternative to this change would be to add another cparams argument to the block compressor function signature and its many implementations. With this change, the dict match state's …
> Independent Dictionary and Working Context Table Logs

- NEWS
- lib/legacy/zstd_v05.c
- programs/platform.h
- programs/util.h
some non-trivial changes to `platform.h` and `util.h`,
initially related to compilation for Haiku,
but I used this opportunity to make them cleaner
and add some documentation.
Tested on a "Haiku" VM, compilation works fine (while it fails with current `dev` branch).
I noticed several platform tests could be improved
(too harsh conditions, useless exception, etc.)
but I did not dare modifying too many tests just before release.
>  portability macro flags updates, for Haiku

- programs/fileio.c
check for __GLIBC__ instead of __linux__ as musl libc doesn't provide
execinfo.h
fixes compilation on Alpine Linux and Void Linux musl arches.
> don't assume __linux__ means __GLIBC__ on BACKTRACES_ENABLE

- lib/compress/zstd_lazy.c
This changeset switches the mitigation strategy away from the one taken in PR #1350 (which avoids missing the end-of-input check by restarting the dictionary search with `bestLength = 0`) to totally avoiding searching the dictionary when we're in that situation, since a precondition to being at risk of running past the end of the input is that we've already found an optimal match. So there's no utility in searching the dictionary. I suspect this will produce a small performance win.
Notably, this approach to avoiding the issue was already present in the `ZSTD_btopt` implementation. Not sure how it got missed in `ZSTD_btlazy2` :cry:.
In making this change, this patch fixes an unfortunate bug. Without this change, the `ZSTD_btlazy2` strategy unconditionally selects the best dictionary match …
> `ZSTD_btlazy2`: Avoid Erroneously Trampling on Match with Worse Dictionary Match

- programs/Makefile
- programs/README.md
- programs/fileio.c
following #1356,
only enable backtrace compilation on linux+glibc.
Also, disable backtrace by default from "release" compilation,
so that less platforms get impacted by the new requirements.
Can be manually enabled/disabled using `BACKTRACE=1/0`.
> backtrace support compiled with more conditions

- lib/common/bitstream.h
When extracting bits from a register,
there are 2 possible methods : double shift, or shift+mask.
This patch arbitrates this choice in favor of shift+mask.
On my laptop, it results in a substantial speed boost on `clang` (+6.5%), and a moderate one on `gcc` (+2.5%). The `clang` win is remarkable.
But that's not the end of the story. The situation is different on other platforms : 
On `entropy`, with bmi2 : `clang` -2%, and `gcc` +1%.
On `entropy`, without bmi2 : `clang` +3%, and `gcc` +3%
On my outdated core 2 platform, necessarily without bmi2 : `clang` -2%, and `gcc` +0%.
So mileage vary. It might also vary depending on compiler versions.
In general, one should expect shift+mask to perform better when bmi2 is not present,
but it's not always the case (see core2 results). And, even with …
> Improved decompression speed

- lib/common/mem.h
Necessary because clang disguises itself as an older (__GNUC_MINOR__ = 2) GCC.
> Enable use of bswap intrinsics in clang

- programs/fileio.c
`gcc-8` on Linux doesn't like `strncat` :
`warning: ‘strncat’ output truncated before terminating nul copying as many bytes from a string as its length`.
Not sure what was wrong, might as well be a false positive.
I can only produce this warning on gcc-8 on Linux.
gcc-8 on OS-X doesn't complain, neither clang nor gcc-7.
Anyway, the logic is simple enough to replaced by a simple `memcpy()`,
thus avoiding the shenanigans of null-terminated strings.
> fixed minor gcc warning

- build/cmake/programs/CMakeLists.txt
- programs/Makefile
- programs/zstdgrep.1
- programs/zstdgrep.1.md
- programs/zstdless.1
- programs/zstdless.1.md
zgrep and zless come with man pages, this adds the same to zstdgrep and zstdless
The zstdgrep man page closely mirrors the zgrep man page; the zstdless is a little... less
> Add man pages for zstdgrep and zstdless

- tests/fuzz/Makefile
libFuzzer's git repo was [moved into compiler-rt](https://reviews.llvm.org/D36908), so `make libFuzzer` clones an empty repo and dies.
change points to the new location within compiler-rt; `make libFuzzer` now builds libFuzzer.a
> Fix libFuzzer location in makefile.

- doc/zstd_compression_format.md
If the current sequence has literal length of zero then an offset value
of three is handled in a special manner. While I implemented a golang
decoder I had to consult the educational decoder for clarification on
the update of the offset history in that case. This commit provides the
clarification that the offset value Repeated_Offset1-1 is handled as a
new offset is added to the offset history accordingly.
> Clarify special case of offset history update

- lib/decompress/zstd_decompress.c
- tests/fuzzer.c
fix #1385 : 
decompressing into `NULL` is an automatic error in `v1.3.7`.
This patch now allows it, as long as the content of the frame is empty.
This behavior seems to simplify things a bit for `arrow`.
Not sure if any other project may rely on this behavior...
> support decompressing an empty frame into NULL

- .circleci/config.yml
Publish the tar uncompressed, zstd compressed, and gzipped. Also publish the `sha256` files for each.
See the artifacts in https://circleci.com/gh/terrelln/zstd/737#artifacts/containers/0 for an example of what gets produced.
> Publish uncompressed, zstd, and gzipped packages

- lib/zstd.h
Consistency is important. If we ignore little things like this, we aren't perfecting our craft. Right?
> provide consistent spacing to enum field

- lib/compress/fse_compress.c
- lib/compress/hist.c
- lib/compress/hist.h
- lib/compress/huf_compress.c
- lib/compress/zstd_compress.c
- tests/decodecorpus.c
Follow up #1393 
Changed `workspace` parameter convention
in order to always provide `workspaceSize`,
so that size can be explicitly checked.
Also, use more `enum` to improve clarity of some parameters.
> refactor HUF_compress_internal for clarity 

- programs/Makefile
Fix building zstd-pgo,
especially with make -j2 or more
> Fix building zstd-pgo

- lib/compress/zstd_opt.c
to express a restricted range condition on `ll0` .
Might also help static analyzer as in #1397
> just add an assert() in ZSTD_insertBtAndGetAllMatches()

- build/cmake/CMakeLists.txt
Only set the build type to Release if the user didn't select any.
See discussion in https://github.com/facebook/zstd/pull/1278#issuecomment-436327923 and below.
> Allow creating debug builds with CMake

- lib/dictBuilder/cover.c
If one of the helper threads executing `COVER_best_finish()` fails to allocate memory, it exits without releasing the mutex. Moreover, if every thread fails on `malloc()` then the main thread sleeps indifinetely on condition variable - that's why `cond_signal()` is also needed.
> Prevent deadlock on malloc() failure.

- lib/common/compiler.h
- lib/decompress/zstd_decompress_block.c
- programs/bench.c
- tests/playTests.sh
on `enwik9` at level 22 (which is a pretty hard scenario with long-range matches),
decompression speed improves by +7% on my laptop (415 -> 445 MB/s)
also : 
fixed benchmark decode-only mode
>  improve long-range decoder speed

- contrib/largeNbDicts/Makefile
- contrib/largeNbDicts/largeNbDicts.c
- lib/decompress/zstd_ddict.c
- lib/decompress/zstd_decompress.c
- lib/decompress/zstd_decompress_block.c
by triggering the prefetching decoder path
(which used to be dedicated to long-range offsets only).
Some figures on my laptop :
(note : all versions prefetch huffman and fse tables)
no content prefetch : ~300 MB/s (for reference)
full content prefetch : ~325 MB/s (before this patch)
new prefetch path : ~375 MB/s (after this patch)
The speed advantage is significant,
and another side-effect is that this version prefetches less data into cache,
since it only prefetches what's needed (instead of the full dictionary).
This pollutes the cache less,
and is supposed to help highly active environments, such as databases.
This effect can't be properly measured in benchmark environment (too clean).
Also :
fixed the `largeNbDicts` test program
which was working improperly when setting `nbBlocks` > …
> Improves decompression speed when using cold dictionary

- build/VS2010/fullbench-dll/fullbench-dll.vcxproj
- build/VS2010/fullbench/fullbench.vcxproj
- build/VS2010/zstd/zstd.vcxproj
- build/cmake/programs/CMakeLists.txt
- build/cmake/tests/CMakeLists.txt
- contrib/largeNbDicts/Makefile
- contrib/largeNbDicts/largeNbDicts.c
- programs/Makefile
- programs/benchfn.c
- programs/benchfn.h
- programs/benchzstd.c
- programs/benchzstd.h
- programs/zstdcli.c
- tests/Makefile
- tests/fullbench.c
- tests/paramgrill.c
During experiment, I frequently need to benchmark something.
Up to now, I had to grab `bench.c` and manually modify it so that it fit into the experiment environment.
This patch separates `benchfn.c` from `benchzstd.c`.
`benchfn.c` does no longer drag zstd dependency (it only needs `mem.h`), making it a lot easier to re-use "as is" into any environment.
`benchzstd.c` is a user of `benchfn`, dedicated to zstd compression/decompression speed.
I also used this opportunity to modify `benchfn` API, using structures to replace the long list of parameters required to start benchmarking function. I believe it helps readability.
> Separating benchfn and benchzstd

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_ldm.c
- lib/compress/zstd_ldm.h
- lib/compress/zstdmt_compress.c
- lib/compress/zstdmt_compress.h
- lib/zstd.h
- programs/fileio.c
- programs/fileio.h
- programs/zstd.1.md
- programs/zstdcli.c
- tests/playTests.sh
- tests/zstreamtest.c
- Factor out LDM's hash function for reuse
- Add rsyncable mode to zstdmt and expose it via the advanced API
- Fix `-B`/`--block-size` to actually set the job size
- Add rsyncable tests to `zstreamtest` and `playTests.sh`
Tested by:
```
> cat A.100MB B.100MB C.100MB D.100MB E.100MB | zstd --rsyncable -fo src/file.zst
/*stdin*\            : 48.22%   (524288000 => 252837782 bytes, src/file.zst)
> rsync -rc --stats src devbigvm:/data/users/terrelln/rsync-test
Total bytes sent: 252868779
total size is 252837782  speedup is 1.00
> echo test > test
> cat test A.100MB test B.100MB test C.100MB test D.100MB test E.100MB | zstd --rsyncable -fo src/file.zst
/*stdin*\            : 48.23%   (524288025 => 252838025 bytes, src/unicorn.tar.zst)
> rsync -rc --stats src …
```
> Add rsyncable mode

- lib/common/cpu.h
This fixes a build failure on i386 with gcc-4.2 on Mac OS X 10.6 and earlier:
```
.tmp/cc).co70.s:899:Junk character 13 (
.tmp/cc8Vco70.s:899:Rest of line ignored. 1st junk character valued 112 (p).
.tmp/cc).co70.s:2502:Junk character 13 (
.tmp/cc8Vco70.s:2502:Rest of line ignored. 1st junk character valued 112 (p).
```
Thanks to @rmottola.
> Fix i386 build failure "Junk character 13"

- programs/Makefile
When multiple -arch flags are used, the compiler invokes itself once for
each architecture. Apparently, input on stdin is consumed by the
compilation of the first arch and is no longer available to the
compilation of the second arch, which results in a build failure and the
potentially incorrect determination that a feature is not available. So
write the feature detection source to a file instead of using stdin.
------
To explain the error I saw which this PR fixes:
If I remove the redirection of stderr to /dev/null from the feature detection part of programs/Makefile, I can see that when for example I have `-arch x86_64 -arch i386` in CFLAGS/CXXFLAGS/LDFLAGS, the error is:
```
Undefined symbols for architecture i386:
"_main", referenced from:
implicit entry/start for main executable
ld: …
```
> Fix feature detection with multiple -arch flags

- programs/zstdcli.c
Since zstd is generating files with the ending .zst I corrected the help output.
> fixed a typo

- .circleci/config.yml
- tests/regression/Makefile
- tests/regression/config.c
- tests/regression/config.h
- tests/regression/data.c
- tests/regression/data.h
- tests/regression/levels.h
- tests/regression/method.c
- tests/regression/method.h
- tests/regression/result.c
- tests/regression/result.h
- tests/regression/results.csv
- tests/regression/test.c
The regression tests run nightly or on the `regression`
branch for convenience. The results get uploaded as the
artifacts of the job. If they change, check the diff
printed in the job. If all is well, download the new
results and commit them to the repo.
This code will only run on a UNIX like platform. It
could be made to run on Windows, but I don't think that
it is necessary. It also uses C99.
* data: This module defines the data to run tests on.
It downloads data from a URL into a cache directory,
checks it against a checksum, and unpacks it. It also
provides helpers for accessing the data.
* config: This module defines the configs to run tests
with. A config is a set of API parameters and a set of
CLI flags.
* result: This module is a helper for method that defines
the result type.
* …
> [regression] Add initial regression test framework

- lib/BUCK
I apologize if this diff is incorrect incase I'm missing something but when I tried to buck build the zstd program it failed because it couldn't find the debug headers/code.
This diff does four things:
- This adds a new buck target for the debug code and adds it common
- Fixes a typo in the word deprecated
- Added the `hist.c` file to the compress target
- Adds `zstd.h` as an exported header for the entire library
> Small changes for buck build

- examples/dictionary_compression.c
- examples/dictionary_decompression.c
- examples/multiple_streaming_compression.c
- examples/simple_compression.c
- examples/simple_decompression.c
- examples/streaming_compression.c
- examples/streaming_decompression.c
- examples/utils.h
Below are changes that I have made:
1. Move common functions into a shared header file to avoid code duplication
2. Replace hard coded exit values with enums to improve readability of example code.
> Refactor examples to avoid code duplication

- tests/regression/config.c
- tests/regression/config.h
- tests/regression/data.c
- tests/regression/data.h
- tests/regression/method.c
- tests/regression/results.csv
- tests/regression/test.c
Dictionaries are prebuilt and saved as part of the data object.
The config decides whether or not to use the dictionary if it is
available. Configs that require dictionaries are only run with
data that have dictionaries. The method will skip configs that are
irrelevant, so for example ZSTD_compress() will skip configs with
dictionaries.
I've also trimmed the silesia source to 1MB per file (12 MB total),
and added 500 samples from the github data set with a dictionary.
I've intentionally added an extra line to the `results.csv` to make
the nightly build fail, so that we can see how CircleCI reports it.
Full list of changes:
* Add pre-built dictionaries to the data.
* Add `use_dictionary` and `no_pledged_src_size` flags to the config.
* Add a config using a dictionary for every level.
* Add …
> [regression] Add dictionary support

- Makefile
- lib/Makefile
- programs/Makefile
before applying it.
Detection and application are controlled by variables which can be overridden on command line.
Fixes #1436 (for `termux`)
> check availability of --color=never command on grep and egrep

- lib/decompress/zstd_decompress.c
- tests/fuzzer.c
When we switched `ZSTD_SKIPPABLEHEADERSIZE` to a macro, the places where we do:
MEM_readLE32(ptr) + ZSTD_SKIPPABLEHEADERSIZE
can now overflow `(unsigned)-8` to `0` and we infinite loop. The fix is to make
the variable an `unsigned long long`, so it is always 64-bits. I've also made
the other related variables `unsigned long long` to mitigate similar potential
issues.
Note that this bug never made it into a release, and was only in the dev branch
for a few days.
> [libzstd] Fix infinite loop in decompression

- programs/fileio.c
- programs/fileio.h
- programs/zstd.1.md
- programs/zstdcli.c
- tests/playTests.sh
The `--no-progress` flag disables zstd's progress bars, but leaves
the summary.
I've added simple tests to `playTests.sh` to make sure the parsing
works.
Closes #1371
> [zstdcli] Add --no-progress flag

- lib/common/debug.h
- lib/compress/zstd_opt.c
- programs/benchzstd.c
`btultra2` presumed that providing more accurate statistics to the parser would result in better compression ratio.
While that's generally true, this does not apply when input is very small, since default distribution tables will be used at entropy stage, whatever the real distribution of values.
The optimal parser uses a cheap heuristic to determine this mode : it uses default distribution tables and keep the cost static when `srcSize <= 1024`.
The same heuristic is now used in `btultra2` to disable initial statistics estimation.
This solves the problem of `btultra2` generating worse compression than `btultra` on some small files.
Note that, a proper way would be to selectively determine which symbol will use dynamic tables and which one will use predefined tables, then selectively …
> btultra2 and very small input

- lib/compress/zstd_compress.c
- tests/fuzzer.c
* Fix `ZSTD_estimateCCtxSize()` with negative levels.
* Fix `ZSTD_estimateCStreamSize()` with negative levels.
* Add a unit test to test for this error.
Fixes #1424
> [libzstd] Fix estimate with negative levels

- programs/fileio.c
- tests/playTests.sh
Compare the input and output files by their inode number and
refuse to open the output file if the input file is the same.
This doesn't work when (de)compressing multiple files to a single
file, but that is a very uncommon use case, mostly used for
benchmarking by me.
Fixes #1422.
> [zstdcli] Refuse to overwrite input file

- lib/compress/zstd_compress.c
- lib/compress/zstd_opt.c
- tests/fuzzer.c
The problem was already masked,
due to no longer accepting tiny blocks for statistics.
But in case it could still happen with not-so-tiny blocks,
there is a stricter control which ensures that
nothing was already loaded nor skipped prior to statistics collection.
> fixed ossfuzz 11849

- tests/regression/Makefile
- tests/regression/config.c
- tests/regression/method.c
- tests/regression/results.csv
* Add configs that test multithreading, LDM, and setting explicit
parameters.
* Update the `compress cctx` method to accept `ZSTD_parameters`.
* Compile against the multithreaded `libzstd.a`.
* Update `results.csv` for the new configs.
Unless you think there are more configs/methods I should test, I think
we have a fairly wide set of configs/methods, so I'll pause adding
more for now.
> [regression] Add more configs

- programs/README.md
- programs/zstdcli.c
- tests/playTests.sh
1. Add support for environment variable ZSTD_CLEVEL in CLI, both positive and negative values are allowed.
2. refactor readU32FromChar(...)
3. Add test cases and update documentation.
> Add support for environment variable ZSTD_CLEVEL in CLI

- lib/compress/zstd_compress_internal.h
- lib/dictBuilder/fastcover.c
- programs/fileio.c
- programs/util.c
- programs/util.h
- tests/paramgrill.c
- tests/playTests.sh
- zlibWrapper/Makefile
- zlibWrapper/examples/zwrapbench.c
provides a better error message, consistent with `gzip` one
>  fixed : detection of non-existing file 

- lib/compress/zstd_fast.c
- programs/benchzstd.c
- programs/fileio.c
when dictionary missing during benchmark.
Also : refactored `ZSTD_fillHashTable()`,
just for readability (it does the same thing)
> fixed : better error message

- .travis.yml
- lib/compress/fse_compress.c
move aarch64 test onto xenial environment
seems to calm down the `ld` bug.
fix #1455
> update travis test 

- contrib/adaptive-compression/datagencli.c
- contrib/seekable_format/zstdseek_compress.c
- contrib/seekable_format/zstdseek_decompress.c
- lib/common/bitstream.h
- lib/common/fse.h
- lib/common/huf.h
- lib/compress/fse_compress.c
- lib/compress/huf_compress.c
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_opt.c
- lib/decompress/zstd_decompress.c
- lib/decompress/zstd_decompress_block.c
- lib/dictBuilder/cover.c
- lib/dictBuilder/fastcover.c
- lib/dictBuilder/zdict.c
- lib/legacy/zstd_v05.c
- programs/benchfn.c
- programs/benchzstd.c
- programs/datagen.c
- programs/dibio.c
- programs/fileio.c
- tests/datagencli.c
- tests/decodecorpus.c
- tests/fullbench.c
- tests/fuzzer.c
- tests/paramgrill.c
- tests/seqgen.c
- tests/zstreamtest.c
- zlibWrapper/examples/zwrapbench.c
as suggested in #1441.
generally `U32` and `unsigned` are the same thing,
except when they are not ...
case : 32-bit compilation for MIPS (`uint32_t` == `unsigned long`)
A vast majority of transformations consists in transforming `U32` into `unsigned`.
In rare cases, it's the other way around (typically for internal-only code, such as random seeds).
Among a few issues this patches solves :
- some parameters were declared with type `unsigned` in `*.h`,
but with type `U32` in their implementation in `*.c` .
- some parameters have type `unsigned*`,
but the caller uses a `&U32` reference instead.
For these cases, the fix seems useful.
However, the bulk of changes is about `%u` formatting,
which requires `unsigned` type,
but generally receives `U32` values instead,
often just for brevity …
> fix confusion between unsigned <-> U32

- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_opt.c
they are only used to print debug messages.
Requested in #1386.
> guard functions using floating point for debug mode only

- .travis.yml
It's incorrect to mix targets `all` and `check` with directive `-j`.
They will be built in parallel
and resulting artifacts will fight each other
using different sets of build options (such as `DEBUGLEVEL`).
> fixed tests for minimal decoder builds

- .travis.yml
Currently, "long" and "medium" tests are defined in 2 separate `travis.yml` files,
one hosted in `dev` branch, the other in `master` branch.
This setup is complex,
regularly creates problem when doing merge from `dev` to `master`.
It's also more difficult to follow which tests are part of "medium" or "long",
and it's more difficult for maintenance and evolution, which must be replicated on both sides.
The new script is now unified : it powers both `dev` and `master`.
The correct set of tests is automatically determined from current branch.
The distribution of tests has also been re-balanced between "medium" and "long".
> Unified travis.yml

- build/cmake/CMakeModules/AddZstdCompilationFlags.cmake
When compiling without c++ enabled, some variables are not present.
This is a check enforced in recent Cmake versions.
CMake Error at CMakeModules/AddZstdCompilationFlags.cmake:54 (list):
list sub-command REMOVE_DUPLICATES requires list to be present.
Call Stack (most recent call first):
CMakeLists.txt:53 (ADD_ZSTD_COMPILATION_FLAGS)
> BUG: list sub-command REMOVE_DUPLICATES requires list to be present

- contrib/pzstd/Makefile
Apparently, Options.o cannot be linked in without $(PROGDIR)/util.o
> contrib/pzstd/Makefile: fix build of tests

- build/cmake/CMakeLists.txt
VERSION_LESS_EQUAL is only available to CMake 3.7+. This adds additional
logic to check that CMAKE_MINOR_VERSION is at least 7.
Fixes #1489
> Check CMake minor version support for VERSION_LESS_EQUAL

- zlibWrapper/gzguts.h
This fixes building under FreeBSD with Clang 6.0.1.
> Include unistd.h on unix platforms for explicit function declaration

- programs/fileio.c
- tests/playTests.sh
fseek() doesn't indicate when it moves past the end of a file.
Consequently, if a file is truncated within its last block, the error would't be detected.
This PR adds a test scenario that induces this situation using a small compressed file of only one block in size.
This test is added to tests/playTests.sh
Check is implemented by ensuring that the filehandle position is equal to the filesize upon exit.
> fix --list on truncated files

- .travis.yml
- Makefile
- doc/zstd_manual.html
- examples/multiple_simple_compression.c
- examples/utils.h
updated `clang` tests on travis CI
fixed associated minor conversion warnings in `examples/`
> Conversion warnings

- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstdmt_compress.c
- lib/decompress/zstd_ddict.c
- lib/decompress/zstd_decompress.c
- lib/decompress/zstd_decompress_block.c
- tests/decodecorpus.c
This diff wraps the error handling code in the decompressor so that debug information tracking the source of errors can be logged. This is intended to help diagnose issues with corrupt compressed blobs.
Addresses #1435.
> Add Debug Information to Error Checks

- lib/dictBuilder/zdict.h
* Fix the memory usage comments now that fast cover is the default.
* Instruct users on what to do if dictionary construction fails.
> [zdict] Improve documentation

- programs/util.c
- programs/zstdcli.c
- tests/playTests.sh
In #1520 it is described that FreeBSD doesn't detect symbolic links. The same is true for OpenBSD. This diff fixes this issue for OpenBSD. I'm guessing that something similar works for FreeBSD as well. However, I'm unable to test this.
While working on the above I noticed some inconsistent behaviour:
```
$ echo hello > hello
$ ln -s hello world
$ zstd hello world
Warning : world is a symbolic link, ignoring
hello                :316.67%   (     6 =>     19 bytes, hello.zst
$ ls *.zst
hello.zst
$ zstd world
world                :316.67%   (     6 =>     19 bytes, world.zst)
$ ls *.zst
hello.zst world.zst
```
I'm guessing that the latter is not OpenBSD specific?
> Detection of symbolic links on OpenBSD

- .cirrus.yml
- programs/util.c
* Fix `-Werror` to be passed via `MOREFLAGS`
* Install `coreutils`
* Run `playTests.sh`
* Fix `UTIL_isLink()` for FreeBSD
Fixes #1520.
> [cirrus] Run playTests.sh

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/zstd.h
- tests/regression/config.c
- tests/regression/results.csv
It controls the literals compression. It is either `auto`, `huffman`, or `uncompressed`. It defaults to `auto`, which is the current behavior.
Add a regression test that tests a positive compression level with uncompressed literals, and a negative compression level with compressed literals. I checked the `results.csv` table and made sure that the compressed sizes make sense.
Fixes #1517.
> Add ZSTD_c_literalCompressionMode flag

- lib/compress/zstd_compress.c
- lib/compress/zstdmt_compress.c
- tests/fuzzer.c
- tests/regression/config.c
- tests/regression/results.csv
* Move all ZSTDMT parameter setting code to ZSTD_CCtxParams_*Parameter().
ZSTDMT now calls these functions, so we can keep all the logic in the
same place.
* Make setting `ZSTD_c_nbWorkers` not clear overlap log / job size.
* Clean up `ZSTD_CCtx_setParameter()` to only add extra checks where needed.
* Clean up `ZSTDMT_initJobCCtxParams()` by copying all parameters by default,
and then zeroing the ones that need to be zeroed. We've missed adding several
parameters here, and it makes more sense to only have to update it if you
change something in ZSTDMT.
* Add `ZSTDMT_cParam_clampBounds()` to clamp a parameter into its valid
range. Use this to keep backwards compatibility when setting ZSTDMT parameters,
which clamp into the valid range.
* Add test cases to to cover the `ZSTD_c_nbWorkers` …
> Clean up parameter code

- CHANGELOG
- lib/compress/zstd_compress.c
- lib/compress/zstdmt_compress.c
- lib/zstd.h
- tests/fuzzer.c
- tests/roundTripCrash.c
- tests/zstreamtest.c
* Renames functions to `ZSTD_CCtxParams_*`.
* The CI will test that everything still builds, and that I didn't miss a call-site.
* I've left the `ZSTDMT_` functions alone, since they are only here for compatibility, so it would be silly to rename them. Side question, when do we want to deprecate/delete these?
Fixes #1529.
> [libzstd] Rename ZSTD_CCtxParam_* to ZSTD_CCtxParams_*

- lib/compress/zstd_compress.c
We no longer care about the `cdictLocal` after calling
`ZSTD_CCtx_refCDict()`, so we should free it to save some
memory.
> [libzstd] Free local cdict when referencing cdict

- lib/compress/zstd_compress.c
- lib/zstd.h
- tests/fuzzer.c
- tests/zstreamtest.c
The order you set parameters in the advanced API is not supposed to matter.
However, once you call `ZSTD_CCtx_refCDict()` the compression parameters
cannot be changed. Remove that restriction, and document what parameters
are used when using a CDict.
If the CCtx is in dictionary mode, then the CDict's parameters are used.
If the CCtx is not in dictionary mode, then its requested parameters are
used.
> [libzstd] Allow compression parameters to be set with a cdict

- lib/decompress/zstd_decompress.c
- tests/fuzzer.c
- tests/legacy.c
While reading through the code to implement legacy compatibility, I noticed that `decompressBound` was assigned to the wrong error code in `ZSTD_errorFrameSizeInfo`.
In `ZSTD_decompressBound`, we check if `decompressedBound` equals `ZSTD_CONTENTSIZE_ERROR`, not `ZSTD_CONTENTSIZE_UNKNOWN` [1].
[1] https://github.com/facebook/zstd/blob/dev/lib/decompress/zstd_decompress.c#L545
> Fix incorrect error code in ZSTD_errorFrameSizeInfo

- lib/common/zstd_internal.h
- lib/decompress/zstd_decompress.c
- lib/legacy/zstd_legacy.h
- lib/legacy/zstd_v01.c
- lib/legacy/zstd_v01.h
- lib/legacy/zstd_v02.c
- lib/legacy/zstd_v02.h
- lib/legacy/zstd_v03.c
- lib/legacy/zstd_v03.h
- lib/legacy/zstd_v04.c
- lib/legacy/zstd_v04.h
- lib/legacy/zstd_v05.c
- lib/legacy/zstd_v05.h
- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v06.h
- lib/legacy/zstd_v07.c
- lib/legacy/zstd_v07.h
- lib/zstd.h
- tests/legacy.c
Allows `decompressBound` to handle legacy formatted records.
Implements https://github.com/facebook/zstd/issues/1536.
> Add legacy support to decompressBound

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstdmt_compress.c
- lib/zstd.h
- tests/regression/config.c
- tests/regression/method.c
- tests/regression/results.csv
- tests/zstreamtest.c
Refactor the `ZSTD_initCStream*()` functions and `ZSTD_resetCStream()` to call:
```c
ZSTD_CCtx_reset(cctx, ZSTD_reset_session_only);
// Set the pledged src size if known
// Set parameters
// Set or clear the dictionary
```
This is a small difference in behavior when you mix the two APIs, since the parameters are now sticky.
The biggest advantages of this change are that it reduces the maintenance of the old streaming API, since it is now just a small wrapper, and we can point users to the implementation to help them switch to the new API. We can document these functions in terms of what they do in the new API.
The disadvantages are a small change in behavior, and users will end up mixing the two APIs.
> Refactor old stream API to completely wrap the advanced API

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- tests/fuzzer.c
* After loading a dictionary only create the cdict once we've started the
compression job. This allows the user to pass the dictionary before they
set other settings, and is in line with the rest of the API.
* Don't use the pledged source size when constructing a dictionary, since it may be used for more than once input.
* Add tests that mix the 3 dictionary loading APIs.
* Add extra tests for `ZSTD_CCtx_loadDictionary()`.
* The first 2 tests added fail before this patch.
* Run the regression test suite.
> [lib] Allow ZSTD_CCtx_loadDictionary() to be called before parameters are set

- build/cmake/lib/CMakeLists.txt
> [libzstd] Specify soversion and version corectly for CMake build

- programs/fileio.c
- programs/util.c
- programs/util.h
- tests/playTests.sh
Prevent CLI from compressing a dictionary with itself.
Implements https://github.com/facebook/zstd/issues/1552.
> [CLI] ensure dictionary and input file are different

- lib/dictBuilder/cover.c
- lib/dictBuilder/cover.h
- lib/dictBuilder/fastcover.c
* The algorithm would bail as soon as it found one epoch that
contained no new segments. Change it so it now has to fail
>= 10 times in a row (10 for fastcover, 10-100 for cover).
* The algorithm uses the `maxDict` size to decide the epoch size.
When this size is absurdly large, it causes tiny epochs. Lower
bound the epoch size at 10x the segment size, and warn the user
that their training set is too small.
Fixes #1554
> [cover] Improvements for small or homogeneous data

- lib/zstd.h
- programs/fileio.c
Fix typo in `zstd.h` and add `UTIL_isSameFile` to comment in `fileio.c`.
Simple text change for completeness.
> Update comments in zstd.h and fileio.c

- lib/compress/zstd_fast.c
I'm working on optimizing the fast search algorithm, but it is hard to work with the two functions combined. Each function wants a different optimization.
This patch has no behavior changes, it just splits the two functions out exactly as-is. I will have a second PR that optimizes these functions.
I benchmarked with clang and gcc on my Intel i9 and clang on my Mac on silesia and the GitHub dataset with a dictionary. This change has a neutral to small positive (up to 5 MB/s) performance difference.
> [libzstd] Split out zstd_fast dict match state function

- examples/multiple_streaming_compression.c
Update to use the new streaming API. Making progress on Issue #1548.
Tested that multiple files could be compressed, and that the output
is the same as calling `streaming_compression` multiple times with
the same compression level, and that it can be decompressed.
> [examples] Update multiple_streaming_compression.c

- examples/streaming_memory_usage.c
- lib/compress/zstd_compress.c
- lib/decompress/zstd_decompress.c
- lib/zstd.h
- tests/zstreamtest.c
* Fix `ZSTD_estimateCStreamSize_usingCCtxParams()` and add a test.
* Make setting `ZSTD_d_maxWindowLog` to 0 reset it to the default value.
* Check that the bounds hold in the example.
* Set the maximum allowed window size in the decompressor to allow larger window logs.
* Update to the new API making progress on #1548.
> Update streaming_memory_usage.c and fix ZSTD_estimateCStreamSize_usingCCtxParams()

- lib/compress/zstd_fast.c
This PR is based on top of PR #1563.
The optimization is to process two input pointers per loop.
It is based on ideas from [igzip] level 1, and talking to @gbtucker.
| Platform                | Silesia     | Enwik8 |
|-------------------------|-------------|--------|
| OSX clang-10            | +5.3%       | +5.4%  |
| i9 5 GHz gcc-8          | +6.6%       | +6.6%  |
| i9 5 GHz clang-7        | +8.0%       | +8.0%  |
| Skylake 2.4 GHz gcc-4.8 | +6.3%       | +7.9%  |
| Skylake 2.4 GHz clang-7 | +6.2%       | +7.5%  |
I see small (1-2%) gains on my AMD ThreadRipper with gcc-7.
Testing on all Silesia files on my Intel i9-9900k with gcc-8
| Silesia File | Ratio Change | Speed Change |
|--------------|--------------|--------------|
| silesia.tar  | +0.17%       | +6.6%        |
| dickens …
> [libzstd] Speed up single segment zstd_fast by 5%

- lib/zstd.h
* Bump the library version to 1.4.0
* Move the candidate advanced API to the stable section.
It makes some minor whitespace changes, but it doesn't change any
of the wording of the documentation.
The biggest thing to review in this PR is the order of the functions.
Also, if there are any documentation changes you want to see, let me know.
I'm planning on updating the streaming documentation block to mention
`ZSTD_compressStream2()`.
I'll put up a separate PR that tweaks some of the documentation
once this lands, so that it is easier to review.
NOTE: Even though these functions are now in stable, they aren't
stable until the next release (in under 1 month). It is possible
that they change until then.
> Stabilize the advanced API

- examples/Makefile
- examples/common.h
- examples/dictionary_compression.c
- examples/dictionary_decompression.c
- examples/multiple_simple_compression.c
- examples/multiple_streaming_compression.c
- examples/simple_compression.c
- examples/simple_decompression.c
- examples/streaming_compression.c
- examples/streaming_decompression.c
- examples/streaming_memory_usage.c
- lib/zstd.h
* Fix the return value docs for `ZSTD_compressStream2()` (first commit).
* Stabilize `ZSTD_getDictID_*()` functions, since there is no other way to get the dictionary ID from the dictionary or frame in the stable API (second commit).
* Clean up the examples (third commit):
* Only use the stable API in the examples and remove `ZSTD_STATIC_LINKING_ONLY`. The only exception is `streaming_memory_usage`.
* Rename `utils.h` to `common.h` to reduce confusion with `programs/utils.h`.
* Add some documentation.
* Use `CHECK()` and `CHECK_ZSTD()` everywhere.
* Clean up the includes.
Fixes #1548
> Stabilize ZSTD_getDictID_*() functions and clean up examples

- lib/compress/zstd_compress.c
- lib/decompress/zstd_decompress.c
- lib/dictBuilder/cover.c
- lib/dictBuilder/cover.h
- lib/dictBuilder/fastcover.c
- lib/zstd.h
- tests/fuzz/Makefile
- tests/fuzz/dictionary_decompress.c
- tests/fuzz/dictionary_round_trip.c
- tests/fuzz/fuzz.py
- tests/fuzz/regression_driver.c
- tests/fuzz/simple_round_trip.c
- tests/fuzz/stream_decompress.c
- tests/fuzz/stream_round_trip.c
- tests/fuzz/zstd_helpers.c
- tests/fuzz/zstd_helpers.h
- tests/fuzzer.c
Changes to the zstd library:
* Make `ZSTD_decompressDCtx()` use the loaded dictionary and add a test.
* Fix `ZSTD_compress2()` for multithreaded compression and add a test.
* Make `ZSTD_compressStream2()` with `ZSTD_e_flush` and `ZSTD_end` make maximal forward progress, and update the docs.
* Don't check the dictionary ID when `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` is defined.
* Make the corpus size warning in the dictionary builder respect the current displayLevel.
Changes to the fuzzers:
* Add `dictionary_round_trip` and `dictionary_decompress` fuzzers that generate a dictionary to use using fast-cover based on the input. So this tests using a valid dictionary. The dictionary is used in both prefix mode and zstd mode, and using both the old and new APIs.
* Fuzz with less than …
> Add new fuzzers and fix exposed bugs

- lib/decompress/zstd_decompress.c
- lib/decompress/zstd_decompress_internal.h
- lib/zstd.h
- tests/fuzzer.c
- tests/zstreamtest.c
Bugs:
* `ZSTD_DCtx_refPrefix()` didn't clear the dictionary after the first
use. Fix and add a test case.
* `ZSTD_DCtx_reset()` always cleared the dictionary. Fix and add a test
case.
* After calling `ZSTD_resetDStream()` you could no longer load a
dictionary, since the stage was set to `zdss_loadHeader`. Fix and add
a test case.
Cleanup:
* Make `ZSTD_initDStream*()` and `ZSTD_resetDStream()` wrap the new
advanced API, and add test cases.
* Document the equivalent of these functions in the advanced API and
document the unstable functions as deprecated.
> [libzstd] Fix decompression dictionary bugs and clean up initialization

- .travis.yml
- build/meson/programs/meson.build
- build/meson/tests/meson.build
- tests/zbufftest.c
- tests/zstreamtest.c
I [tried to set Travis notification](https://travis-ci.com/lzutao/zstd/builds/108152136) for meson job only but 
Travis didn't mail me when I tested the build failed.
So could we make mesonbuild non-optional? You could
ping me when meson build failed or just comment out
the `env: ALLOW_FAILURES=true` line.
> Fix tests and meson build

- tests/playTests.sh
The OS X test machine on TravisCI doesn't recognize the parameter
https://travis-ci.org/facebook/zstd/jobs/520517933.
> [playTets] Don't pass status=none to dd

- tests/fullbench.c
We were getting bad speed measurements introduced by 9703a5912173982f9e9f14681f428afe18a4d828. Use the same max as used in `benchfn.c`.
Test by running `fullBench` and making sure we are getting real measurements, not `-10000000000.0 MB/s`.
> [fullbench] Fix speed measurements

- lib/decompress/zstd_decompress.c
- lib/legacy/zstd_legacy.h
- tests/fuzz/Makefile
- tests/fuzz/fuzz.py
- tests/fuzz/zstd_frame_info.c
* Write a fuzzer that fuzzes all the helper functions that take compressed input.
* Found an out-of-bounds read in `ZSTD_decompressBound()`.
* Fix a bug where `ZSTD_findDecompressedSize()` would return a zstd error code if `readSkippableFrameSize()` failed.
> [fuzzer] Fuzz frame info functions

- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
- tests/fuzz/Makefile
- tests/fuzz/dictionary_decompress.c
- tests/fuzz/simple_decompress.c
- tests/paramgrill.c
* Run fuzzers with legacy support.
* Size the decompression output buffer randomly and run 10x with different output sizes to try and catch buffer overruns better.
* Fix a bug in `ZSTDv6_findFrameSizeInfoLegacy()`.
* Fix a bug in `ZSTD_decodeSeqHeaders()`.
> [fuzzer] Run fuzzers in legacy mode and fix legacy code

- lib/legacy/zstd_v01.c
- lib/legacy/zstd_v05.c
* We would read the jump table before checking the source size.
* The v05 bug was caught by the `simple_decompress` fuzzer now that we are running with legacy support enabled.
* The v01 bug was caught by manual inspection.
* All the other legacy versions seem to check the header correctly.
> [legacy] Fix Huffman jump table reads in v01 and v05

- lib/legacy/zstd_v01.c
- lib/legacy/zstd_v02.c
- lib/legacy/zstd_v03.c
- lib/legacy/zstd_v04.c
- lib/legacy/zstd_v05.c
* Version <= 0.5 could read beyond the end of `dumps`, which points into
the input buffer.
* Check the validity of `dumps` before using it, if it is out of bounds
return garbage values. There is no return code for this function.
* Introduce `MEM_readLE24()` for simplicity, since I don't want to trust
that there is an extra byte after `dumps`.
> [legacy] Fix ZSTDv0*_decodeSequence()

- programs/fileio.c
Add a static function `LONG_TELL` for the forth `#if` branch
It looks like the only way to invoke the edited code is through the `--list` option of the cli.
I tested it on a Windows 7 machine, for both small and large(3 GiB) files, and they worked as expected.
> Fix #1591 - Not building on MinGW-W64

- examples/Makefile
fixes "make test" fail in example directory
````
$ make test
...
! ./simple_decompression tmp.zst   # unknown input size, must fail
tmp.zst :    617 ->    1891 
tmp.zst correctly decoded (in memory). 
make: *** [Makefile:80: test] Error 1
````
> fails to "make test" in examples

- programs/zstdcli.c
- tests/playTests.sh
Since [#1520](https://github.com/facebook/zstd/issues/1520) has been merged, commands like zstdcat properly detect symbolic links on Linux. But the consequence is that they output nothing when executed on a symbolic link. According to the manual, zstdcat includes -f, which should follow symbolic links. This is also how most *cat commands like zcat behave.
Please comment and I would be glad if you could consider this request for merging into master. Thanks.
Charles
> Make zstdcat to follow symbolic links

- .travis.yml
- build/meson/meson.build
* Update to use ninja v1.9.0 on CI
> meson: Update default project version

- .travis.yml
- build/meson/meson.build
- build/meson/tests/meson.build
- tests/playTests.sh
This PR:
* tests: Fix shellcheck warnings in playTests.sh
* tests: Do not use ../programs which is relative to tests dirs
* tests: Replace relative paths for zstd/tests dir
* Set shell options explicitly, not in shebang
* playTests: Replace echo -e with printf
* meson: Fix test-zstd
* meson: Fix legacy test
* meson: Enable testing in CI
One advantage of running meson test on CI is that tests are run
parallel by default. So test time is faster than running test with make.
Closes #1605
> meson: Enable testing in CI

- tests/poolTests.c
* Count the number of concurrent threads instead of timing
* Remove a deadlock from bad usage of `ZSTD_pthread_cond_wait()`, since the signal could've happened before we started waiting, so we would wait forever.
The test is now consistently passing for me.
> [test] Fix poolTests deadlock and flakiness

- programs/fileio.c
uClibc does not support BACKTRACE. It also defines __GLIBC__ and minor as both 2.
This fixes compilation under such a setup.
Example: https://downloads.openwrt.org/snapshots/faillogs/arc_arc700/packages/zstd/compile.txt
> fileio: Disable BACKTRACE under uClibc

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_lazy.c
- lib/compress/zstd_opt.c
`nextToUpdate3` is re-synchronized with `nextToUpdate` at beginning of each block.
It only needs to be tracked from within `ZSTD_compressBlock_opt()`.
Made the logic clear, by removing `nextToUpdate3` from `ZSTD_window`,
so that no code tries to maintain this variable.
> nextToUpdate3 does not need to be maintained outside of zstd_opt.c

- lib/compress/zstd_compress.c
- lib/compress/zstd_opt.c
- tests/fullbench.c
- tests/fuzzer.c
`fullbench` can now benchmark speed on sample of any size, thanks to `-B#` command.
new : scenario 43, streaming compression with a new context allocated and freed every time, and initialization not knowing source size (`ZSTD_CONTENTSIZE_UNKNOWN`).
> fullbench minor improvements

- programs/fileio.c
Moved the logic to measure elapsed time and cpu load from FIO_compressFilename to FIO_compressFilename_internal.
1. FIO_compressFilename is only used for single file case. If we want to show elapsed time and cpu load for each file in multiple file scenario, the measurement needs to be done in FIO_compressFilename_internal, which is called by both single and multiple file scenarios. 
2. I could have added the logic to FIO_compressFilename_internal, FIO_compressFilename_dstFile, or FIO_compressFilename_srcFile. I thought FIO_compressFilename_internal is a good fit since it already has logic to print stats about compression (compression ratio). I see elapsed time and cpu load as the extension to the stats.
> zstdcli : expose cpu load indicator for each file on -vv mode

- .circleci/config.yml
- .circleci/images/primary/Dockerfile
Instead of installing dependencies before test, use custom Docker Image with pre-installed dependencies.
> CircleCI : use custom Docker Image with pre-installed dependencies

- lib/compress/zstd_opt.c
- tests/regression/results.csv
We would only skip at most 192 bytes at a time before this diff.
This was added to optimize long matches and skip the middle of the
match. However, it doesn't handle the case of repetitive data.
This patch keeps the optimization, but also handles repetitive data
by taking the max of the two return values.
**Before:**
```
> for n in $(seq 9); do echo strategy=$n; dd status=none if=/dev/zero bs=1024k count=1000 | command time -f %U zstd --zstd=strategy=$n >/dev/null; done
strategy=1
0.34
strategy=2
0.36
strategy=3
0.41
strategy=4
0.93
strategy=5
1.33
strategy=6
8.41
strategy=7
31.03
strategy=8
31.13
strategy=9
123.05
```
**After:**
```
> for n in $(seq 9); do echo strategy=$n; dd status=none if=/dev/zero bs=1024k count=1000 | command time -f %U ./zstd --zstd=strategy=$n >/dev/null; done …
```
> [libzstd] Optimize ZSTD_insertBt1() for repetitive data

- build/cmake/lib/CMakeLists.txt
Hi,
I'm using add_subdirectory to include zstd in my project.  Another library that I'm using also creates a custom target called uninstall.
This change checks that the uninstall target doesn't exist before it creates it.
> CMake: Check for existing custom target 'uninstall'

- tests/playTests.sh
These options require ZSTD_MULTITHREAD.
> Skip --adapt and --rsyncable tests when built without thread support

- programs/fileio.c
This resolves a race condition where zstd or unzstd may expose read
permissions beyond the original file allowed.  Mode 600 is used
temporarily during the compression and decompression write stage
and the new file inherits the original file’s mode at the end.
Fixes #1630
chmod() should silently fail in situations where it isn't possible to set mode 600, such as on FAT file systems. I'm also not really able to tell if this builds okay on Windows. mingw-w64 seems to build it fine (as long as I changed timefn.h to have `<windows.h>` instead of `<Windows.h>`), but i don't know if chmod() has any effect on that OS -- it's well possible that someone should make a Windows-specific equivalent to this.
> [programs] set chmod 600 after opening destination file

- build/VS2010/libzstd/libzstd.vcxproj
As a principle, static libs should not dllexport methods; that should only be used when building DLLs.
Case in point: when static libs with dllexport directives are linked into DLLs created with a .def file, the VC++ compiler exports the dllexported methods into the DLL, in addition to the exports listed in the .def file. This will result in undesired link dependencies and is not the correct thing to do.
I've also cleaned up the vcxproj a bit by consolidating duplication.
> Remove ZSTD_DLL_EXPORT=1 for static lib

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_double_fast.c
- lib/compress/zstd_fast.c
- lib/compress/zstd_lazy.c
- lib/compress/zstd_opt.c
To ensure that all detected matches remain within window size, 
the current strategy is to preemptively invalidate all indexes 
that could end up being too far while compressing next block.
This is good for speed, as checking if a match is within distance is now a trivial comparison.
This roughly invalidates one block worth of data, which is about 128 KB. 
It's then progressively restored as compression progress through the block. But temporarily, the window size has been truncated by up to 128 KB.
This is bad for compression ratio, but the impact is low, as long as the window size is large, relative to the block size.
As the window size is reduced, this is no longer the case.
Especially when `wlog <= 17`, the window size is now equal to the block size. Hence, this strategy invalidates …
> Improves compression ratio for small windowLog

- build/cmake/programs/CMakeLists.txt
CMake bug fix: CMake didn't install zstdless and zstdgrep.
I mess up the last PR[#1625](https://github.com/facebook/zstd/pull/1625) and create a new PR here.
Really sorry about this. @felixhandte
> CMake bug fix: didn't install zstdless and zstdgrep.

- build/cmake/CMakeModules/FindLibLZ4.cmake
- build/cmake/README.md
- build/cmake/programs/CMakeLists.txt
Add some instructions in build/cmake/README.md for guys not familiar with cmake. Show them how to build with options
Yes, I saw there is a cmake support, but it can be improved using a CMakeLists.txt file and have a flag for each thing we want to build or not.
Add lz4 format support for zstd program, with a new cmake module FindLibLZ4.cmake added to find lz4 library.
This has been test on:
suse12sp2 cmake 3.12.1 lz4 1.8.3
windows10 cmake 3.12.1 lz4 1.8.3
ubuntu12.04 cmake 3.0.2 lz4 1.8.3
centos7.4 cmake 2.8.12 lz4 1.8.3
redhat7.2 cmake 3.0.2 lz4 1.8.3
with tests like:
lz4 compressed file->zstd decompress file->diff files
zstd compressed file->lz4 decompress file->diff files
[Issue#715](https://github.com/facebook/zstd/issues/715)
I rebased my last pull request and restart a new pull …
> add cmake lz4 support

- lib/compress/zstd_compress.c
- lib/compress/zstd_opt.c
- lib/compress/zstdmt_compress.c
- tests/Makefile
- tests/bigdict.c
* Extract the overflow correction into a helper function.
* Load the dictionary `ZSTD_CHUNKSIZE_MAX = 512 MB` bytes at a time
and overflow correct between each chunk.
* Add a test case that made overflow asserts fail, and now passes.
I couldn't figure out how to make a fast test that causes data corruption.
Data corruption could happen when all these conditions are true:
* You are using multithreading mode
* Your overlap size is >= 512 MB (implies window size >= 512 MB)
* You are using a strategy >= ZSTD_btlazy
* You are compressing more than 4 GB
The problem is that when loading a large dictionary we don't do
overflow correction. We can only load 512 MB at a time, and may
need to do overflow correction before each chunk.
Fixes https://github.com/facebook/zstd/issues/1653.
> Fix data corruption in niche use case

- .travis.yml
- build/meson/README.md
- build/meson/contrib/gen_html/meson.build
- build/meson/meson.build
- build/meson/meson_options.txt
Meson now reserves the `build_` prefix for options.
> meson: Fix deprecated build warnings on build options

- .circleci/config.yml
- .circleci/images/primary/Dockerfile
Decoder was enforcing a constraint that is more strict than the spec. Sequence section for a compressed block can be less than the constraint that was enforced by decoder. When a block with rle mode for all (literal length, match length, and offset) is followed by another block with repeat mode for all (literal length, match length, and offset), the second block's sequence section can be 2 bytes (1 byte for number of sequences and 1 byte for compression mode for each field). 
This pull request includes 2 changes. 
1. fixing the decoder code to remove the constraint. 
2. Updating decodecorpus code to generate repeat after rle mode. 
Run `./decodecorpus -ptestfiles -otestfiles -n1 -s1236947365 -v` to generate an input that has an issue before the fix.
> decodecorpus 

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstdmt_compress.c
- programs/benchfn.c
I recently received a user performance report stating that `reduceIndex()` can require a non-negligible delay to perform its job, especially when applied to a large context.
`reduceIndex()` is required in 2 scenarios : 
- when compressing a large data stream, typically > 4 GB
- when reusing a context for a lot of smaller data streams, and using the `continue` mode as a consequence of constantly keeping the same parameters.
For the first case, there's nothing new.
For the second case, the issue is that `reduceIndex()` is a measurable load compared to a single compression job. User reported delay in the ~80ms range. I could find similar delay on my laptop with `llvm` in the 20-30ms range when using large tables (~30 MB). User results are exacerbated by the use of Visual Studio, which is …
> memset() rather than reduceIndex()

- lib/compress/zstd_compress.c
When we wrote one byte beyond the end of the buffer for RLE
blocks back in 1.3.7, we would then have `op > oend`. That is
a problem when we use `oend - op` for the size of the destination
buffer, and allows further writes beyond the end of the buffer for
the rest of the function. Lets assert that it doesn't happen.
> ZSTD_compressSequences_internal assert op <= oend

- tests/fuzz/Makefile
- tests/fuzz/fuzz.py
- tests/fuzz/simple_compress.c
We were missing coverage of compression with a too-small output buffer.
This fuzzer catches the bug fixed by https://github.com/facebook/zstd/pull/1404 (with the fix removed) in an hour or two of CPU time. The same bug took the unguided `fuzzer.c` fuzzer months or years of CPU time to find.
> [fuzz] Add a compression fuzzer with randomly sized output buffer

- doc/zstd_manual.html
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/zstd.h
- programs/fileio.c
- programs/fileio.h
- programs/zstdcli.c
This pull request only adds targetCBlockSize as an advanced parameter for ZSTD compression. At the moment changing its value won't have any impact on compression. The implementation of super block compression will follow as a separate PR.
> Adding targetCBlockSize param

- .gitignore
- build/.gitignore
- programs/.gitignore
- tests/.gitignore
- zlibWrapper/.gitignore
Some files are ignored by some .gitignore rules. These files should be exclude from gitignore
Ignored files:
`build/VS2008/zstd/`
`build/VS2010/zstd/`
`build/cmake/lib/`
`build/meson/lib/`
`contrib/VS2005/zstd/`
`examples/dictionary_compression.c`
`examples/dictionary_decompression.c`
`mygittestproject.zip`
`programs/windres/generate_res.bat`
`tests/fuzz/dictionary_decompress.c`
`tests/fuzz/dictionary_round_trip.c`
`tests/gzip/hufts-segv.gz`
`zlibWrapper/examples/example.c`
`zlibWrapper/examples/fitblk.c`
`zlibWrapper/examples/zwrapbench.c`
> fix gitignore errors

- lib/compress/zstd_compress.c
Factor out the logic to build sequence store. ZSTD_buildSeqStore() will be used by ZSTD_compress_superBlock in the following PR.
> Factor out the logic to build sequences

- lib/Makefile
- lib/common/compiler.h
- lib/common/zstd_internal.h
- lib/compress/zstd_compress_internal.h
- lib/decompress/zstd_decompress_block.c
tldr: 7.5% average decode speedup on silesia corpus at compression levels 1-3 (sandy bridge)
Background: while investigating zstd perf differences between clang and gcc I noticed that even though gcc is vectorizing the loop in in wildcopy, it was not being done as well as could be done by hand.  The sites where wildcopy is invoked have an interesting distribution of lengths to be copied.  The loop trip count is rarely above 1, yet long copies are common enough to make their performance important.The code in zstd_decompress.c to invoke wildcopy handles the latter well but the gcc autovectorizer introduces a needlessly expensive startup check for vectorization.
See how GCC autovectorizes the loop here:
https://godbolt.org/z/apr0x0
Here is the code after this diff has been applied: (left …
> perf improvements for zstd decode

- lib/compress/zstd_ldm.c
- lib/compress/zstdmt_compress.c
- lib/compress/zstdmt_compress.h
- tests/playTests.sh
`src` is the wrong pointer here. When the job size is 2GB the second job does overflow correction, but `src - base == 2 GB` for every chunk. When we do overflow correction we get `current & cycleLog + maxDist == 2 GB & 2^26 + 2 GB == 2 GB`, meaning we effectively never do overflow correction that job. Then the next job we overflow, and things go terribly wrong.
Instead, we need to pass the beginning of the current chunk, which is only 1 MB large and is well under the maximum chunk size of 512 MB.
There are asserts that failed before this change, and don't fail after, but I accidentally defined the wrong macro during the build for my initial tests.
The test I added to `playTests.sh` has assertion failures and produces corrupted data before this change. The test I added to `zstreamtest.c` …
> [ldm] Fix bug in overflow correction with large job size

- .gitignore
- lib/compress/zstd_double_fast.c
in a way which is more favorable to compression ratio, though slightly slower.
Detailed benchmark :
core i7-9700k (disabled turboboost), Ubuntu x64 19.04, `gcc` v8.3.0 : 
| filename | `dev` ratio | this patch | improv | c.speed | d.speed |
| --- | --- | --- | --- | --- | --- |
| silesia.tar | 3.173 | 3.188 | +0.47% |  -1.9% | +0.28% |
| calgary.tar | 3.075 | 3.098  | +0.75% | -1.5% | +0.60% |
| dickens | 2.767 | 2.789 | +0.79% | -2.2% | +1.13% |
| mozilla | 2.767 | 2.768 | +0.04% | -2.5% | +0.02% |
| xml | 8.364 | 8.407 | +0.51% | -2.1% | +0.01% |
| book2 | 2.976 | 3.008 | +1.08 % | -1.5% | +0.00% |
| progc | 2.785 | 2.804 | +0.68% | -2.6% | +0.32% |
| enwik8 | 2.806 | 2.826 | +0.71% | -1.5% | +0.80% |
Note : I must re-run speed tests, as it seems there is enough difference between cores …
> updated double_fast complementary insertion

- tests/regression/results.csv
Results look positive across the board. There are a few cases where it gets ~10 bytes worse, but that is noise.
> [regression] Update results for ZSTD_double_fast update

- doc/zstd_compression_format.md
This changes the size limit on compressed blocks to match those of the other
block types: they may not be larger than the `Block_Maximum_Decompressed_Size`,
which is the smaller of the `Window_Size` and 128 KB, removing the additional
restriction that had been placed on `Compressed_Block`s, that they be smaller
than the decompressed content they represent.
Several things motivate removing this restriction. On the one hand, this
restriction is not useful for decoders: the decoder must nonetheless be
prepared to accept compressed blocks that are the full
`Block_Maximum_Decompressed_Size`. And on the other, this bound is actually
artificially limiting. If block representations were entirely independent,
a compressed representation of a block that is larger than the contents of the
block …
> [doc] Remove Limitation that Compressed Block is Smaller than Uncompressed Content

- lib/decompress/zstd_decompress.c
- tests/decodecorpus.c
Adding check if block size exceeds maximum.
Tested by creating a frame with a fake frame with raw block of size approximately 500 kb, and verifying the output:
> Add Check if Block Size Exceeds Maximum

- contrib/seekable_format/examples/Makefile
- contrib/seekable_format/examples/seekable_decompression_mem.c
- contrib/seekable_format/zstdseek_decompress.c
Issue noticed in #395 by @P-E-Meunier.  I guess I never wrote examples using the in-memory API, oops.  New example tests the in-memory api:
```
$ ./seekable_compression dickens 131072
$ ./seekable_decompression dickens.zst 2000000 2001000 | shasum
8cfd22487cd222b8756d824fa3c4419ab6c722a3  -
$ ./seekable_decompression_mem dickens.zst 2000000 2001000 | shasum
8cfd22487cd222b8756d824fa3c4419ab6c722a3  -
```
Same test without the patch to `zstdseek_decompress.c`:
```
$ ./seekable_decompression_mem dickens.zst 2000000 2001000 | shasum
ZSTD_seekable_init() error : An I/O error occurred when reading/seeking 
da39a3ee5e6b4b0d3255bfef95601890afd80709  -
```
> Fix seekable decompression in-memory api

- contrib/largeNbDicts/largeNbDicts.c
- programs/zstdcli.c
Compiling with clang-8 fails with the following errors:
largeNbDicts.c:562:37: error: implicit conversion turns floating-point
number into integer: 'const double' to 'U64' (aka 'unsigned long')
[-Werror,-Wfloat-conversion]
U64 const dTime_ns = result.nanoSecPerRun;
~~~~~~~~   ~~~~~~~^~~~~~~~~~~~~
zstdcli.c:300:5: error: '@return' command used in a comment that is
not attached to a function or method declaration
[-Werror,-Wdocumentation]
* @return 1 means that cover parameters were correct
~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
zstdcli.c:301:5: error: '@return' command used in a comment that is
not attached to a function or method declaration
[-Werror,-Wdocumentation]
* @return 0 in case of malformed parameters
~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> fix compiling errors with clang-8

- CHANGELOG
- doc/zstd_manual.html
- lib/zstd.h
In preparation for a new release, rev the version number and update the CHANGELOG.
> Bump Library Version Number to 1.4.2

- contrib/seekable_format/examples/.gitignore
Trivial PR to reflect the existence of a new binary in
`contrib/seekable_format/examples/`.
> Add New Seekable Compression Example to .gitignore

- programs/util.c
Pointer `path` points to a memory which is malloced in the `while` loop, but it's not freed before `continue`
> memory leak fix

- doc/zstd_manual.html
- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_double_fast.c
- lib/compress/zstd_fast.c
- lib/compress/zstd_lazy.c
- lib/compress/zstd_opt.c
- lib/decompress/zstd_decompress.c
- lib/decompress/zstd_decompress_block.c
- lib/zstd.h
- programs/datagen.c
- tests/fuzzer.c
Fix compression ratio inefficiency 
introduced in #1624
under following scenario :
- dictionary compression
- at levels 1 to 3
- with medium size payloads (larger than `attachDict` threshold)
The patch restore compression ratio to previous level.
A new compression efficiency test is added into `fuzzer/unitTests` in order to control gross negative variations in compression ratio, playing all levels with normal compression and flat dictionary compression.
> Fix compression ratio inefficiency 

- programs/util.c
I believe the original code was meant to deal with case that `/proc/cpuinfo` has come across a error: the formatting of `/proc/cpuinfo` was broken. In that way, the `sep` could also be `NULL` because it's the return of `strchr`.
I think adding a `NULL` check is better here.
> add NULL pointer check in util.c

- CHANGELOG
- lib/legacy/zstd_v03.c
The DCtx has a 128KB literals buffer. When a block's literals are raw-encoded, we were not checking the literal section length before copying then into that buffer. This could result in a buffer overflow.
> Fix Buffer Overflow in Legacy (v0.3) Raw Literals Decompression

- lib/common/compiler.h
Noticed and fixed by Warner Losh <imp@FreeBSD.org>.
> Fix the build on GCC 4.x after 812e8f2a1

- lib/compress/zstd_compress.c
The nbSeq "short" format (1-byte)
is compatible with any value < 128.
However, the code would cautiously only accept values < 127.
This is not an error, because the general 2-bytes format
is also compatible with small values < 128.
Hence the 1-byte inefficiency remained invisible.
Spotted by Intel's Smita Kumar.
> fixed very minor inefficiency (nbSeq==127)

- tests/fuzz/Makefile
- tests/fuzz/README.md
- tests/fuzz/fuzz.py
* Remove the `make libFuzzer` target since it is broken and obsoleted
by `CC=clang CXX=clang++ ./fuzz.py build all --enable-fuzzer`. The
new `-fsanitize=fuzzer` is much better because it works with MSAN
by default.
* Improve the `./fuzz.py gen` command by making the input type explicit
when creating a new target.
* Update the `README` for `--enable-fuzzer`.
Fixes #1727.
> [fuzz] Improve fuzzer build script and docs

- lib/legacy/zstd_v02.c
- lib/legacy/zstd_v04.c
Extends the fix in PR#1722 to v0.2 and v0.4. These aren't built into
zstd by default, and v0.5 onward are not affected.
I only add the `srcSize > BLOCKSIZE` check to v0.4 because the comments
say that it must hold, but the equivalent comment isn't present in v0.2.
Credit to OSS-Fuzz.
> [legacy] Fix buffer overflow in v0.2 and v0.4 raw literals decompression

- programs/fileio.c
- programs/fileio.h
- programs/zstd.1.md
- programs/zstdcli.c
- tests/playTests.sh
Certain streaming situations can result in significantly different compression ratios between a file and stdin (streaming the same file). This is mainly an issue for smaller source sizes, where the default compression parameters are not appropriate.
This diff adds a `--stream-size` option, which allows the user to specify the exact size of the incoming stream. Note that this specified size _must_ be the exact size of the stream, or else zstd will fail with `error 11`.
Tests have been added for comparing the compression ratio of a small file and streaming that small file, requiring that the difference is less than 0.05%.
Resolves #1720.
> Add --stream-size=# option

- tests/fuzz/fuzz_helpers.h
- tests/fuzz/regression_driver.c
Enable it by building with this command:
```
./fuzz.py build all --debug 3
```
> [fuzz] Add a DEBUGLOG(3) statement to print file

- doc/zstd_manual.html
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/zstd.h
- programs/fileio.c
- programs/fileio.h
- programs/zstd.1.md
- programs/zstdcli.c
- tests/fuzz/zstd_helpers.c
- tests/playTests.sh
- tests/zstreamtest.c
Certain streaming situations can result in significantly different compression ratios between a file and stdin (streaming the same file). This is mainly an issue for smaller source sizes, where the default compression parameters are not appropriate.
This diff adds an experimental --size-hint option, which allows the user to specify the approximate size of a source stream. The hint does not need to be exactly the same size as the incoming stream. 
The following are outputs from a few different play tests with hints that are not exact:
```
/*stdin*\         : 21.79%   ( 11000 =>   2397 bytes, tmp.zst)   # 50 bytes too big
/*stdin*\         : 21.79%   ( 11000 =>   2397 bytes, tmp.zst)   # 50 bytes too small
/*stdin*\         : 21.85%   ( 11000 =>   2403 bytes, tmp.zst)   # twice actual …
```
> Add --size-hint=# option

- contrib/declib/examples/simple.c
- contrib/declib/zstddeclib-in.c
Tested with GCC4.2, GCC7.4 and Clang 3.3.
> C99 and older GCC fixes

- examples/streaming_compression.c
- examples/streaming_decompression.c
* Handle compression of empty file
* Error in decompression in case of trailing data
> Fix streaming compression/decompression examples

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstdmt_compress.c
Static analyzer reported issue of performance inefficiency due to big parameter passed by value (`ZSTD_CCtx_params`).
Size of the parameter is reported as 144 bytes on 64-bit, thus passing by const pointer saves 136 bytes on the stack on each function call and potentially provides a small performance boost due to avoided copy.
> Passing ZSTD_CCtx_params by const pointer

- tests/fuzz/Makefile
- tests/fuzz/README.md
- tests/fuzz/fuzz_data_producer.c
- tests/fuzz/fuzz_data_producer.h
- tests/fuzz/simple_decompress.c
Addressing the fuzz data generation by following the lz4 approach of reading data from the end to generate parameters, instead of only hashing the first few bytes and relying on the hash to be the seed.
Only changing one test in this PR to make sure it's the right way to do it. I've tested locally and the test passes.
> [Fuzz] Improve data generation #1723

- Makefile
- doc/educational_decoder/Makefile
- doc/educational_decoder/harness.c
- doc/educational_decoder/zstd_decompress.c
- doc/educational_decoder/zstd_decompress.h
- lib/dictBuilder/cover.c
fix #1774
also :
- fix minor compilation warnings
- fix dictionary decompression test
- make sure `test` is run during CI tests
> fix educational decoder

- lib/common/mem.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_cwksp.h
- tests/fuzzer.c
This changeset builds on the work in #1712, and uses the new workspace abstraction introduced in that PR to perform more efficient context resets, even when the compression parameters change.
Overall this PR should produce compression speed wins for repeated compressions on contexts where the parameters vary (whether because the compression level changes, or the size of the input changes), and be otherwise perf neutral. The gains are very situational, and range from 0% to 4%. There are also outsize wins that this PR brings from fixing existing pathological cases, like constantly switching compression levels on streaming compression of small responses without a pledged src size, which range up 40x improvements.
> Avoid Clearing Tables Even When Changing CParams

- lib/common/zstd_internal.h
- lib/compress/zstd_compress_internal.h
- lib/decompress/zstd_decompress_block.c
Summary: The idea behind wildcopy is that it can be cheaper to copy more bytes (say 8) than it is to copy less (say, 3).  This change takes that further by exploiting some properties:
1. it's almost always OK to copy 16 bytes instead of 8, which means fewer copy instructions, and fewer branches
2. A 16 byte chunk size means that ~90% of wildcopy invocations will have a trip count of 1, so branch prediction will be improved.
Speedup on Xeon E5-2680v4 is in the range of 3-5%.
Measured wildcopy length distributions on silesia.tar:
```
level	<=8	<=16	<=24	>24
1	78.05%	11.49%	3.52%	6.94%
3	82.14%	8.99%	2.44%	6.43%
6	85.81%	6.51%	2.92%	4.76%
8	83.02%	7.31%	3.64%	6.03%
10	84.13%	6.67%	3.29%	5.91%
15	77.58%	7.55%	5.21%	9.66%
16	80.07%	7.20%	3.98%	8.75%
```
Test Plan: benchmark silesia, make check
> Improvements in zstd decode performance

- lib/zstd.h
- tests/fuzzer.c
I assumed this would cover the streaming buffers.
> Update Comment on `ZSTD_estimateCCtxSize()`

- lib/common/compiler.h
- lib/common/zstd_internal.h
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_double_fast.c
- lib/compress/zstd_fast.c
- lib/compress/zstd_lazy.c
- lib/compress/zstd_ldm.c
- lib/compress/zstd_opt.c
- lib/decompress/zstd_decompress_block.c
- tests/decodecorpus.c
* Bump `WILDCOPY_OVERLENGTH` to 32 to fix the wildcopy overread introduced in #1756.
* Optimize `ZSTD_wildcopy()` by removing unnecessary branches, unrolling the loop, and bumping to a 32 byte copy in stripes of 16.
* Extract `ZSTD_overlapCopy8()` into its own function.
* Add `ZSTD_safecopy()` for `ZSTD_execSequenceEnd()`. It is
optimized for single long sequences, since that is the important
case that can end up in `ZSTD_execSequenceEnd()`. Without this
optimization, decompressing a block with 1 long match goes
from 5.7 GB/s to 800 MB/s.
* Refactor `ZSTD_execSequenceEnd()`.
* Increase the literal copy shortcut to 16.
* Add a shortcut for offset >= 16.
* Simplify `ZSTD_execSequence()` by pushing more cases into
`ZSTD_execSequenceEnd()`.
* Delete `ZSTD_execSequenceLong()` since it is …
> Optimize (de)compression and fix wildcopy overread

- lib/common/bitstream.h
- lib/common/zstd_internal.h
- lib/legacy/zstd_v01.c
- lib/legacy/zstd_v02.c
- lib/legacy/zstd_v03.c
- lib/legacy/zstd_v04.c
- lib/legacy/zstd_v05.c
- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
GCC is unable to simplify '31 - __builtin_clz(val)' and produces ugly assembly. Clang can simplify it.
Use alternative expr "__builtin_clz(val) ^ 31" which is optimized well by Clang and GCC too.
Proof: https://godbolt.org/z/y32jQq
> Improve ZSTD_highbit32's codegen

- build/cmake/lib/CMakeLists.txt
- build/cmake/programs/CMakeLists.txt
Use paths provided by GNUInstallDirs module instead.
> Don't hardcode installation directories in CMakeLists.txt

- doc/zstd_manual.html
- lib/common/zstd_internal.h
- programs/benchzstd.c
- programs/benchzstd.h
which is no longer used,
noticed by @davidbolvansky in #1807
> removed wildcopy8() 

- doc/zstd_manual.html
- lib/compress/zstd_compress.c
- lib/zstd.h
- tests/fuzzer.c
instead of current names `ZSTD_dct_*`,
reported by @nigeltao (#1822)
> updated erroneous comments using ZSTD_dm_*

- tests/fuzz/stream_round_trip.c
> [fuzz] Increase output buffer size of stream_round_trip

- lib/common/mem.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_cwksp.h
- lib/compress/zstd_ldm.c
Adds 8-byte spaces on either side of allocations into the workspace (which requires touching all of the places we calculate the size of the workspace), and poisons them when we run under ASAN. This allows us to verify that accesses into the individual objects in the workspace don't bleed over into each other.
This means removing any assumptions made in the rest of the codebase concerning contiguity of objects, which I kind of view as a side benefit...
Note that we do not put redzones around the table allocations, because that memory region is complicated... We depend on the contiguity of the tables to know that the compressor is maintaining the invariants around the values in the [objectEnd, tableEnd) range, while the workspace is responsible for the [tableEnd, tableValidEnd) range.
> Add Poisoned Redzones to the Workspace When Compiling with ASAN

- lib/common/pool.c
- lib/common/threading.c
- lib/common/threading.h
- lib/compress/zstdmt_compress.c
- tests/poolTests.c
* Clear everything in the `jobDescription` except the `job_mutex` and `job_cond`.
* Add a debug implementation of `threading.h` that would've caught this class of bug.
* See [CircleCI failure](https://circleci.com/gh/terrelln/zstd/1727?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) before the fix.
* See [Travis failure](https://travis-ci.org/terrelln/zstd/builds/599822721?utm_source=github_status&utm_medium=notification) before the fix.
Fixes #1830.
> [zstdmt] Don't memset the jobDescription

- lib/decompress/zstd_decompress.c
- lib/zstd.h
- programs/fileio.c
- tests/fullbench.c
- tests/fuzzer.c
- zlibWrapper/zstd_zlibwrapper.c
* Fix `ZSTD_FRAMEHEADERSIZE_PREFIX` and `ZSTD_FRAMEHEADERSIZE_MIN` to
take a `format` parameter, so it is impossible to get the wrong size.
* Fix the places that called `ZSTD_FRAMEHEADERSIZE_PREFIX` without
taking the format into account, which is now impossible by design.
* Call `ZSTD_frameHeaderSize_internal()` with `dctx->format`.
* The added tests catch both bugs in `ZSTD_decompressFrame()`.
Fixes #1813.
> Fix ZSTD_f_zstd1_magicless for small data

- programs/zstd.1
- programs/zstd.1.md
- programs/zstdcli.c
- tests/playTests.sh
which is a preferred construction for long options when applicable.
Also, added `--output-dir-flat` entry into man page.
> Added --output-dir-flat=

- lib/compress/zstd_compress.c
- tests/fullbench.c
Compression ratio of ` initCStream_advanced()` when using fast strategies (levels 1 & 2)
was seriously reduced, due to accidental disabling of Literals compression.
Credit to @QrczakMK, which perfectly described the issue, and implementation details,
making the fix straightforward.
Example : initCStream with level 1 on synthetic sample P50 :
```
Before : 5,273,976 bytes
After  : 3,154,678 bytes
ZSTD_compress (for comparison) : 3,154,550
```
Fix #1787.
To follow : refactor the test which was supposed to catch this issue (and failed)
> fix initCStream_advanced() for fast strategies

- tests/regression/method.c
- tests/regression/results.csv
* A copy-paste error made it so we weren't running the advanced/cdict
streaming tests with the old API.
* Clean up the old streaming tests to skip incompatible configs.
* Update `results.csv`.
The tests now catch the bug in #1787.
> [regression] Fix the old streaming regression test

- lib/deprecated/zbuff.h
- tests/Makefile
- tests/zbufftest.c
in order to display a deprecation message with `gcc` >= v4.5.0
(as opposed to >= v5.0).
although, curiously enough, I was never able to reproduce the issue
where the compiler is supposed to complain about a missing deprecation message
(according to the bug report, it should be present while using gcc 4.8).
fix #1488
> improve deprecation warning macro

- zlibWrapper/gzread.c
Fix #1800
As per https://github.com/facebook/zstd/issues/1800#issuecomment-545945050,
Visual does not support `ssize_t` type,
which is an issue for `gzread.c`.
Added a work around, suggested by @bluenlive
Note : I have not been able to confirm the problem,
so this is a blind fix.
This seems safe outside of Visual, since it is gated by `_MSC_VER` macro.
> fix zlibWrapper for Visual Studio

- build/cmake/lib/CMakeLists.txt
- lib/Makefile
- lib/libzstd.pc.in
Addresses #1794. Instead of deriving the lib dir and include dir at build-time, let's do it like everyone else does at pkg-config run-time. This has the disadvantage that we can no longer override LIBDIR and INCLUDEDIR in the Makefile and have that reflected in the .pc file.
Tested with make and cmake to produce what appear to be correct files:
```
prefix=/usr/local
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib
Name: zstd
Description: fast lossless compression algorithm library
URL: http://www.zstd.net/
Version: 1.4.4
Libs: -L${libdir} -lzstd
Cflags: -I${includedir}
```
> In pkg-config File, Derive Lib and Include Dir from Prefix at Use-Time

- lib/decompress/zstd_decompress_block.c
In the case that `op >= oend_w` it is possible that `diff < 8` because
the two buffers could be adjacent.
Credit to OSS-Fuzz, which found the bug. It isn't reproducible because
it depends on the memory layout.
> Fix assert in ZSTD_safecopy

- programs/fileio.c
- programs/fileio.h
- programs/util.c
- programs/util.h
- programs/zstdcli.c
- tests/playTests.sh
Introducing a "--exclude-compressed" that skips compression of pre-compressed input files. Addressing Issue#1579.
> Added "--exclude-compressed" flag feature

- lib/compress/zstd_compress.c
Probably better to be defensive about this change. If pledgedSrcSize is unknown, we use the old CDict behavior.
> Disable reloading dictionary when there is no known srcSize

- lib/compress/zstd_compress.c
- lib/decompress/zstd_decompress.c
- tests/fuzz/Makefile
- tests/fuzz/dictionary_loader.c
- tests/fuzz/fuzz.py
* Silently skip dictionaries less than 8 bytes, unless using `ZSTD_dct_fullDict`.
This changes the compressor, which silently skips dictionaries <= 8 bytes.
* Allow repcodes that are equal to the dictionary content size, since it is in bounds.
Adds the `dictionary_loader` fuzzer to test the patch.
* The fuzzer found the repcode bug (original bug) without any help.
* Additionally, it found the 8 byte dictionary bug.
> Fix 2 bugs in dictionary loading

- lib/compress/zstd_compress.c
- lib/decompress/zstd_decompress.c
- tests/fuzz/Makefile
- tests/fuzz/dictionary_loader.c
- tests/fuzz/fuzz.py
- zlibWrapper/Makefile
> fix dictionary edge case

- tests/playTests.sh
date(1) is used to display the last modification time of a file, which is not supported on OpenBSD, FreeBSD and Darwin. Instead use stat(1).
Tested on OpenBSD.
> 'date -r FILE' is non-portable.

- lib/compress/zstd_compress.c
This parameter is unused in single-threaded compression. We should make it behave like the other multithread-only parameters, for which we only accept zero when we are not built with multithreading.
> Fix #1861: Restrict overlapLog Parameter When Not Built With Multithreading

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstdmt_compress.c
- tests/fuzzer.c
* Make `_internal()` versions of functions `ZSTD_getCParams()` and `ZSTD_getParams()` that don't translate 0 to unknown.
* Call the `_internal()` versions internally.
* Clean up the logic in `ZSTD_getCParams_internal()`.
* Make `ZSTD_getCParamsfromCCtxParams()` treat 0 as 0 and switch callers to `ZSTD_CONTENTSIZE_UNKNOWN`.
* Add a test for the issue in #1863 to `fuzzer.c`.
* Run the regression test suite to make sure we didn't regress anything obvious.
Fixes https://github.com/facebook/zstd/issues/1863.
> Fix parameter selection and adjustment with srcSize == 0

- Makefile
- zlibWrapper/Makefile
[c89 and c90 are the same language](https://en.wikipedia.org/wiki/ANSI_C#C90). Old compilers like gcc 4.2.1 don't know the c90 alias.
See https://trac.macports.org/ticket/59620
> Change c90 to c89

- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/decompress/zstd_decompress_internal.h
- lib/dictBuilder/zdict.c
- lib/dictBuilder/zdict.h
- tests/fuzzer.c
For #1715 
Tested locally and validated that the sizes come out as expected.
Main hurdle is that getting the size of the dict header can only come from the functions that "copy" the dictionary entropy tables into a CCtx or DCtx, and output the size as a side effect. So, I guess there are a couple of ways to do this.
1. It looks like "\x01\x00\x00\x00\x04\x00\x00\x00\x08\x00\x00\x00" is hardcoded into the end of the entropy tables as of now. We could just search for this, but it doesn't seem like this will always be the case.
2. Borrow some of the logic the logic currently existing in `ZSTD_loadZstdDictionary()` in `zstd_compress.c` and/or `ZSTD_loadDEntropy()` in `zstd_decompress.c` and re-write an dict header/entropy-table parsing function that focuses purely on getting the size (so …
> Method to get dictionary header size

- lib/compress/zstd_compress.c
- tests/fuzzer.c
Modifies the existing RLE test to compress into two RLE blocks instead of one, and now we also check that there is no significant size regression (arbitrarily set to 10% of 39 bytes) as a proxy for testing that the blocks were indeed compressed with RLE (without RLE it would compress to 47 bytes).
Curiously, the existing test for RLE would compress to the same size regardless of whether RLE blocks were enabled.
Also validated that previous patch will fail this test.
> RLE test and re-enable RLE in main compression loop

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_double_fast.c
- lib/compress/zstd_lazy.c
- lib/compress/zstdmt_compress.c
- lib/decompress/zstd_decompress.c
- tests/fuzzer.c
- tests/zstreamtest.c
* Extract window initialization into `ZSTD_window_init()`
* Add `ZSTD_CCtx::initialized` so we always reset the indices the first time. This wasn't happening for static contexts.
* Fix various null pointer arithmetic.
* Add some more unit tests, to ensure coverage.
Fixes #1899.
> Fix null pointer addition

- programs/util.c
There must be mtim*e*
Error popup if I use gcc-4.4 and build under Ubuntu 10.04.
And in arm builds up to Ubuntu 14.04.
Probably there must be more clever check for attributes of stat_t structure.
> WIP: Fix typo in util.c

- lib/common/bitstream.h
- lib/common/compiler.h
- lib/decompress/huf_decompress.c
- lib/decompress/zstd_decompress_block.c
Silesia level 1
| Compiler | Before | After | Gain |
|---|---|---|---|
| gcc-9.2 | 1192.7 MB/s | 1256.7 MB/s | +5.3% |
| clang-9.0.0 | 1083 MB/s | 1203.2 MB/s | +11.1% |
enwik8 level 1
| Compiler | Before | After | Gain |
|---|---|---|---|
| gcc-9.2 | 1035.6 MB/s | 1103.8 MB/s | +6.5% |
| clang-9.0.0 | 923.2 MB/s | 1044.8 MB/s | +13.1% |
enwik8 level 22 (`ZSTD_decompressSequencesLong()`)
| Compiler | Before | After | Gain |
|---|---|---|---|
| gcc-9.2 | 739.2 MB/s | 781.2 MB/s | +5.6% |
| clang-9.0.0 | 694.5 MB/s | 746.3 MB/s | +7.5% |
Streaming decompression of enwik8 and silesia at level 1: `zstd -t enwik8.zst silesia.tar.zst`
| Compiler | Before | After | Gain |
|---|---|---|---|
| gcc-9.2 | 927.3 MB/s | 970.3 MB/s | +4.6%|
| clang-9.0.0 | 847.1 MB/s | 935.5 MB/s | +10.4% |
Measured …
> Decompression speed optimizations

- programs/util.c
- programs/zstdcli.c
- tests/playTests.sh
This would resize the table of input filenames to zero,
delivering an empty table, which was reduced to `NULL`,
and to which it was no longer possible to add `stdin`.
Now, always return a list with at least `1` capacity,
even if empty.
> fix recent issue combining -r with empty list of input files

- programs/zstdcli.c
- tests/playTests.sh
displaying into `stderr` or `stdout` is now an explicit operation.
I was bothered by this "hidden contract", making the rest of the unit (slightly) more difficult to anticipate.
Case in point : `initCLevel()` would not work during initialization, 
it was necessary to wait first for `g_displayOut` initialization,
since the function may output an error message in case of incorrect environment variable.
But `g_displayOut` could not be initialized at compile time, since `stderr` is not considered a constant.
Doing it nonetheless would result in undefined behavior at runtime, with no prior compilation warning.
As a rule of thumb, removing secret contracts is generally a good improvement for code maintenance.
Also : fix a slight discrepancy between `-V` and `--version`.
> small refactoring : remove global variable g_displayOut

- contrib/diagnose_corruption/.gitignore
- contrib/diagnose_corruption/Makefile
- contrib/diagnose_corruption/check_flipped_bits.c
I spend an increasing amount of my time looking at "Corrupted block detected" failures in decompression. Not infrequently, I suspect that it is the result of hardware failure, and that the blob has become bit-flipped or otherwise corrupted somewhere along the line.
For that reason I was motivated to write a little tool to inspect blobs that fail to decompress, to try modifying them, and then check whether they decompress successfully. This seems like potentially a generally useful tool, so I figured it might be worth putting in `contrib/`.
> Add Tool to Diagnose Whether Corrupt Blobs are Plausibly Bit-Flips

- build/cmake/lib/CMakeLists.txt
- build/cmake/lib/config.cmake.in
> Make idiomatic cmake install so third party cmake installers work right.

- .gitignore
- .travis.yml
on real hardware.
Note : the PPC64LE test is only run on `master` and `cron` jobs, 
so it's not visible as part of this PR's tests.
But it was successfully run previously on [this instance](https://travis-ci.org/facebook/zstd/jobs/625177515?utm_medium=notification&utm_source=github_status).
> added ppc64le tests on travis

- lib/compress/zstd_compress.c
- tests/fuzzer.c
noCompress superblocks are larger than the original data because of the addition of a block header and epilogue per block. If we add enough of these during streaming compression, we're going to run out of room and throw a dstSize_tooSmall error. To prevent that I just branch to regular compression when we might run out of room. 
Credit to oss-fuzz
> [fuzz] Adding bool to check if there is enough room to emit noCompress Superblocks

- tests/Makefile
- tests/playTests.sh
`playTests.sh` needs to distinguish the `qemu` invocation from the path to the `zstd` binary, so it can construct symlinks and invoke `zstd` through those symlinks.
> Fix playTests.sh to Work under QEMU

- .travis.yml
- programs/platform.h
- programs/util.c
- tests/Makefile
- tests/playTests.sh
Let's try this again. Changes:
1. I believe checking `defined(_WIN32)` is redundant with checking the POSIX version. So I've removed that.
2. I flipped the order, we should do the preferred behavior first and the fallback next.
3. I added a check for whether `st_mtime` is defined. When `st_mtim` replaced `st_mtime`, `st_mtime` became a macro that expanded to `st_mtim.tv_sec` for backwards compatibility. Since we have found examples where the platform advertising POSIX 2008 still doesn't have `st_mtim`, this additional check should be defensive. The only concern is whether there are platforms that have `st_mtim` but not the `st_mtime` macro. I don't believe that there should be: the `st_mtime` macro is also part of POSIX 2008 (although we've seen where that gets us...). At any rate, …
> Use statbuf->st_mtim Again

- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- tests/fuzzer.c
I added this check last week because noCompress blocks in streaming mode were eating up all of dstCapacity when superblock was enabled. I used blockSize to determine the number of blocks that would fit inside srcSize and dstCapacity when I should have used targetCBlockSize. 
Also added some debug statements. Currently running libFuzzer on this locally
> [fuzz] Dividing by targetCBlockSize instead of blockSize for nbBlocks fit

- programs/util.c
Cygwin currently uses the fallback implementation which just returns 1 every time,
which leads to bad performance when zstd is called with -T0 for example.
Instead use the POSIX implementation used for the BSDs which works just fine under Cygwin.
Tested under Cygwin and MSYS2.
Before:
```
$ zstd -f -vv -T0 -c mingw-w64-x86_64-python3-3.8.0-1-any.pkg.tar -o mingw-w64-x86_64-python3-3.8.0-1-any.pkg.tar.zst
*** zstd command line interface 64-bits v1.4.4, by Yann Collet ***
Note: 1 physical core(s) detected
```
After:
```
$ zstd -f -vv -T0 -c mingw-w64-x86_64-python3-3.8.0-1-any.pkg.tar -o mingw-w64-x86_64-python3-3.8.0-1-any.pkg.tar.zst
*** zstd command line interface 64-bits v1.4.4, by Yann Collet ***
Note: 16 physical core(s) detected
```
> Make UTIL_countPhysicalCores() work under Cygwin

- tests/fuzz/regression_driver.c
The `numFiles` variable wasn't updated, so the fuzzer only tested one input in the directory. I did two things to fix this:
1. Remove the `numFiles` variable entirely.
2. Error if we can't open a file and print the number of files tested.
> [fuzz] Fix regression_driver.c with directory input

- lib/decompress/zstd_decompress.c
This was exposed when running another project's tests that use zstd with UBSAN instrumentation.
> fix UBSAN's invalid-null-argument error in zstd_decompress.c

- lib/compress/zstdmt_compress.c
- lib/legacy/zstd_v04.c
- lib/legacy/zstd_v05.c
- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
- tests/fuzz/stream_decompress.c
- tests/fuzz/stream_round_trip.c
* Allow zero sized buffers in `stream_decompress`. Ensure that we never have two
zero sized buffers in a row so we guarantee forwards progress.
* Make case 4 in `stream_round_trip` do a zero sized buffers call followed by
a full call to guarantee forwards progress.
* Fix `limitCopy()` in legacy decoders.
* Fix memcpy in `zstdmt_compress.c`.
Catches the bug fixed in PR #1939
> [fuzz] Allow zero sized buffers for streaming fuzzers

- programs/fileio.c
- programs/fileio.h
- programs/zstd.1.md
- programs/zstdcli.c
- tests/playTests.sh
* Add new cli endpoint --diff-from 
* Overrides 32 MB dict limit with --memory=# when using --diff-from
* Ensures that windowSize > srcSize on compression using --diff-from
https://github.com/facebook/zstd/issues/1935
> Adding new cli endpoint --patch-from=

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_superblock.c
- lib/compress/zstd_compress_superblock.h
- lib/decompress/zstd_decompress.c
- tests/zstreamtest.c
Super blocks must never violate the zstd block bound of input_size + ZSTD_blockHeaderSize. The individual sub-blocks may, but not the super block. If the superblock violates the block bound we are liable to violate `ZSTD_compressBound()`, which we must not do. Whenever the super block violates the block bound we instead emit an uncompressed block.
This means we increase the latency because of the single uncompressed block. I fix this by enabling streaming an uncompressed block, so the latency of an uncompressed block is 1 byte. This doesn't reduce the latency of the buffer-less API, but I don't think we really care.
* I added a test case that verifies that the decompression has 1 byte latency.
* I rely on existing zstreamtest / fuzzer / libfuzzer regression tests for correctness. During …
> Fix super block compression and stream raw blocks in decompression

- appveyor.yml
- programs/platform.h
When building zst under cygwin or msys2 with std=c99 the build would fail because
of an undefined fileno()/_fileno(), which is used by the IS_CONSOLE() macro.
When building with -std=c99 (gcc otherwise defaults to gnu, which implies POSIX),
which is the default of the cmake build, then including unistd.h wont define
_POSIX_VERSION and all other headers also wont expose POSIX API.
To fix this make sure to define _POSIX_C_SOURCE with the version we want before including
unistd.h and so that _POSIX_VERSION is set to the version provided by the system.
Since Cygwin/MSYS2 just follow POSIX we can also remove their special cases for
defining IS_CONSOLE().
And, for completeness, also explicitly include stdio.h which is what actually declares fileno().
Tested with the normal make file and cmake …
> Fix the c99/cmake build under Cygwin/MSYS2

- .travis.yml
- Makefile
- appveyor.yml
- build/cmake/CMakeLists.txt
- build/cmake/CMakeModules/AddZstdCompilationFlags.cmake
- build/cmake/tests/CMakeLists.txt
- programs/util.c
- tests/Makefile
- tests/fuzzer.c
- tests/playTests.sh
* Pass `datagen` as a variable to `playTests.sh` so we can use the one that cmake builds
* Add a cmake test that runs `playTests.sh`
* Run the cmake tests on Appveyor and Travis
* Build cmake tests in debug mode
* Set `DEBUGLEVEL=1` in debug mode
* Fix problem with `readLineFromFile()` on Cygwin
Closes #1949
> [cmake] Add playTests.sh as a test

- programs/zstdcli.c
It's already present in the man page, just missing from the help command.
> Add --single-thread to zstd --help

- lib/compress/zstd_compress_internal.h
- tests/playTests.sh
After PR #1624 we no longer updated `lowLimit` every block. That means `lowLimit` only gets updated when the round buffer overlaps in single threaded mode, or when we start a new job in multithreaded mode. After that change (and maybe before too), `lowLimit` can underflow. If `lowLimit` underflows, then for the remainder of compression all matches are deemed out of bounds, so compression ratio plummets.
This fixes the problem by ensuring `lowLimit` never underflows. We set `lowLimit` and `dictLimit` to 1 instead, and ensure that we aren't invalidating any of the window.
I've modified two tests in `playTests.sh` to trigger overflow correction. Currently they don't because after PR #1658 we clear the context instead of overflow correction if we are starting within 16 MB of the correction …
> Fix lowLimit underflow in overflow correction

- programs/timefn.c
- programs/timefn.h
Android doesn't provide `timespec_get()`.
> Fix timefn on android

- lib/decompress/huf_decompress.c
- lib/decompress/zstd_decompress_block.c
This patch fixes a performance regression on aarch64 phones compiled with clang.
* Only keep the special clang ordering of Huffman decompression on x86_64 and i386. It is neutral on armv7 and negative on aarch64.
* Add a `LIKELY()` to the `endSignal` computation. There isn't a good reason for it other than clang on aarch64 needs it, and it doesn't hurt anyone else.
* Add `HINT_INLINE` to `ZSTD_overlapCopy8()`. Without it `-Oz` will outline this function.
I've tested the performance of `./zstd -b1e1 enwik6` on the following devices.
Machine name | CPU | Clang version | Gcc version | Test command
-- | -- | -- | -- | --
Nexus 4 | 1.5 GHz quad-core Krait | 9.0.8 (ndk-r21) | N/A | ./zstd
Galaxy S6 | Quad-core 2.1 GHz Cortex-A57 + Quad-core 1.5 GHz Cortex-A53 | 9.0.8 (ndk-r21) | N/A | ./zstd …
> Fix performance regression on aarch64 with clang

- lib/decompress/zstd_decompress.c
- lib/decompress/zstd_decompress_block.c
Move it so that `zstd_decompress_block.c` doesn't depend on `zstd_decompress.c`. This allows us to move `zstd_decompress_block.c` into its own target in our mobile buck build, so we can compile it with `-Os`.
> Move ZSTD_checkContinuity() to zstd_decompress_block.c

- tests/Makefile
- tests/README.md
- tests/automated_benchmarking.py
* Make the cli arguments optional
* Add early check for files count (bail when len(filenames == 0)
* Add --dict argument (when set, this will use the first half of the file as a dictionary for the second half)
Example: 
Benchmark using the first half of silesia files as the dict for the second half and compare the current hash to facebook:dev
```
python automated_benchmarking.py --mode current --dict True --dir ~/silesia
```
> [automated_benchmarking] Make arguments optional and add --dict argument

- lib/compress/zstd_compress.c
EDIT: 
This PR doesn't change compression behavior, it is necessary for enabling ldm with dictionaries because resetCCtx changes ldm params
> Using appliedParams instead of "supplied" params in compressBegin()

- programs/zstdcli.c
As per @Cyan4973's request. The end user isn't expected to know the mapping from compression level to compression strategy so I'm went ahead and included level in the display as well.
> Displaying level in --show-default-cparams

- programs/Makefile
https://github.com/facebook/zstd/issues/1983
```
../make-4.3/install/bin/make
...
==> building with threading support
==> building zstd with .gz compression support
==> building zstd with .xz/.lzma compression support
==> no liblz4, building zstd without .lz4 support 
...
```
> [build-issue] More portable header prefix usage (#)

- .github/workflows/main.yml
See PR #1992. I've been unable to test it on my repo, see https://github.com/terrelln/zstd/pull/2. It looks like it only works with the `facebook/zstd` repo, not `terrelln/zstd`, but I verified it still outputs a pass. So we can merge this without it failing any of our PRs, and we can see how it works.
> Enable oss-fuzz CIFuzz dogfood

- programs/zstdcli.c
`readU32FromCharChecked()` currently fails for numbers within the nearest multiple of 10 of the limit for 32-bit unsigned ints:
```
$ zstd -M4294967295
error: numeric value too large
```
This breaks e.g. [lesspipe](https://github.com/wofr06/lesspipe). As unsigned integer 'overflow' is well-defined behaviour in C, we can safely just let it happen and check afterwards.
> Fix integer parsing in cli

- CONTRIBUTING.md
Our documentation for contributing to zstd was subpar. I'm adding some notes on setting up CI for a new user and an outline for how to contribute.
Workflow. This is simply how I've been contributing so far. Some feedback for this would be great! 
https://github.com/bimbashrestha/zstd/blob/042b28bd2c1b4c0e76f6c97ec9661324fd7b72b2/CONTRIBUTING.md#workflow
CI: 
https://github.com/bimbashrestha/zstd/blob/042b28bd2c1b4c0e76f6c97ec9661324fd7b72b2/CONTRIBUTING.md#setting-up-continuous-integration-ci-on-your-fork
Issue: https://github.com/facebook/zstd/issues/1990
> [doc] Adding notes about CI and an outline of collaboration workflow

- programs/Makefile
PR #1987 forgot to prefix another include causing lz4 detection to fail.
> Fix forgotten portable header prefix

- .github/workflows/main.yml
Applies #2004 and turns off dry-run mode. If spurious failures pop up, I will turn dry-run mode back on.
> Update CIFuzz file and turn off dry-run mode

- build/cmake/lib/CMakeLists.txt
- lib/Makefile
- lib/libzstd.pc.in
Revises #1851. Fixes #1900. Replaces #1930.
Thanks to @orbea, @neheb, @Polynomial-C, and particularly @eli-schwartz for pointing out the problem and suggesting solutions.
Tested with
```
make -C lib clean libzstd.pc
cat lib/libzstd.pc
make -C lib clean libzstd.pc     LIBDIR=/foo
make -C lib clean libzstd.pc INCLUDEDIR=/foo
make -C lib clean libzstd.pc     LIBDIR=/usr/localfoo
make -C lib clean libzstd.pc INCLUDEDIR=/usr/localfoo
make -C lib clean libzstd.pc     LIBDIR=/usr/local/lib     prefix=/foo
make -C lib clean libzstd.pc INCLUDEDIR=/usr/local/include prefix=/foo
make -C lib clean libzstd.pc     LIBDIR=/usr/local/foo
make -C lib clean libzstd.pc INCLUDEDIR=/usr/local/foo
make -C lib clean libzstd.pc     LIBDIR=/usr/local/
make -C lib clean libzstd.pc INCLUDEDIR=/usr/local/
make -C …
```
> Fix pkg-config File Generation Again

- build/cmake/lib/CMakeLists.txt
- lib/Makefile
- lib/libzstd.pc.in
Reverts #2001. Looks like it's broken on OS X. I'm going to take a different approach (probably in python to avoid cross-platform shell brittleness).
Addresses #2015.
> Revert "Fix pkg-config File Generation Again"

- programs/zstdgrep
- tests/playTests.sh
Don't pass `-fq` to `zstdcat` because it is already implied. This allows errors to be logged to `stderr` and fixes #2020.
> [zstdgrep] Log zstd decompression errors to stderr

- Makefile
- lib/Makefile
- programs/Makefile
appveyorCI has been updated to add an installation test
which fails without this patch.
It should pass with it.
> test installation with MSYS2+mingw-w64

- lib/compress/zstd_opt.c
The pricing of `opt[0].price` doesn't matter at all for the parsing, since every path contains `opt[0]`. I've left the `litlen` price in so we don't get negative prices when we subtract it off.
I don't expect more than any real gains, except maybe on a specifically constructed dataset, but no need to do the extra work.
> [opt] Don't recompute initial literals price

- lib/common/compiler.h
Removes warning on icc
```
decompress/zstd_decompress_block.c(1119): warning #3175: unrecognized gcc optimization level
DONT_VECTORIZE
^
```
> Removing no-tree-vectorize for intel

- programs/fileio.c
- programs/fileio.h
- programs/zstd.1.md
- programs/zstdcli.c
- tests/playTests.sh
https://github.com/facebook/zstd/issues/1926
Ran 
```
#!/bin/bash
while true
do
echo "line" >> /tmp/log.txt
done
```
and
```
./zstd --compress --no-content-size --stdout /tmp/log.txt > /tmp/log.txt.zst
```
> Adding --no-content-size to the cli

- lib/common/bitstream.h
- lib/common/zstd_internal.h
- lib/compress/zstd_compress_internal.h
https://github.com/facebook/zstd/issues/1951
I've managed to reproduce this error on my windows vm, visual 2019 with: 
```
#include <iostream>
#include <cassert>
using namespace std;
int main()
{
unsigned long index = 0;
_BitScanReverse64(&index, 0x0ull);
cout << index << endl;
assert(index == 0);
return 0;
}
```
Silesia entire file benchmarks: 
| level | zstd-clang (before) | zstd-clang (after)  | zstd-gcc (before) | zstd-gcc (after) |
|-------|---------------------|---------------------|-------------------|------------------|
| 1     | 440 mb/s            | 440 mb/s (-)        | 454 mb/s          | 454 mb/s (-)     |
| 2     | 334 mb/s            | 337 mb/s (-)        | 334 mb/s          | 336 mb/s (-)     |
| 3     | 239 mb/s            | 243 mb/s (+1%)      | 241 mb/s          | 242 …
> _BitScan{Reverse,Forward} add check for undefined

- lib/compress/zstd_fast.c
I generally saw a 2-3% gain in level 1 compression speed and didn't notice any regressions. Adding `#pragma ivdep` (which forces vectorization) seems to add another 1-2% to this but because intel says it isn't safe, I don't think we should include it.
Silesia benchmarks: 
|         | gcc       | icc (before) | icc (after) | Improvement |
|---------|-----------|--------------|-------------|-------------|
| dickens | 301 mb/s  | 271 mb/s     | 274 mb/s    | +1.1%       |
| mozilla | 443 mb/s  | 388 mb/s     | 396 mb/s    | +2.0%       |
| mr      | 396 mb/s  | 360 mb/s     | 366 mb/s    | +1.6%       |
| nci     | 874 mb/s  | 793 mb/s     | 792 mb/s    |  -          |
| ooffice | 352 mb/s  | 309 mb/s     | 321 mb/s    | +3.8%       |
| osdb    | 421 mb/s  | 378 mb/s     | 383 mb/s    | …
> [opt] Small icc level 1 compression speed gain using #pragma vector 

- programs/zstd.1.md
https://github.com/facebook/zstd/pull/2010
Credit to @eyherabh for finding this naming inconsistency
> [doc] targetLen -> targetLength

- contrib/match_finders/README.md
- contrib/match_finders/zstd_edist.c
- contrib/match_finders/zstd_edist.h
Turned out to not provide enough utility to make up for the additional CPU usage. Including this in contrib with some light docs in case this becomes interesting again. 
The one place where this outperforms zstd-19 for compression ratio consistently is when compressing a small file (<10KB) with a small and similar in content dictionary (a use case which doesn't really exist as far as I can tell). There are very few overlapping matches in those cases so edit distance basically does as good of a job as can be done. 
For large files, this is 5-10X slower than zstd-19  and 2-3X worse in terms of compression ratio. I Think most of the loss is in being unable to find overlapping matches. 
References: 
An O(ND) Difference Algorithm and Its Variations: 
http://www.xmailserver.org/diff2.pdf
An …
> [contrib] Edit distance match finder

- lib/compress/zstd_opt.c
* Only update repcodes upon arrival
* Use the repcodes in `opt[cur]` for the next chunk instead of recomputing them
Measurements with gcc-9.2.1 and clang-9.0.1 on enwik7.
| Level | Compiler | Before | After |
|---|---|---|---|
| 16 | gcc | 4.70 MB/s | 4.71 MB/s |
| 16 | clang | 4.63 MB/s | 4.74 MB/s |
| 19 | gcc | 2.60 MB/s | 2.69 MB/s |
| 19 | clang |2.58 MB/s | 2.60 MB/s |
I expect this to be more important in two cases:
1. There are lots of match candidates. Like level 19 enwik7.
2. We're running at a faster speed.
> [opt] Update repcodes less often

- lib/decompress/zstd_decompress_block.c
The alignment is added before the loop, so this shouldn't hurt
performance in any case. The only way it hurts is if there is already
performance instability, and we force it to be stable but in the bad
case.
This consistently gets us into the good case with gcc-{7,8,9} on an
Intel i9-9900K and clang-9. gcc-5 is 5% worse than its best case but has
stable performance. We get consistently good behavior on my Macbook Pro
compiled with both clang and gcc-8. It ends up in the 50% from DSB and
50% from MITE case, but the performance is the same as the 85% DSB case,
so thats fine.
> Align decompress sequences loop to 32+16 bytes

- tests/playTests.sh
playTests.sh didn't work when `ZSTD_BIN` or `DATAGEN_BIN` had a space in
the path name. This happens for me because I split the cmake build
directory by compiler name, like "Clang 9.0.0".
The fix is to replace all instances of `$ZSTD` with the `zstd()`
function, and the replace `$DATAGEN` with `datagen()`. This will allow
us to change how we call zstd/datagen in the future without having to
change every callsite.
Note: I changed some tmp file suffixes from `.zstd` to `.zst` because they got messed up with my find and replace.
> [test] Fix playTests.sh with space in binary path

- lib/decompress/huf_decompress.c
Spotted on iOS/Clang when building with the default `-Wshorten-64-to-32` (since `__builtin_expect` returns a `long`).
> Fixes decompressor when using -Wshorten-64-to-32

- lib/common/zstd_internal.h
- lib/compress/zstd_cwksp.h
- lib/decompress/zstd_decompress.c
- lib/decompress/zstd_decompress_internal.h
- tests/fuzzer.c
https://github.com/facebook/zstd/issues/2066
> [memory opt] Downsize decompression buffers when large for too long

- lib/compress/zstd_compress.c
- tests/fuzz/dictionary_round_trip.c
Adding refPrefix to our dictionary_round_trip fuzzer caused it to crash on 
https://github.com/facebook/zstd/blob/dde98d833db693020130996de4750e8052dfcc1c/lib/compress/zstd_compress.c#L3003-L3007
handling null case on refPrefix advanced like in loadDictionary.  I'll rebase the patch-from pr on top of this after it lands.
> [bug] handling case where prefix is NULL or 0 sized in refPrefix_advanced 

- lib/common/compiler.h
- lib/compress/zstd_double_fast.c
- lib/compress/zstd_fast.c
**Optimize compression by adding prefetch**
Average gains	gcc9.2.0 clang9.0.0
level 1~2	3.10%	 3.69%
level 3~4	2.49%	 1.51%
**Test environment**
1)	Measured with lzbench, transplanting the code of Zstd’s develop branch. 
2)	The testfile is silesia.tar.
3)	The test environment is as follows:
aarch64
Cpu name			Armv8-a
CPU(s):				128
Memory Device			DDR4 2666 MT/s 32 GB
Number Of Memory Devices	16
> Optimize by prefetching on aarch64

- programs/fileio.c
- tests/fullbench.c
Made a few minor improvements to `fileio.c` :
- fix or clarify a few comments
- reorder some parameters, to enforce "mutable references first" rule
- simplified `fwriteSparse()`
> minor refactor of `fileio.c`

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_ldm.c
- lib/compress/zstd_ldm.h
- lib/compress/zstdmt_compress.c
- programs/fileio.c
- programs/zstd.1.md
- programs/zstdcli.c
- tests/fuzz/dictionary_decompress.c
- tests/fuzz/dictionary_loader.c
- tests/fuzz/dictionary_round_trip.c
- tests/fuzzer.c
- tests/playTests.sh
**Patch From**
Zstandard is introducing a new command line option —patch-from= which leverages our existing compressors, dictionaries and the long range match finder to deliver a high speed engine for producing and applying patches to files.
Patch from increases the previous maximum limit for dictionaries from 32 MB to 4 GB. Additionally, it maintains fast speeds on lower compression levels without compromising patch size by using the long range match finder (now extended to find dictionary matches). By default, Zstandard uses a heuristic based on file size and internal compression parameters to determine when to activate long mode but it can also be manually specified as before. 
Patch from also works with multi-threading mode at a minimal compression ratio cost loss single threaded …
> Adding --long support for --patch-from

- programs/fileio.c
https://github.com/facebook/zstd/issues/2081
```
[Optimal parser notes] Consider the following to improve patch size at the cost of speed:
- Use --single-thread mode in the zstd cli
- Set a larger targetLength (eg. --zstd=targetLength=4096)
- Set a larger chainLog (eg. --zstd=chainLog=30)
```
> [doc-bug] Updating the recommended max chainlog for patch-from

- programs/fileio.c
- tests/playTests.sh
Nit: looks like VS code also made some other whitespace changes so unfortunately the second commit isn't clean.
> [bug] passing cParams.hashLog instead of comprParams->hashLog for ldm trigger

- lib/compress/zstd_compress.c
- tests/fuzzer.c
Right now, when the user supplies a non-fullDict to compressStream2 with multi-threading on and claims that they're passing a fullDict, we don't fail. Instead we just convert the dict to a rawContent dict.
> [bug] Making compressStream2 fail when passing rawContent but claiming fullDict

- .travis.yml
- Makefile
- TESTING.md
- appveyor.yml
- build/cmake/CMakeLists.txt
- build/cmake/tests/CMakeLists.txt
- tests/fuzzer.c
- tests/zstreamtest.c
Expand the CTest support. This simplifies integration as a CMake [ExternalProject](https://cmake.org/cmake/help/latest/module/ExternalProject.html).
Tests that are part of the "Medium" set of tests get the `Medium` label and this label is now used by the CMake CI jobs.
The conventional CMake option for enabling tests (`BUILD_TESTING`) is now respected if it was specified on the first configure.
> Add CTest support

- lib/common/error_private.c
- lib/common/zstd_errors.h
- lib/decompress/zstd_decompress.c
- lib/decompress/zstd_decompress_internal.h
- lib/zstd.h
- tests/fuzz/stream_decompress.c
- tests/zstreamtest.c
This flag allows users to skip the output buffer allocation + memcpy if they guarantee that the `ZSTD_outBuffer*` passed to `ZSTD_decompressStream()` is large enough to fit the entire frame, and is never modified by the user.
Also fixes a bug where empty frames weren't eligible for single-pass mode. It caused a small allocation (4 bytes), and is a little bit slower.
Adds tests for single-pass and stable output buffer modes.
Fuzz tests `ZSTD_d_stableOutput` to ensure it never crashes.
Fixes #2093
> [lib] Add ZSTD_d_stableOutBuffer + fix single-pass mode for empty frames

- .travis.yml
- lib/Makefile
- programs/Makefile
- tests/Makefile
fix #2045
When compiling `libzstd` in multithreading mode,
the `libzstd-mt` recipe would not include `-pthread`,
resulting in an underlinked dynamic library.
As a consequence, user programs had to add `-pthread` during their own build.
Fixed it, and added a test on TravisCI to check that `libzstd` is fully linked.
This makes it possible, in some future release,
to provide a multi-threaded `libzstd` dynamic library by default
as it would no longer impact the build script of user programs.
Added another test, which show that compiling a user program (`zbufftest-dll`) linked to multi-threaded `libzstd` doesn't require `-pthread` on user side.
Thanks to @trofi for underlining the issue and solution.
note : not directly related to this PR, but these tests made me realize that almost all our …
> Fix underlinked libzstd

- lib/common/huf.h
- lib/common/zstd_internal.h
- lib/compress/huf_compress.c
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_compress_literals.c
- lib/compress/zstd_compress_superblock.c
- lib/compress/zstd_compress_superblock.h
- lib/compress/zstd_opt.c
- tests/fuzz/simple_round_trip.c
- tests/fuzzer.c
Fixes:
* Enable RLE blocks for superblock mode
* Fix the limitation that the literals block must shrink. Instead, when we're within 200 bytes of the next header byte size, we will just use the next one up. That way we should (almost?) always have space for the table.
* Remove the limitation that the first sub-block MUST have compressed literals and be compressed. Now one sub-block MUST be compressed (otherwise we fall back to raw block which is okay, since that is streamable). If no block has compressed literals that is okay, we will fix up the next Huffman table.
* Handle the case where the last sub-block is uncompressed (maybe it is very small). Before it would skip superblock in this case, now we allow the last sub-block to be uncompressed. To do this we need to regenerate the correct …
> Fix up superblock mode

- .circleci/config.yml
- lib/common/compiler.h
- lib/common/fse_decompress.c
- lib/common/xxhash.c
- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_compress_literals.c
- lib/compress/zstd_compress_sequences.c
- lib/compress/zstd_compress_superblock.c
- lib/compress/zstd_cwksp.h
- lib/compress/zstd_opt.c
- lib/compress/zstdmt_compress.c
- lib/decompress/zstd_ddict.c
- lib/decompress/zstd_decompress.c
- lib/decompress/zstd_decompress_block.c
- lib/legacy/zstd_v01.c
- lib/legacy/zstd_v02.c
- lib/legacy/zstd_v03.c
- lib/legacy/zstd_v04.c
- lib/legacy/zstd_v05.c
- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
- tests/fuzzer.c
- tests/zstreamtest.c
This changeset allows Zstd to be built without warnings under `-pedantic`. Specifically, this was tested with:
```
make clean zstd CFLAGS="-std=c99 -Wall -Wextra -pedantic -Werror -DDEBUGLEVEL=3" CC=gcc
make clean zstd CFLAGS="-std=c99 -Wall -Wextra -pedantic -Werror -DDEBUGLEVEL=3" CC=clang
```
This addresses #2035. See also previous threads on this topic: #1989, #1540, and #1538.
It also lets Zstd build successfully (though not without warnings) under C90/C89/ANSI mode.
This PR accomplishes this in a different way than previous solutions. Rather than diverge into two kinds of macros with and without additional arguments, it simply complies with C99 by making sure every invocation of these macros does have at least one argument.
Known deficiencies:
- Every invocation of …
> Compile Under `-pedantic -Werror` and `-std=c90`

- contrib/largeNbDicts/largeNbDicts.c
Benchmark compression (default) with -z now 
```
./largeNbDicts [Options] filename(s)
Options :
-z          : benchmark compression (default)
-d          : benchmark decompression
-r          : recursively load all files in subdirectories (default: off)
-B#         : split input into blocks of size # (default: no split)
-#          : use compression level # (default: 3)
-D #        : use # as a dictionary (default: create one)
-i#         : nb benchmark rounds (default: 6)
--nbBlocks=#: use # blocks for bench (default: one per file)
--nbDicts=# : create # dictionaries for bench (default: one per block)
-h          : help (this text)
```
Sanity check: largeNbDicts with one dict benchmarks the same as hot compression with -b
```
zstd -b6 -i1 -D ~/data/github_dict -r ~/data/github
6# 9114 …
```
> [bench] Extending largeNbDicts to compression 

- .travis.yml
- lib/Makefile
- lib/README.md
This diff reorganizes the `lib/Makefile` to extract various settings that a
user would normally invoke together (supposing that they were aware of them)
if they were trying to build the smallest `libzstd` possible. It collects
these settings under a master setting `ZSTD_LIB_MIN_SIZE`.
Also document this new option.
> Add Minification Variable to `lib/Makefile`

- appveyor.yml
- build/cmake/tests/CMakeLists.txt
The cygwin test on Appveyor is way too long (>30 mn).
The main issue is the very long `zstreamtest`, because no time out has been programmed.
Ensures that both `fuzzer` and `zstreamtest` receive a 30sec slot.
Should reduce cygwin tests duration by -30mn.
> faster cygwin test

- lib/common/xxhash.c
- lib/decompress/zstd_decompress_block.c
- lib/legacy/zstd_v01.c
- lib/legacy/zstd_v02.c
- lib/legacy/zstd_v03.c
- lib/legacy/zstd_v04.c
- lib/legacy/zstd_v05.c
- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
- tests/fuzz/Makefile
- tests/fuzz/block_decompress.c
- tests/fuzz/block_round_trip.c
- tests/fuzz/dictionary_decompress.c
- tests/fuzz/dictionary_loader.c
- tests/fuzz/dictionary_round_trip.c
- tests/fuzz/fuzz_data_producer.c
- tests/fuzz/fuzz_helpers.c
- tests/fuzz/fuzz_helpers.h
- tests/fuzz/simple_compress.c
- tests/fuzz/simple_decompress.c
- tests/fuzz/simple_round_trip.c
- tests/fuzz/stream_decompress.c
- tests/fuzz/stream_round_trip.c
- tests/fuzz/zstd_frame_info.c
- tests/fuzz/zstd_helpers.c
- tests/fuzzer.c
When the output buffer is `NULL` with size 0, but the frame content size
is non-zero, we will write to the NULL pointer because our bounds check
underflowed.
This was exposed by a recent PR that allowed an empty frame into the
single-pass shortcut in streaming mode.
* Fix the bug.
* Fix another NULL dereference in zstd-v1.
* Fix NULL passed to `memcpy()` and friends across the codebase.
* Overflow checks in 32-bit mode.
* Add a dedicated test.
* Expose the bug in the dedicated simple_decompress fuzzer.
* Switch all mallocs in fuzzers to return NULL for size=0.
* Fix a new timeout in a fuzzer.
Neither clang nor gcc show a decompression speed regression on x86-64.
On x86-32 clang is slightly positive and gcc loses 2.5% of speed.
Credit to OSS-Fuzz.
> [lib] Fix NULL pointer dereference

- lib/dictBuilder/zdict.h
* Move to stable API
* Improve docs
Closes #1816
> [zdict] Stabilize ZDICT_finalizeDictionary()

- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
The modification points interact on each other, and the effect of testing separately is not very well.
Average gains(level 1~19)	gcc9.2.0	clang9.0.0
Compression			1.67%		1.23%
Decompression			0.02%		0.36%
**Test environment**
1)	Measured with lzbench, transplanting the code of Zstd’s develop branch. 
2)	The testfile is silesia.tar.
3)	The test environment is as follows:
aarch64
Cpu name			Armv8-a
CPU(s):				128
Memory Device			DDR4 2666 MT/s 32 GB
Number Of Memory Devices	16
> Optimize compression by using neon function.

- lib/compress/zstd_fast.c
Opportunistic change, saving a few instructions.
Benefits are small though measurable.
gcc 9.3.0 :
kennedy : 459 -> 466
silesia : 360 -> 365
enwik8  : 267 -> 269
clang 10.0.0 :
kennedy : 436 -> 441
silesia : 364 -> 366
enwik8  : 271 -> 272
> small speed improvement for strategy fast

- lib/Makefile
A commonly accepted makefile idiom is V=1 or VERBOSE=1
to request the printing of all commands.
This is not "default" though, and must be manually added.
Example :
Before :
```
make libzstd
compiling dynamic library 1.4.5
creating versioned links
make libzstd V=1
compiling dynamic library 1.4.5
creating versioned links
```
After :
```
make libzstd
compiling dynamic library 1.4.5
creating versioned links
make libzstd V=1
compiling dynamic library 1.4.5
cc -DXXH_NAMESPACE=ZSTD_ -DZSTD_LEGACY_SUPPORT=5 -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef -Wpointer-arith -Wvla -Wformat=2 -Winit-self -Wfloat-equal -Wwrite-strings -Wredundant-decls -Wmissing-prototypes -Wc++-compat  -O3 common/debug.c …
```
> support for verbose make

- programs/README.md
I noticed that the help is outdated as there is no mention of --adapt. Y'all should probably put "update help text" into your release checklist.
(Huh, what are these silent changes with the trailing spaces?)
> programs/README.md: update help text

- build/cmake/CMakeLists.txt
- build/cmake/lib/CMakeLists.txt
- build/cmake/lib/config.cmake.in
- build/cmake/zstdConfig.cmake
- Generate a better CMake Package Config file
- Doesn't give an error if a version is specified to `find_package` (e.g. `find_package(zstd 1.4.3)`)
- Works from both a build directory and installation directory
- Fix that installation of the libzstd.pc does not respect DESTDIR installations (e.g. `make DESTDIR=/tmp/staging install`)
- Minor CMake refactoring/simplification
> CMake: Fix DESTDIR installs and the Package Config file

- .travis.yml
- Makefile
- build/cmake/lib/CMakeLists.txt
- lib/Makefile
- lib/libzstd.pc.in
Resubmission of #2001. This switches the `sed` invocations to use `-E`,
extended regex syntax, which is better standardized across platforms.
I guess.
Same test plan:
```
make -C lib clean libzstd.pc
cat lib/libzstd.pc
echo # should fail
make -C lib clean libzstd.pc     LIBDIR=/foo
make -C lib clean libzstd.pc INCLUDEDIR=/foo
make -C lib clean libzstd.pc     LIBDIR=/usr/localfoo
make -C lib clean libzstd.pc INCLUDEDIR=/usr/localfoo
make -C lib clean libzstd.pc     LIBDIR=/usr/local/lib     prefix=/foo
make -C lib clean libzstd.pc INCLUDEDIR=/usr/local/include prefix=/foo
echo # should succeed
make -C lib clean libzstd.pc     LIBDIR=/usr/local/foo
make -C lib clean libzstd.pc INCLUDEDIR=/usr/local/foo
make -C lib clean libzstd.pc     LIBDIR=/usr/local/
make -C lib clean libzstd.pc …
```
> Fix pkg-config File Generation Again Again

- programs/zstdcli.c
CMake already passes this flag. Make should as well.
Also fixes up the one offender.
> Compile Under `-Wunused-variable`

- programs/README.md
make it clearer that `ZSTD_CLEVEL` is notably useful for `tar --zstd`
Also added documentation for build macros
`ZSTD_NOBENCH`, `ZSTD_NODICT`, `ZSTD_NOCOMPRESS`, `ZSTD_NODECOMPRESS`
> updated zstd CLI documentation

- README.md
> Update benchmarks and add fast mode

- programs/Makefile
- programs/zstdcli.c
to help readability.
Group arguments into separated titled categories,
try to give better visibility to more commonly used arguments.
> updated `zstd -h` 

- lib/common/error_private.h
- lib/compress/zstd_compress.c
- lib/zstd.h
- tests/fuzzer.c
Fix #2107 
Ensure no context downsizing is happening if context is initialized with `ZSTD_initStatic*()`.
Updated tests to control tighter memory scenarios.
> Fix for initStatic

- programs/Makefile
Recent versions of clang seem to require a step of conversion from the profraw file to a "compiler-readable" profdata file to let PGO work.
> programs/Makefile: make it actually work with clang

- tests/playTests.sh
```
echo "start" | grep -f - tmp_grep
```
doesn't work consistently on all greps (eg: fails on mac) so we shouldn't require that zstdgrep support that usage. Removing that test
> [build] removing -f test (grep usage not supported on mac)

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_double_fast.c
- lib/compress/zstd_fast.c
- lib/compress/zstd_lazy.c
- lib/compress/zstd_opt.c
- lib/decompress/zstd_ddict.c
- lib/decompress/zstd_decompress.c
- lib/decompress/zstd_decompress_block.c
- lib/decompress/zstd_decompress_internal.h
- tests/fuzz/Makefile
- tests/fuzz/dictionary_round_trip.c
- tests/fuzz/fuzz.py
- tests/fuzz/raw_dictionary_round_trip.c
The bug is be triggered when:
* A dictionary is used.
* There are at least two blocks of data.
* First block ends and one of the repcodes in the state points into the dictionary at the end of the block.
* The dictionary is invalid for all/some of the second block.
* The second block uses one of the repcodes from the first block that point into the dictionary, past the point where the dictionary is invalidated.
The bug is fixed by always validating the repcodes. All other strategies are okay because the lower levels invalidate offsets early, and the optimal parser already does this validation.
This patch adds a macro `FUZZING_ASSERT_VALID_SEQUENCE` which tells the decompressor to check sequences with `assert()` because they are always expected to be valid. The round trip style fuzzers …
> Fix rare scenario with lazy parser, dictionary, and repcodes

- lib/compress/zstd_lazy.c
PR #2131 caused a 5% loss in speed for levels 5 and 6. This is caused by code alignment. This PR gets the speed back up to par.
I've measured speed with clang and gcc levels 5-9 and the performance is now approximately neutral with performance before the PR (within 1 MB/s either way).
This is the same alignment command that we are using in `decompressSequences()` so we're not adding anything new right before the release.
> [greedy] Fix performance instability

- lib/compress/zstd_compress.c
- lib/compress/zstd_ldm.c
- tests/fuzzer.c
Exposed when loading a dictionary < LDM minMatch bytes in MT mode.
Test Plan:
Add a unit test that catches the bug, and run the zstreamtest reproducer.
```
CC=clang make -j zstreamtest fuzzer MOREFLAGS="-O0 -fsanitize=address"
./zstreamtest -vv -i100000000 -t1 --newapi -s7065 -t3925297
./fuzzer -v -i1
```
> [lib] Fix bug in loading LDM dictionary in MT mode

- tests/regression/results.csv
https://github.com/facebook/zstd/pull/2131/files#r425494155 explains the change, which was a small optimization in the case of small window sizes.
> [test][regression] Update results.csv

- tests/fuzz/Makefile
- tests/fuzz/dictionary_stream_round_trip.c
- tests/fuzz/fuzz.py
I can't find out why CIFuzz is failing on https://github.com/facebook/zstd/pull/2139
I'm creating a fresh pr to test if it fails here.
> [fuzz] Adding dictionary_stream_round_trip fuzzer

- contrib/single_file_libs/README.md
- contrib/single_file_libs/combine.sh
- contrib/single_file_libs/create_single_file_library.sh
- contrib/single_file_libs/zstd-in.c
Since #2103 the generated file sizes are much larger on macOS (and any other environment where `realpath` is missing). This adds a Python fallback to bring the file sizes back to what they were.
> Reduced single file lib size on macOS

- tests/playTests.sh
Addresses #2144.
It's surprising that none of our tests caught this. We can address that shortfall in a follow-up issue.
> Don't Use `[[` in Shell Scripts

- lib/compress/zstd_compress.c
- lib/compress/zstd_ldm.c
- lib/compress/zstdmt_compress.c
- tests/fuzzer.c
* Invalidate the `loadedDictEnd` when we reset the context
* Also invalidate `loadedDictEnd` when we do overflow correction
Added a test that produces an out of bounds offset before this fix, and works after.
> [ldm] Reset loadedDictEnd when the context is reset

- lib/compress/zstd_fast.c
- lib/compress/zstd_ldm.c
- lib/compress/zstdmt_compress.c
- tests/fuzz/.gitignore
Issue 22294, firing `assert(offset_1 <= current +1)` within `compress_fast_extDict()`,
and issue 22262, firing `assert(offset_1 <= dictAndPrefixLength)` within `compress_fast_dictMatchState()`,
are actually a consequence of a new behavior enabled within `ldm`, that has become possible since the new `--patch-from` capability (and therefore not present in earlier versions) : 
- Previously, `ldm` would not load any dictionary when in multithreading mode
+ This is still the case when using the "one-ingestion" strategy
- This has been updated as part of the [`--patch-from` capability](https://github.com/facebook/zstd/blame/dev/lib/compress/zstdmt_compress.c#L1519)
+ Loading the dictionary into the `ldm` is necessary in order to catch long-distance correlations
+ Note that only the "streaming" …
> fix 22294 & 22262

- tests/fuzz/simple_round_trip.c
Expand it so we don't get too much noise. If it fires again I will probably just delete this test.
> [fuzz] Expand the allowedExpansion

- lib/compress/zstdmt_compress.c
- tests/fuzzer.c
Missed 1 place to reset the `loadedDictEnd` in PR #2150.
Test Plan:
```
./zstreamtest --newapi -vv -i75205 -s4067 -t75156
./zstreamtest --newapi -vv -i1861 -s5681 -t1792
./zstreamtest --newapi -vv -i1937 -s7232 -t1845
```
> [ldm][mt] Fix loadedDictEnd

- appveyor.yml
triggered following visual-release compilation test
> Fix playTests.sh 

- lib/legacy/zstd_v04.c
Fixes this error when building with `make ZSTD_LEGACY_SUPPORT=1`:
```
legacy/zstd_v04.c:77:10: fatal error: debug.h: No such file or directory                                                     
77 | #include "debug.h"                                                                                                   
```
> Fix legacy build after #2103

- build/cmake/lib/CMakeLists.txt
- build/meson/lib/meson.build
- lib/Makefile
this API is deprecated, for a loong time now,
all related symbols will be removed in a future version (likely v1.5.0)
and the header `zbuff.h` doesn't compile from `include/` anyway,
because it needs to be positioned one directory below `zstd.h`.
Also removed `cover.h` from `cmake` installer,
as it should have never been part of this list to begin with.
Fix #2161
> do not install zbuff.h

- doc/zstd_compression_format.md
Specifies the decoder's behavior on receiving a frame with `dictID=0`.
Pushed paragraph on reserved `dictID` ranges into the Dictionary Format section.
Answer #2172 .
> updated spec on dictID==0

- lib/Makefile
rule `lib-release` wasn't working : it was just skipped.
Same for `lib-mt`.
Removing them from the list of `.PHONY` targets fixes it.
fix #2175
> fixed default rule for lib/Makefile

- programs/fileio.c
The effective limit was 2GB but the enforced limit was 4GB. Fixing the inconsistency. I see that there is another issue (https://github.com/facebook/zstd/issues/2173) open about increasing the limit all together. If we go down that route, that'll be a different pr. 
Test plan
```
$ make -C tests datagen
$ tests/datagen -g3000000000 > large-data
$ cp large-data large-dict
$ make -j
$ ./zstd --patch-from=large-dict large-data -o /dev/null
zstd: error 42 : Can't handle files larger than 2 GB
```
> Change --patch-from limit from 4gb to 2gb

- .github/workflows/generic-dev.yml
This is the first batch of tests I'm migrating from travis CI because of discontinued support in the coming months. This is just a subset of the dev pr tests. The master pr tests will be in a separate workflow file. 
Some tests weren't able to be migrated. Will have to do some additional work to make those work like setting up an arm self-hosted runner and trusty self-hosted runner with fb. 
* icc (need self-hosted)
* arm/qemu-arm (need self-hosted)
* versionTag 
* valgrindTest (keeps failing for some reason. need investigation)
* staticAnalyze (need trusty so need self-hosted)
* pcc-fuzz: (need trusty so need self-hosted)
* arm-build-test (need self-hosted)
> [actions] Migrating 1st batch of tests from Travis to Github Actions

- .github/workflows/generic-release.yml
There are a number of tests that were not migrated. See the comments in the yml for details. Will have to figure out how to get those ported later. But this is the low hanging fruit. 
Also I want to test the release only tests more throughly so I'm running them even on prs to dev right now. I'll remove that eventually.
> [actions] Migrating 2nd batch of tests from Travis to Github Actions

- lib/compress/zstd_compress.c
- lib/compress/zstd_cwksp.h
This PR refactors the compression code so that there is a single function responsible for figuring out how much memory we need to allocate for a CCtx given a set of parameters.
In addition to settling on a single logic that estimates this size, this also adds an assert that validates that estimate is exactly correct.
> Consolidate CCtx Size Estimation Code

- .github/workflows/generic-dev.yml
- tests/playTests.sh
Closes https://github.com/facebook/zstd/issues/2149
I'm using [shellcheck](https://github.com/koalaman/shellcheck#from-your-terminal) to check compatibility with bourne shell explicitly. I confirmed that this catches the incompatibility that was missed in the previous release (https://github.com/facebook/zstd/pull/2148): 
```
In tests/playTests.sh line 270:
if [[ $file2timestamp -ge $file1timestamp ]]; then
^-- SC2039: In POSIX sh, [[ ]] is undefined.
```
It also discovered 3 other warnings. Two of them were good suggestions so I fixed them. One of them isn't worth fixing imo so I suppressed it using shellcheck --exclude. This is the warning I excluded
```
In tests/playTests.sh line 401:
ls -las $INTOVOID | grep "rw-rw-rw-"
^-- SC2010: Don't use ls | grep. Use a glob or a for loop with a …
```
> [ci] Adding bourne shell compatibility test

- README.md
- tests/playTests.sh
Improved zstd test script by making it more intuitive.
- Provided default values for both ZSTD_BIN and DATAGEN_BIN
- Added more actionable error messages in the script
- Added instructions for local testing in README
> Check environmental variables in playTests.sh and add default values

- programs/zstd.1.md
- programs/zstdcli.c
This makes it easier to parse the version of zstd
we have instead of having to run a regex to parse
the WELCOME_MESSAGE
This was needed because we wanted to detect if
--patch-from was supported or not.
> Make --version respect -q for ouptut a shorter version string

- programs/fileio.c
- tests/playTests.sh
Closes https://github.com/facebook/zstd/issues/2195
A further refinement might be to guess the size of src when not provided by --stream-size. The src size won't be much bigger than the dict size so we could potentially pick `dictSize + SOME_PADDING`.
> [cli] Allowing stdin on --patch-from using --stream-size

- lib/compress/zstd_compress_superblock.c
The bound check condition should always be met because we selected `set_basic` as
our encoding type. But that code is very far away, so assert it is true so if it is
ever false we can catch it, and add a bounds check.
Fixes #2213.
> [superblock] Add defensive assert and bounds check

- contrib/single_file_libs/zstd-in.c
- lib/dictBuilder/cover.c
- lib/dictBuilder/fastcover.c
- lib/dictBuilder/zdict.c
The `dictBuilder` sources were missing from the single-file libs, as per #2211. This PR:
- Adds the missing files to the generator script's input
- Fixes the duplicate 'console' macros and vars
- Fixes the duplicate hash functions
I'm not 100% happy with the approach for fixing the macros (adding `#undef`s) since it adds _noise_ around the definitions. That said... I'm not sure pulling out that code into a shared header would be any cleaner.
The hash functions were already present in `zstd_compress_internal.h` but instead of relying on those the choice was to prefix (with `COVER_` or `FASTCOVER_` accordingly). This was felt to be cleaner (than detecting `ZSTD_COMPRESS_H`, which felt like introducing future breakage).
> Single-file libs now include dictBuilder

- lib/common/compiler.h
- lib/dictBuilder/cover.c
On MSVC there are other calling conventions such as __vectorcall, which may be enabled as the default. When this is done, zstd will not compile as it attempts to pass a __vectorcall sort function to qsort, which expects a __cdecl function.
This explicitly marks those functions intended for usage with qsort as being __cdecl.
> Explicitly use __cdecl for qsort, to avoid warning when default calling convention is not __cdecl

- lib/dictBuilder/fastcover.c
* Remove the unnecessary mask, since `ZSTD_hash*()` already ensures
the output is mod 2^h.
* Dedup the hash functions and use `ZSTD_hash*()` directly.
> [cover] Remove unnecessary mask and dedup hash functions

- lib/decompress/zstd_decompress_block.c
Fix unused vairable warnings when `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` is defined but asserts are disabled.
Fixes #2210.
> Fix unused variable warnings in fuzzing build mode without asserts

- .circleci/config.yml
- index.html
Should I add something like (full) or (block, streaming, dictionary, training)?
I think it's the only C# binding that provides OSX .dylib and Linux Musl compatible .so versions as well.
It ships stripped statically linked O3 LTO builds of libzstd for the gamut of platforms that .NET / Fw / Core runs on.
It builds libzstd-mt from zstd version tags and does generic tests for all the platforms using docker images, incl. armv7-hf and arm64v8 via qemu.
It exposes friendly wrappers as well as direct bindings, it has decent testing and coverage.
Performance overhead is minimal as it performs direct `calli` cdecl call site bindings.
It's also signed now, so corpos that need that sort of thing can link their signed assemblies against it.
> Add ImpromptuNinjas.ZStd C# libzstd bindings link to GitHub Pages branch

- contrib/single_file_libs/build_decoder_test.sh
- contrib/single_file_libs/build_library_test.sh
- lib/common/pool.c
- lib/dictBuilder/cover.c
The single-file library makes a compilation error on Emscripten build due to static variable names collisions, reported on #2211
- Rename a few static variables
- Try Emscripten build using `docker` if `emcc` command is not available
Error like this...
```bash
$ ./build_library_test.sh
Amalgamating files... this can take a while
Processing: zstd-in.c
...
Combine script: PASSED
Single file library creation script: PASSED
Compiling roundtrip.c: PASSED
Compression: PASSED (size: 3127, uncompressed: 32768)
Decompression: PASSED
Byte comparison: PASSED
Running roundtrip.c: PASSED
zstd.c:30822:21: error: redefinition of 'g_ctx' with a different type: 'COVER_ctx_t *' vs 'POOL_ctx' (aka 'struct POOL_ctx_s')
static COVER_ctx_t *g_ctx = NULL;
^
zstd.c:7413:17: note: previous definition is here …
```
> [contrib] Fix single-file compilation error on Emscripten build.

- programs/Makefile
Clang is also supported, so no need to mention only the GCC compiler.
> Update comment about PGO build.

- build/cmake/lib/CMakeLists.txt
Mingw follows unix conventions and often expects pkg-config files to be present.
> Install pkg-config file on MINGW also

- .github/workflows/main.yml
It should address https://github.com/google/oss-fuzz/issues/3982
> cifuzz: don't upload artifacts when CIFuzz fails to build fuzz targets

- programs/util.c
Since version 1.4.5 and commit 5af8cb7aea8d890b4801e50e5274371510f2cf33, if st_mtime is not defined, programs/util.c uses utime without including utime.h which will raise the following build failure on some of the buildroot autobuilders:
```
util.c: In function 'UTIL_setFileStat':
util.c:161:24: error: storage size of 'timebuf' isn't known
struct utimbuf timebuf;
^~~~~~~
```
Fixes:
- http://autobuild.buildroot.org/results/be902c5d110f37bce622a2215191f155b7d3e7e0
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> programs/util.c: fix build without st_mtime

- build/meson/meson.build
Tested on a default installation of Debian 10.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
> meson: remove build requirement for distutils

- programs/zstdcli.c
- tests/playTests.sh
this patch reduces complexity associated with
commands requiring a separated arguments
such as :
`-o filename`
`-D dictionary`
`--output-dir-flat dir`
`--output-dir-mirror dir`
`--maxdict size`
`--dictID id`
It used to be a multi-stage process requiring maintenance of an explicit context,
it's now simplified as a single macro.
Thanks to this simplification,
separated arguments logic has also been extended to
`--patch-from XXX`
`--filelist XXX`
extending current syntax using `=XXX`
`--patch-from=XXX`
`--filelist=XXX`
Separated argument is useful for filenames and directories,
as it benefits from shell expansion
such as `~/dir/file`
where the `~` is automatically translated by the shell.
In contrast `--long-command=FILE` does not interpret `FILE`,
hence `~/` is transmitted as is to the …
> CLI: simplified handling of separated-fields arguments

- lib/common/zstd_internal.h
Fix preprocessor in ZSTD_wildcopy so that X86 code goes to the right branch.
> Fix preprocessor in ZSTD_wildcopy

- contrib/single_file_libs/build_decoder_test.sh
- contrib/single_file_libs/build_library_test.sh
- lib/dictBuilder/cover.c
- lib/dictBuilder/fastcover.c
Visual Studio 2019 was generating a variable shadowing warning after the dict builder was rolled-in. This prefixes the affected global and adds `-Wshadow` to the build scripts.
> Fixed VS variable shadowing warning (single file lib)

- lib/common/zstd_internal.h
Use `memcpy` instead of `COPY16` so that the `add` instruction can be moved after the branch. This could save 1 instruction when compiling with gcc.
Codegen before this PR: in Basic Block 1, 4 instructions execute before jmp instruction.
Codegen after this PR: in Basic Block 1, 3 instructions execute before jmp instruction.
> Optimize ZSTD_wildcopy

- lib/compress/hist.c
new version easier to vectorize
leads to smaller code and faster execution
notably at the last recombination stage (fixed cost per block).
Assembly inspected with godbolt
On my `macosx` laptop, using default `clang` with `-mavx2` :
2K block : 1280 MB/s -> 1550 MB/s
8K block : 1750 MB/s -> 1860 MB/s
Also : fixed a minor error for a corner case (srcSize == 0)
> optimized histogram

- lib/common/bitstream.h
- lib/common/compiler.h
- lib/common/zstd_internal.h
- lib/compress/zstd_compress_internal.h
This adds STATIC_BMI2 define to compiler.h, which is enabled on MSVC when compiler target has __AVX2__ enabled
Like DYNAMIC_BMI2 but at compile time.
Replaces uses of BitScanForward/Reverse with _lzcnt_u64/_tzcnt_u64 and 32 variants for better code gen.
Other changes when STATIC_BMI2 is on:
BIT_getLowerBits uses _bzhi_u64 
BIT_getMiddleBits uses _bextr_u64
STATIC_BMI2 is only turned on with MSVC
MSVC is terrible at detecting patterns such as  _bextr_u64, clang is much better so maybe not necessary there.
In BIT_getLowerBits  Clang is smart enough to use _bzhi_u64 when -march=skylake is enabled(AVX2 support), MSVC fails to do so when /arch:AVX2 is on.
> Added STATIC_BMI2 for compile time detection of BMI2 on MSVC, when enabled various intrinsics are used

- programs/fileio.c
- programs/util.c
- programs/util.h
This stack introduces variants of various `UTIL_...()` functions that take an already prepared result of a `stat()` call, rather than making a `stat()` call themselves. In situations where several of these calls are made in sequence, it's easy to use these new functions to refactor the code to reuse the result of a single `stat()` call rather than make several.
This causes zstd to make 37% fewer `stat()` calls:
```
felixh@vali:~/prog/zstd (dev)$ strace ./zstd -r lib -o /dev/null |& grep -E '^stat\(' | wc -l
730
felixh@vali:~/prog/zstd (fewer-stat-syscalls)$ strace ./zstd -r lib -o /dev/null |& grep -E '^stat\(' | wc -l
460
```
> Share stat() Calls Where Convenient

- lib/common/compiler.h
Reorder the ifdefs for the PREFETCH macros so that the compiler builtin is favored over the inline assembly for aarch64.
I checked godbolt and both gcc and clang will produce the same prefetch commands as the inline asssembly.
> Prefer __builtin_prefetch over inline asm

- lib/decompress/zstd_decompress_block.c
Minor change but newer Clang/Xcode projects seem to have the `-Wcomma` warning enabled by default.
There are more of these in the codebase in general, and it's a style I use myself, so wasn't sure whether adding the various compiler equivalents of `-Wno-comma` would be better? For the single file _decoder_ there's only one so it became a one-liner.
> Fix clang -Wcomma warning (single file decoder)

- lib/zstd.h
It does not only return 0 on success.
> Fix Documentation for ZSTD_CCtxParams_setParameter()

- .github/workflows/generic-dev.yml
- .travis.yml
The directory structure for icc's installation had changed so it couldn't find he setvars.sh it needed. I now just reference the compiler path for the latest icc directly which shouldn't change.
> [actions] removing broken icc test from travis and adding working version to actions

- lib/decompress/zstd_decompress.c
- lib/decompress/zstd_decompress_block.c
- tests/fuzz/Makefile
- tests/fuzz/decompress_dstSize_tooSmall.c
- tests/fuzz/fuzz.py
- tests/fuzzer.c
* Always return `dstSize_tooSmall` when the destination buffer is too small for both compression and decompression
* Add tests to `fuzzer.c`
* Update `simple_compress` fuzzer to ensure `dstSize_tooSmall` is returned
* Add `decompress_dstSize_tooSmall` fuzzer to ensure `dstSize_tooSmall` is returned
Initial performance looks slightly positive for gcc and slightly negative for clang. It looks like just alignment noise.
Fixes #2222
> [fix] Always return dstSize_tooSmall when it is the case

- lib/decompress/zstd_decompress.c
- lib/decompress/zstd_decompress_internal.h
- lib/zstd.h
- programs/fileio.c
- programs/zstdcli.c
- tests/fuzzer.c
- tests/playTests.sh
This adds the advanced parameter `ZSTD_d_forceIgnoreChecksum` as a new experimental decompression parameter. If enabled, then decompression will ignore checksums, whether or not they were enabled during compression.
A few considerations/points of discussion:
- Open to other naming suggestions - not sure if there’s a general consensus against negative actions in param names (ignore), but I wanted to emphasize that we’re going out of our way to ignore the checksum behavior that the compressor specified, and that this isn't typical behavior, hence `forceIgnore`. But, done the other way, we avoid all the `!` in the logic implementing this.
- This strictly ignores the value of the checksum, i.e. if the checksum flag is enabled in the compressed stream, but the checksum size is not 4 bytes, …
> New advanced decompression param to ignore checksums

- tests/fuzz/fuzz_data_producer.c
- tests/fuzz/fuzz_data_producer.h
- tests/fuzz/simple_round_trip.c
- tests/fuzz/stream_decompress.c
* Disable the superblock expansion test, since there isn't effectively a bound in the worst case.
* Fix `stream_decompress` to avoid timeouts by passing the whole buffers when out of control bytes in the data producer.
> [fuzz] Fix oss-fuzz test problems

- lib/common/entropy_common.c
- tests/fuzz/Makefile
- tests/fuzz/fse_read_ncount.c
- tests/fuzz/fuzz.py
* Fix bug introduced in PR #2271
* Fix long-standing bug that is impossible to trigger inside of zstd
* Add a fuzzer that makes sure the normalized count always round trips
correctly
I measured this change to be performance neutral, modulo small changes due to alignment.
> [bug] Fix FSE_readNCount()

- programs/fileio.c
- programs/fileio.h
- programs/zstdcli.c
- tests/playTests.sh
video of how it works: https://vimeo.com/451651373
Summary:
Now, instead of line by line output, we have a single, live updating progress feed when compressing/decompressing multiple files.
```
zstd tmp1 tmp2 tmp3 tmp4.       # uses refreshing status line, displayLevel = 2
zstd tmp1 tmp2 tmp3 tmp4.  -v   # same as before, prints status updates on each line and more info, displayLevel = 3
zstd tmp1 tmp2 tmp3 tmp4   -q.  # same as before, emits nothing, displayLevel = 1
```
We add two new parameters in `FIO_prefs_t`: `int nbFiles` and `int currFileIdx`. Also, the function signature of `FIO_(de)compressMultipleFilenames()` no longer has a `nbFiles` field, since we already have one in `FIO_prefs_t`.
Now, we only force `displayLevel=1` in pipe mode which is actually desirable, as opposed to …
> Refreshing progress bar for processing multiple files

- lib/zstd.h
`ZSTD_versionString(void)` function is missing from the manual.
Below is the display effect in the Edge browser.
Before:
After:
> [doc] Add ZSTD_versionString() to manual

- programs/fileio.c
- programs/util.c
- programs/util.h
- programs/zstd.1.md
- tests/playTests.sh
The following would trigger the warning:
`zstd tst/tmp1 tst/tmp2 tst/tmp3 -o out.zst`
`zstd tst/tmp1 tst/tmp2 tst/tmp3 -o out.zst --rm` (this one aborts fully)
`zstd tst/tmp1 tst/tmp2 tst/tmp3 -o out.zst --rm -f`
`zstd tst/tmp1 tst/tmp2 tst/tmp3 -o out.zst -f`
`zstd tst/tmp1 testfiles/tmp2 testfiles/tmp3 -c`
`zstd -r tst/ -o out.zst`
`zstd -r tst/ -c`
`zstd -r tst/ --rm -c` (this one aborts fully)
./zstd -r tst/ --rm -f`
For overwriting the file with `-f`, there's no warning triggered. Is that behavior that we want here as well? 
Some tests in `playTests.sh` had to be modified to work with the new warning.
> Add a warning whenever (de)compressing multiple files

- lib/compress/zstd_compress.c
Unintentional integer overflow (OVERFLOW_BEFORE_WIDEN)
overflow_before_widen: Potentially overflowing expression:
cdict->dictContentSize * 6U
with type unsigned int (32 bits, unsigned) is evaluated using 32-bit arithmetic, and then used in a context that expects an expression of type U64 (64 bits, unsigned).
> Resolve Coverity 1432392 Unintentional integer overflow

- lib/Makefile
Previously, this construct would add `-O3` onto the end of the compiler flags variable, **after** `MOREFLAGS`, which meant that it was impossible to override. This commit fixes this order and should otherwise be a no-op.
> Fix Makefile Variable Concatenation Order

- lib/compress/zstd_compress.c
`ZSTD_CCtx_setParameter` does not adhere to the documented behavior of setting `0` as `compressionLevel`:  
`Special: value 0 means default, which is controlled by ZSTD_CLEVEL_DEFAULT`.  
Instead it does not change the compression level at all.  
This pull request adjusts the behavior to conform to the documentation.
> Fix setParameter not falling back to default compression level

- contrib/largeNbDicts/largeNbDicts.c
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_lazy.c
- lib/compress/zstd_lazy.h
- lib/zstd.h
- programs/fileio.c
- tests/fuzzer.c
Builds on top of @bimbashrestha's #2201 to implement a new search structure for dictionaries in the greedy, lazy, and lazy2 
strategies. This is a work-in-progress.
Expected performance increases are approximately as follows:
Level | Hot Dict | Cold Dict
----- | -------- | ---------
5   |   ~+10%  |    ~+35%
6   |   ~+10%  |    ~+30%
7   |   ~+ 8%  |    ~+25%
8   |   ~+ 6%  |    ~+17%
9   |   ~+ 6%  |    ~+14%
10   |   ~+ 5%  |    ~+12%
The improvement degrades as the input gets large. Compression ratio is slightly improved at level 5 (~0.05%). Benchmarked on an Intel Xeon E5-1650 v3 @ 3.50GHz (Haswell), with gcc 8.4.0. With recent fixes, I'm not aware of any scenario where perf is worse with the DDSS than without.
To-Do:
> DDSS For Lazy: Implement a Dedicated Dictionary Hash Table

- lib/compress/zstd_compress.c
- lib/compress/zstd_lazy.c
- lib/zstd.h
- tests/fuzzer.c
This PR builds on #2276 to also restructure the chain table for the strategies `ZSTD_greedy`, `ZSTD_lazy`, and `ZSTD_lazy2`.
With this PR, the cumulative perf improvement seen for the Dedicated Dictionary Search Structure stack, for the HTTP test corpus, is:
Level | Hot Dict | Cold Dict
----- | -------- | ---------
5   |   ~+17%  |    ~+30%
6   |   ~+12%  |    ~+45%
7   |   ~+13%  |    ~+40%
8   |   ~+16%  |    ~+50%
9   |   ~+19%  |    ~+65%
10   |   ~+24%  |    ~+70%
> DDSS for Lazy: Implement a Dedicated Dictionary Chain Table

- lib/compress/zstd_compress.c
- lib/zstd.h
- tests/fuzzer.c
fix #2297
also :
- `assert()` `endDirective` in `ZSTD_compressStream_internal()`, for debug mode
- add relevant tests
> check endDirective in ZSTD_compressStream2()

- programs/README.md
- programs/zstd.1.md
- programs/zstdcli.c
- tests/playTests.sh
Using `ZSTD_NUMTHREADS` as the environment variable. `-T#` supersedes this setting.
> Allow environment variable to specify number of threads for compression

- contrib/linux-kernel/Makefile
- contrib/linux-kernel/decompress_sources.h
- contrib/linux-kernel/test/Makefile
- contrib/linux-kernel/test/static_test.c
Add decompress_sources.h, which includes all the decompression .c files.
This is used for kernel decompression.
Also, add a test which checks that including decompress_sources.h works.
> [contrib][linux-kernel] Add decompress_sources.h

- lib/compress/zstd_compress.c
- lib/zstd.h
- tests/regression/results.csv
The regression tests discovered a couple ways in which #2276 and #2295 caused failures to correctly derive compression parameters. The regression test results now have a much smaller diff against `v1.4.6`:
```diff
--- tests/regression/results.csv
+++ results-eee51a66.csv
@@ -26,4 +26,4 @@
-silesia,     level 5,           compress cctx,                4710237
-silesia,     level 6,           compress cctx,                4660057
-silesia,     level 7,           compress cctx,                4596295
-silesia,     level 9,           compress cctx,                4543924
+silesia,     level 5,           compress cctx,                4710236
+silesia,     level 6,           compress cctx,                4660056
+silesia,     level 7,           compress cctx,                4596296
+silesia, …
```
> Fix Compression Parameter Derivation Bugs Introduced by DDSS Changes

- tests/playTests.sh
Writing to stdout causes tests to fail when importing into TP2.
I will merge into the `staging` branch for zstd-1.4.6.
> [tests] Don't write to stdout

- .github/workflows/linux-kernel.yml
- contrib/linux-kernel/Makefile
- contrib/linux-kernel/zstd_deps.h
- lib/common/zstd_internal.h
- lib/decompress/zstd_decompress_internal.h
- lib/zstd.h
* Enable `-Wunused-const-variable` and `-Wunused-but-set-variable` in the linux kernel CI so these don't regress.
* Fix `contrib/linux-kernel/zstd_deps.h` to `(void)` all parameters in `ZSTD_malloc`, `ZSTD_free`, and `ZSTD_calloc`.
* Fix all `-Wunused-const-variable` warnings in `lib/`. This includes one fix in `zstd.h`.
See the report here https://lkml.org/lkml/2020/9/23/598.
I will cherry pick these commits into the `staging` branch for zstd-1.4.6.
> Silence warnings reported by Kernel Test Robot

- .gitignore
- programs/fileio.c
- programs/fileio.h
- tests/playTests.sh
This PR adds support to decompress `*.zstd` files, silently.
Users might accidentally use that prefix instead of `.zst` so this seems nice to have. 
We don't include `.zstd` in `suffixListStr` (which prints out the supported suffixes when trying to decompress an invalid suffix), nor do we include this in the `README.md` cause `.zst` is still the correct suffix that should be used - this is just more for convenience.
Tests: in `playTests.sh` and manual spot-checking.
> Support .zstd suffix only for decompression

- programs/fileio.c
To address #2309 
This PR will make it so that the lines printed throughout the multifile status bar update are roughly the same size each time, and adds a bit of padding at the end, so it will more successfully overwrite. We also add 40 characters of whitespace to the right of the printed summary, which would override any leftover characters from the status bar.
I'm not sure if there are better ways to do this. There are still theoretically rare/extreme cases in which we still may leave behind some leftover characters (if the number of megabytes read for a given file are more than tens of thousands, and then the next file is small). Escape codes would be a cleaner solution, but aren't portable.
Tested locally to make sure it works as intended, and that the leftover characters are …
> Fix multifile status bar and summary - clear out extraneous characters

- programs/fileio.c
- programs/fileio.h
- programs/util.c
- programs/util.h
- programs/zstdcli.c
- tests/playTests.sh
`getchar()`-dependent warning prompts may swallow characters from stdin. We don't want that if stdin is our input.
The following behavior is currently:
```
$ cat <<EOF >test
> y
> Hello, world!
> EOF
$ ./zstd test
test                 :181.25%   (    16 =>     29 bytes, test.zst)             
$ ./zstd -q -d test.zst -c           // compresses fine when directly processing file
y
Hello, world!
$ ./zstd < test -o test.zst.         // 'y' in the first line is consumed when input is fed thru stdin
/*stdin*\            :192.86%   (    14 =>     27 bytes, test.zst)             
$ ./zstd -q -d test.zst -c
Hello, world!
```
Unit tests included, and checked that they fail on current `dev` branch, but work with the patch.
> Don't let warning messages consume input from stdin

- doc/zstd_compression_format.md
There was a request to disallow repcodes == 0 in dictionaries. However, it seems to already be implemented (see: `zstd_compress.c: line 3048`).
But the compression format doc was not updated. Also, according to the code, in `zstd_compress.c: line 3049`, `repcode == dictContentSize` is allowed, so the documentation for that is accordingly adjusted.
> Update documentation about repcodes in dictionaries

- lib/compress/zstd_compress_internal.h
ZSTD_hashPtr() function was not expanded by MSVC, led to low performance compared to GCC.
Issue https://github.com/facebook/zstd/issues/2314
> Let MSVC force inline ZSTD_hashPtr() function

- lib/decompress/zstd_decompress.c
- lib/zstd.h
- tests/fuzzer.c
* Reset all decompression parameters in `ZSTD_DCtx_reset()` when
resetting parameters.
* Add a test case.
Fixes #2331.
> Reset all decompression parameters in ZSTD_DCtx_reset()

- lib/compress/zstd_compress_internal.h
Clarify how we handle dictionaries in each case.
> Add comments to ZSTD_getLowest{Match,Prefix}Index()

- programs/zstdcli.c
Simple change - instead of displaying a generic `Incorrect parameters` error message, we display the actual reason that an operation like `zstd < FILE` fails. The extra info that `badusage()` prints about flags and how zstd accepts arguments also isn't really relevant/useful in this case, so we just print this one line, like `gzip`.
> Improve error messages on console input/output

- lib/compress/zstd_compress.c
This PR does resolves two issues brought up in #2300, discovered by @animalize:
1) When using ZSTD_compressStream2(), if a `cdict` was used during compression, that cdict's compression level was not respected. Now the `cdict` will take priority in terms of compression level, but will not change `cctx->requestedParams`.
2) Fixes `ZSTD_createCDict_byReference()` to use the overloaded `compressionLevel = 0` behavior.
No unit tests included in this PR, but tested locally (and by @animalize in #2300) to confirm that using `ZSTD_compressStream2()` does in fact take on the `cdict` compression level when compressing files that would cause a dictionary reload, and that everything else works as usual.
> For ZSTD_compressStream2(), let cdict take compression level priority

- programs/fileio.c
- programs/fileio.h
- programs/zstdcli.c
- tests/playTests.sh
Note: this will have merge conflicts with #2322 (and recently merged #2310), so once #2322 is merged, I'll fix the merge conflicts in this PR.
Currently we have some issues where intermediate status summaries are interspersed with compressed or decompressed data output to `stdout`.
This PR changes the behavior so that no matter the verbosity, there will never be anything displayed/printed in the middle of a compressed or decompressed output in `stdout`. This is particularly important for decompression, if the user wants to spot check decompressed output in the terminal. Though displayed compressed output in the terminal isn't really comprehensible anyways, it's good to be consistent here too.
However, at higher verbosities, a summary may be printed afterwards, along with some other …
> Prevent summary updates when using stdout

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstdmt_compress.c
- tests/fuzzer.c
This PR is divided into several commits which are split logically. See each commit message for details. Summary included below.
* [bug] Fix dictContentType when reprocessing cdict - The cdict could get loaded in `auto` mode when it was supposed to be raw content.
* [refactor] Remove ZSTD_resetCStream_internal() - It wasn't a logical division of responsibilities and was hiding a bug.
* [minor improvement] Pass dictSize when selecting parameters - In `ZSTD_compressStream2()` we weren't passing the dictionary size when selecting compression parameters.
*  [minor improvement] Pass 0 as the content size in the DDS.
* Fix ZSTD_adjustCParams_internal() to handle dictionary logic  - Pass the compression parameter mode into `ZSTD_{get,adjust}CParams_internal()` and avoid downsizing the hashLog and …
> Fix ZSTD_adjustCParams_internal() to handle dictionary logic

- doc/zstd_manual.html
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_ldm.c
- lib/compress/zstd_opt.c
- lib/compress/zstdmt_compress.c
- tests/fuzzer.c
- tests/playTests.sh
Using the long range matchfinder (`--long`) with high compression levels (16 and above) currently can cause regressions compared to not using the long mode at all. This is because enabling long mode will cause the matches found by the long range matchfinder to be blindly accepted. This PR changes that behavior, and makes each LDM found a candidate for the optimal parser instead.
This PR improves `--long` mode compression the most when `--long` mode is actually useful. `--patch-from` is a great example of `--long` mode being useful, so there are some nice benefits here. With this PR, `--patch-from` becomes even more competitive with `bsdiff` for generating small patches. The following results are fastest of three runs. 
**linux kernels tarballs (5.8 -> 5.9-rc7) : ~1GB dst**
| Name …
> Integrate long distance matches into optimal parser

- lib/common/mem.h
- lib/legacy/zstd_v01.c
- lib/legacy/zstd_v02.c
- lib/legacy/zstd_v03.c
- lib/legacy/zstd_v04.c
- lib/legacy/zstd_v05.c
- lib/legacy/zstd_v06.c
- lib/legacy/zstd_v07.c
- programs/timefn.h
When building `zstd` by **GCC 4.5.4** on **AIX 5.1** , GCC could not found `stdint.h`
> Fix building on AIX 5.1

- lib/common/zstd_internal.h
There are compilation environments in aarch64 where NEON isn't
available. While these environments could define ZSTD_NO_INTRINSICS,
it's more fail-safe to use the more specific symbol to know if NEON
extensions are available.
__ARM_NEON is the proper symbol, defined in ARM C Language Extensions
Release 2.1 (https://developer.arm.com/documentation/ihi0053/d/). Some
sources suggest __ARM_NEON__, but that's the obsolete spelling from
prior versions of the standard.
Signed-off-by: Warner Losh <imp@bsdimp.com>
> aarch64: use __ARM_NEON instead of __aarch64__ to control use of neon

- zlibWrapper/Makefile
previous recipe would build `*.o` object files directly within `programs/`.
This generation could be in competition with other local builds happening in `programs/` at the same time.
This could be triggered by a race condition while calling `make -j all`,
resulting in spurious build error, such as : https://github.com/facebook/zstd/pull/2359/checks?check_run_id=1259667696#step:3:323
fixed by generating the relevant object file locally.
> fix zwrapbench parallel build

- .travis.yml
`make -j all check` isn't really a valid way to invoke `make check`, and is the likely cause test failures like: https://travis-ci.org/github/facebook/zstd/jobs/736047280
Test: I'll do multiple re-runs of the travis CI test on this PR to see if fails.
> [travis CI] Change make -j all check to make -j all && make check

- lib/compress/zstd_ldm.c
@terrelln is currently working on more robust nondeterminism tests. One of the failures that showed up was in the LDM. 
The investigation revelaed that the LDM backwards match counting causes the nondeterminism. Essentially, the backwards match counting function will stop if it reaches the beginning of the circular buffer. However, we shouldn't stop if we reach the beginning - we should keep counting from the very end of the circular buffer once we reach the beginning since the backwards match might continue from the back. Note that the forward match counter already has this functionality.
The tests are yet to be merged, but if you want to check it out you can observe that if you run:
```
git remote add terrelln https://github.com/terrelln/zstd
git fetch terrelln
git checkout T77290931
cd …
```
> Fix nondeterministic LDM behavior in multithreading

- lib/compress/zstdmt_compress.c
- programs/fileio.c
Brought up in #2352. Since `cycleLog(chainLog)` is just `chainLog-1` if the compression strategy is `btlazy2` or higher. The effect of this change is that we use smaller jobsizes at higher compression levels with `--long`, allowing greater use of multithreading on files a few hundred megabytes large.
This PR also corrects an error in `FIO_adjustParamsForPatchFromMode()` related to `cycleLog()`.
| Conf        | dev, no `--long` | dev, `--long`: `MAX(21, chainLog+4)` | change_ldm_config, `--long`: `MAX(21, ZSTD_cycleLog(chainLog, strategy)+4` |
|-------------|------------------|--------------------------------------|----------------------------------------------------------------------|
| -22 wlog=27 | 29               | 30                                   | 30 …
> Reduce --long mode MT jobsize at higher levels

- tests/fuzz/.gitignore
- tests/fuzz/Makefile
Using a clean checkout of zstd, running `make` in tests/fuzz/ will currently fail, apparently unless you also run `make regressiontest` beforehand. I'm no Makefile expert, but I usually expect `make` to just work. So, this PR does three things:
- Adds `libregression.a` to the build targets in `fuzz/Makefile`
- Make clean now properly removes all the fuzz build targets and prints the usual message
- .gitignore is updated to include all the appropriate build artifacts, as well as transient ones that might stick around if you abort in the middle of `make`.
> [minor] Fix some /tests/fuzz Makefile annoyances

- tests/fuzzer.c
I noticed that at least locally, this test was taking > 5s to complete which is way over the average in `fuzzer.c`, so it probably belongs in "long tests".
All this PR does is move the test into the long tests section.
> Move ldm + opt parser no regression test to long tests

- .travis.yml
- appveyor.yml
- lib/dictBuilder/zdict.h
- programs/Makefile
Building the `zstd` CLI costs a non negligible time. It's not very long, but it's not instantaneous either.
The main reason is that several units (those in `lib/`) must be rebuilt _from source_ at every compilation.
Therefore, any change anywhere requires re-compilation of the entire `lib/` portion of `zstd`.
A better solution would be compile `*.o` object files, and link them.
And btw, that's what already happens for units in `programs/`
(though they only represent a small portion of total compilation time).
But we can't do that for units in `lib/` because, by default, `*.o` objects are stored alongside their `*.c` source.
And problem is, these object files are already created for the benefit of the static library,
which unfortunately uses different compilation flags.
Specifically, the …
> faster rebuild of zstd 

- lib/Makefile
Similar to [yesterday's PR](https://github.com/facebook/zstd/pull/2367),
this one makes it faster to rebuild `libzstd` after some minor source code change, enabling fast iterations.
The method is also similar: link `%.o` object files, instead of compiling from `%.c` source every time.
This was already the case for the static `libzstd.a`, but not for the dynamic `libzstd.so`, which had to be rebuilt entirely from source every time.
Reason is : by default, each `%.o` is generated alongside its corresponding `%.c` source file, so there is only space for one. 
And since the dynamic and static libraries do not use the same compilation flags (specifically, the dynamic library _requires_ Position Independent Code, while static _must not_ use it), only one get to produce `%.o` object file.
This …
> faster rebuild of libzstd

- lib/compress/zstd_compress.c
- lib/compress/zstd_ldm.c
- lib/compress/zstd_ldm.h
#2341 introduced some issues in OSS-Fuzz. This PR fixes those issues.
The root cause was that sometimes we could begin an LDM compression job without having a "clean" `rawSeqStore` to begin with - i.e., the `posInSequence` value was not set to 0 during `ZSTD_referenceExternalSequences()`, which could cause the opt parser to integrate some LDMs that weren't in the right position.
Luckily, the blame PR already included an assert made debugging this much easier: `assert(optLdm->seqStore.posInSequence <= currSeq.litLength + currSeq.matchLength)`
Now, it's not entirely clear to me what the best way is to test/catch this specific case earlier - would appreciate any suggestions
1) I don't think `assert(pos == 0 && posInSequence == 0)` in the code that follows the call to …
> Fix long distance matcher OSS-fuzz issue

- lib/compress/zstd_compress.c
- lib/compress/zstdmt_compress.c
- lib/zstd.h
- tests/fuzzer.c
Since the LDM can no longer cause compressed size regressions, and at worst, is only a tiny bit slower than without LDM at `btopt+` compression strategies (benchmarks in #2341), let's enable long mode by default when the window size is greater than 128 MB and we're using the `btopt+` strategies.
It seems this is about as far upstream in the compression codepath as it makes sense to do this change, and even then, MT and single-thread have to be dealt with separately, and `ZSTD_makeCCtxParamsFromCParams()` must get updated as well.
Tests:
- Unit test included in `fuzzer.c` to ensure this doesn't modify the user's requested params in the `cctx`
- Tested locally to make sure that LDM gets enabled with the specified conditions.
> Enable LDM by default if window size >= 128MB and strategy uses opt parser

- lib/compress/zstdmt_compress.c
- lib/compress/zstdmt_compress.h
- tests/Makefile
- tests/fuzzer.c
- tests/zstreamtest.c
* Remove `singleBlockingThread` mode because it is already handled in `zstd_compress.c`.
* Remove the single-pass shortcut fixing Issue #2327.
* Rip out all unused functions from the zstdmt API. Delete the `zstreamtest --mt` test. Rewrite unit tests to use the zstd API.
* Rewrite the `zstreamtest` fuzzer loop to check for compression determinism. It had to be rewritten to always make maximal forward progress to ensure determinism in multithreading mode.
Bug fixes (the last 2 commits: see commit messages):
* Zstdmt would create empty compression jobs when called with `ZSTD_e_end` and when it can't get an input buffer. It would also incorrectly set `mtctx->frameEnded = 1`, which could cause other issues, like an unterminated frame. The fix is to move the switch to `ZSTD_e_flush` outside of …
> Fix zstdmt stability issues and clean up the zstdmt code

- tests/fuzzer.c
OSS Fuzz exposed a bug in the LDM that was fixed in #2362 - this PR adds a test case for the specific failure: compressing with LDM + opt parser in streaming mode with a flush that contains a small, uncompressible block, followed by another compression.
Test Plan:
- Verified that this test will fail on versions of zstd prior to #2362, but passes after that PR was merged.
- Spot-checked to make sure we have the exact same issue (`rawSeqStore::posInSequence` fails to advance fully).
> Add a test case for LDM + opt parser with small uncompressible block

- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/zstd.h
- tests/fuzzer.c
This PR modifies the public-facing `ZSTD_Sequence` API. This will make it easier to integrate with the upcoming sequence compression API.
- Removes unnecessary field `matchPos` from `ZSTD_Sequence` and adjusts member `rep` to make more sense.
- Changes `ZSTD_getSequences()` to provide last literals (rather than ignoring them).
- Improves documentation regarding the `ZSTD_Sequence` as well as some internal definitions.
- Adjusts/fixes existing related unit tests.
Test Plan:
- Unit test for sequence extraction modified to suit new definitions
- Spot checking on multiple files that even with modifications, `ZSTD_getSequences()` outputs the exact same output, with the only difference being the value of 'rep' (we no longer allow `rep == 4`).
> Refine external ZSTD_Sequence API

- lib/common/error_private.c
- lib/common/zstd_errors.h
- lib/common/zstd_internal.h
- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/compress/zstd_cwksp.h
- lib/decompress/zstd_decompress.c
- lib/decompress/zstd_decompress_internal.h
- lib/zstd.h
- tests/zstreamtest.c
This completes all the tasks in Issue #2353 except hooking up zstdmt. See each commit for summaries. Each one hooks up / optimizes one thing.
This saves allocations in `ZSTD_compress2()`, and saves `memcpy()` calls when `dstCapacity < ZSTD_compressBound(srcSize)`.
Let me know what you think of this methodology. I'm happy with everything except in `ZSTD_compress2()`, where I temporarily enable stable in/out buffers, and then reset to the original values. This could be accomplished with a different flush value instead, like `ZSTD_e_singlePass`, which modifies the `appliedParams` to stable in/out only. But, then that would be part of the stable API for users.
I've added unit tests for: ZSTD_compress2(), stable in & out, only stable in, only stable out.
> Add ZSTD_c_stable{In,Out}Buffer and optimize when set

- tests/regression/README.md
- tests/regression/results.csv
#2339 removes the single-pass zstdmt API.
This changes the compressed size, because we no longer take the # of threads into
account when deciding the job size.
Add a README to explain how to update `results.csv`.
> [regression] Updates results.csv & add README

- programs/fileio.c
#2042 brought up LGTM static analysis: https://lgtm.com/projects/g/facebook/zstd/?mode=list&severity=recommendation
Looks like one really minor thing here just maybe worth addressing : just passing a large struct by const reference instead of by value.
> [minor] Pass cRess_t by const ptr instead of by value

- doc/zstd_manual.html
- lib/compress/zstd_compress.c
- lib/zstd.h
- tests/fuzzer.c
Recreating https://github.com/facebook/zstd/pull/2383 as I used the wrong email address in the commits.
I've squashed them down to a single commit and moved the new function to the experimental section as requested in the previous PR.
> Add ZSTD_getDictID_fromCDict function to experimental section

- lib/compress/zstd_compress.c
- lib/compress/zstd_compress_internal.h
- lib/zstd.h
- tests/fuzzer.c
Currently, `ZSTD_getSequences()` emits an array of sequences with delimiters (in the form of sequences with `offset = 0, matchLength = 0` for block boundaries and last literals. We add the capability to emit sequences in a more "raw" form with no explicit block boundaries or last literals. 
This will be a "mode" of `ZSTD_Sequence` that the sequence compression API must be able to handle, so we should add the capability to extract sequences in this format via `ZSTD_getSequences()`.
This PR:
- Adds a new enum type to `zstd.h` that defines modes of sequence extracting/ingestion
- Extends the `ZSTD_getSequences()` function to support the new mode
- Updates the relevant docs
Test Plan:
- Include new mode in `fuzzer.c` unit test.
- Manual spot checking to ensure that output looks as expected.
> Add enum to define ZSTD_Sequence type and update sequence extraction API

- lib/compress/zstd_compress.c
- tests/fuzzer.c
The repcode handling logic was slightly off in the original version of this API - this PR aims to fix it by: 1) Keeping track of a dedicated repcode array, and 2) Persist the repcodes array through each block. I've aimed to make the handling logic as clear to read as possible since we will need a similar process in the sequence compression API.
Test Plan:
- Manual spot checking (roundtrips silesia.tar with compression api)
- Modify the unit test. Previously, it turns out that setting the `litProbability` field to something like 0.5 in the `RDG_genBuffer()` function would almost always cause the unit test to fail. With this PR, it no longer does.
> Improve repcode handling in sequence extraction API

- lib/compress/zstd_compress.c
Clickbait title, but I noticed that `ZSTD_isRLE()` is unoptimized. @terrelln suggested unrolling the loop and showed me an unrolled version of `ZSTD_isRLE()` that's much faster (most of the code here he wrote!), and I've made some minor tweaks.
Using `fullbench.c` to do a microbenchmark on just the function with a buffer of all 0:
Raw input: 1000 bytes 
Old version: ~3700MB/s
New version: ~35000MB/s
Raw input: 100000 bytes
Old version: ~4500MB/s
New version: ~45000MB/s
And actual compression:
When compressing a file of all 'a', 150K, compression level 1:
Old version: ~10000MB/s
New version: ~14000MB/s
When compressing a file of all 'a', 7MB, compression level 1:
Old version: ~3000MB/s
New version: ~11000MB/s
These not really realistic files, but as expected, compression speed is a bit …
> 10x speedup for ZSTD_isRLE()

- tests/fuzz/.gitignore
- tests/fuzz/Makefile
- tests/fuzz/fuzz.py
- tests/fuzz/sequence_compression_api.c
This PR is rebased on top of #2387.
This adds a fuzzer for the new sequence compression API. Basically, the fuzzer generates some arbitrary, valid sequences based on some literal buffer, generates the source based on the sequences, and asks `ZSTD_compressSequences()` to roundtrip this source.
What is the process for adding this to OSS-Fuzz and properly integrating it into the fuzzer libraries/systems? Seems like something needs to be uploaded/downloaded.
Followups:
- Add fuzzing for sequences with block delimiter
- Add fuzzing for externally provided arbitrary repcodes (once `ZSTD_compressSequences()` supports it)
> Fuzzer for sequence compression API

- tests/fuzz/sequence_compression_api.c
OSS Fuzz found an issue with the sequence compression API. Root cause is in the fuzzer's sequence generator itself.
The sequence generator can generate match lengths between `ZSTD_MINMATCH_MIN` and some maximum allowable matchlength. However, at compression time, the value of `cParams.minMatch` will change depending on the `cctx` generated. 
So, prior to this change, it could have been the case that the fuzzer's sequence generator could generate matches of length `ZSTD_MINMATCH_MIN`, while than the actual value of `cParams.minMatch` in the cctx could be higher, which could cause issues further down the line (since the `seqStore::maxNbSeq` is sized partially based on the size of `minMatch).
By always setting the value of `minMatch` in the `cctx` to the same as what the sequence generator …
> [OSS-Fuzz] Make sequence compression fuzzer's generated minmatch to be same as CCtx's minmatch

- programs/util.c
gcc10 doesn't like its own `strncpy()`
which is problematic for tests requiring zero warning.
> fix gcc10 warnings

- .github/workflows/generic-release.yml
- .travis.yml
- tests/playTests.sh
- added tests presumed to break lz4 console detection
(note : it indeed writes garbage into console, but doesn't produce an "error" signal on github actions)
- fix broken lz4 test
fix #2400
> fix lz4 compatibility test broken in docker

- build/cmake/CMakeLists.txt
This has to do with a deprecated policy with the recent release of cmake 3.19.1. A policy about `INTERFACE_LINK_LIBRARIES` has been deprecated for versions `< 2.8.12`. The deprecation will produce warnings if an older version is used, or the policy is set to `OLD`. 
More info about the deprecated policy:
https://cmake.org/cmake/help/latest/policy/CMP0022.html
Signed-off-by: Stephen Brawner <brawner@gmail.com>
> Update cmake_minimum_required to 2.8.12

- lib/Makefile
The result of building lib under Windows Subsystem for Linux is dlllibzstd.dll in lib folder, not libzstd.dll in lib/dll as expected.
```
zstd/lib$ make CC=x86_64-w64-mingw32-gcc TARGET_SYSTEM=Windows_NT all
compiling dynamic library 1.4.5
x86_64-w64-mingw32-gcc ... -Wl,--out-implib,dll\libzstd.dll.a -shared ... -o dll\libzstd.dll
zstd/lib$ ls *.dll
dlllibzstd.dll
```
Seems like a slash instead of a backslash should work everywhere.
> Fix dll path in case of cross-compilation

- lib/compress/zstd_compress.c
We should not be comparing total number of sequences given to the max number of sequences allowed in the seqStore.
Instead, we should compare the number of sequences per block to the max number of sequences allowed in the seqStore.
Test Plan:
- Validated that change fixed OSS Fuzz issue.
> [oss-fuzz] Move sequence compression API nbSequences check

- doc/zstd_manual.html
- lib/zstd.h
- tests/Makefile
This was intended as a larger refactor of `tests/Makefile`,
but as I'll get busy in the next days,
I figure it's fine to merge what's already available.
Mostly minor refactoring stuff : 
- remove targets and options which are irrelevant and broken
- make better use of implicit rules
- fix API manual formatting
> Minor refactor

- contrib/linux-kernel/Makefile
- contrib/linux-kernel/decompress_sources.h
- contrib/linux-kernel/linux_zstd.h
- contrib/linux-kernel/test/Makefile
- contrib/linux-kernel/test/include/linux/module.h
- contrib/linux-kernel/test/static_test.c
- contrib/linux-kernel/test/test.c
- contrib/linux-kernel/zstd_compress_module.c
- contrib/linux-kernel/zstd_decompress_module.c
- lib/compress/zstd_compress.c
Adds the linux wrapper API. It is a functionally equivalent subset of the current API in the linux kernel. The only difference is name changes and taking parameter structs by const pointer instead of value. It preserves exactly the same semantics.
> [linux] Add the linux wrapper API

- lib/compress/zstd_compress.c
- tests/zstreamtest.c
`ZSTDMT_compressStream()` doesn't **guarantee** that it makes progress every iteration. It guarantees it won't enter a busy waiting loop, but it may loop for a few iterations before it blocks, under the right circumstances.
There are two solutions:
1. Add a loop inside of `ZSTDMT_compressStream()` that loops until progress is made.
2. Modify the loop already in `ZSTD_compressStream()` to wait for progress with `ZSTD_e_continue`.
I've chosen the second approach, because we already had to call `ZSTDMT_compressStream()` in a loop for `ZSTD_e_flush` and `ZSTD_e_end`. Now, we will also call it in a loop for `ZSTD_e_continue`, and wait for some progress.
The determinism test caught this bug because of its odd loop condition. It loops until no forward progress is made, and it assumes that the …
> [lib] Ensure that multithreaded compression always makes some progress

- lib/dictBuilder/zdict.c
This PR is questionable.
Should use `ZSTD_CLEVEL_DEFAULT` in `zdict.c` file?
For example:
1, A man sets `ZSTD_CLEVEL_DEFAULT = 6` in his build.
2, He uses public function `ZDICT_trainFromBuffer()` to train a dictionary.
3, He gives the dictionary to others.
Then this dictionary has a non-standard level, is this ok?
> use ZSTD_CLEVEL_DEFAULT in zdict.c

- lib/common/entropy_common.c
- lib/common/huf.h
- lib/compress/huf_compress.c
- lib/compress/zstd_compress_internal.h
- tests/decodecorpus.c
- zlibWrapper/zstd_zlibwrapper.c
by exposing `HUF_CElt` declaration, as suggested by @terrelln
> fix gcc-10 strict aliasing warnings

- .github/workflows/generic-dev.yml
Intel-oneapi doesn't exist anymore. Instead, it looks like it's been split into specific packages. Just needed to install the new ones:)
> [build] Fix icc build. Using updated ubuntu packages

- Makefile
- contrib/seekable_format/tests/.gitignore
- contrib/seekable_format/tests/Makefile
- contrib/seekable_format/tests/seekable_tests.c
- contrib/seekable_format/zstdseek_decompress.c
Issue #2335 from @mdittmer noted that seekable decompress can hang, and provided a useful repro in #2334
The root cause is in the main loop of `ZSTD_seekable_decompress()`, which can get stuck in an infinite loop if `zs->decompressedOffset` never increases, and the initial `offset != 0`. 
Since the decompressed offset never increases, we will execute code from lines `385-395`, which resets the stream object, so when we finish decompressing the whole buffer, we will just start all over again, into infinity.
So here, I add a requirement (similar to the `ZSTD_decompressStream()` API) where after a certain number of consecutive times where no forward progress is made, we bail out. 
It's not clear to me if it's ever valid to have many consecutive calls where no progress is made, and if so, …
> Remove possibility of hanging when using seekable decompression

- tests/paramgrill.c
Some additional warnings on paramgrill pop up with: `-Wconversion -m32` - this PR addresses those warnings.
> Fix various paramgrill conversion warnings

- lib/compress/zstd_compress.c
- lib/compress/zstd_cwksp.h
Addresses #2286.
Pretty straightforward, we keep the redzones when built with ASAN so the size estimation code still works, but disable poisoning and unpoisoning when the workspace is statically allocated. We still do MSAN poisoning though, which should be safe.
> Don't ASAN-Poison Statically-Allocated Workspaces

- build/cmake/lib/CMakeLists.txt
- lib/Makefile
- lib/libzstd.pc.in
Instead of using `sed` to manipulate the lib and include dirs, this PR causes make and cmake to use their native language features to compare the `prefix` /`exec_prefix` to the prefix of those paths, and if they match, rewrite that prefix into a reference to the `prefix`/`exec_prefix` variables.
This means that if `includedir` and `libdir` are not children of `prefix`/`exec_prefix`, we'll fall back to just emitting a whole, absolute path, rather than failing.
This PR addresses #2192 and #2312.
> Don't Use Regexes to Build Pkg-Config File

- .github/workflows/generic-dev.yml
- appveyor.yml
- build/cmake/lib/CMakeLists.txt
- build/cmake/tests/CMakeLists.txt
- tests/playTests.sh
* Fix quoting in the cmake files. Some places needed quotes, some places needed the quotes removed.
* Fix the `zstdgrep` tests in `playTests.sh`.
* Add a test case that tests the cmake build with spaces in the repo path.
Fixes #2255.
> [cmake] Fix source directory with spaces

- lib/Makefile
- programs/Makefile
In some circumstances, links can have a slightly different behavior from real binaries,
which can potentially break a few scripts relying on "real binary" assumption.
remove this risk by copying the actual binary to final destination.
> replace links by actual copies

- CHANGELOG
CHANGELOG doesn't have date, which is a bit inconvenient for readers.
The dates are from https://github.com/facebook/zstd/releases, I checked them twice.
v0.7.0 is missing in that page, so I used v0.7.0 tag's date.
> add release dates to CHANGELOG

- programs/dibio.c
good day.
there is probably a bug in your code. type conversion (unsigned long long) will be performed after integer overflow. 
so I suggest a simple fix.
> fix Integer Overflow

- CHANGELOG
- doc/zstd_manual.html
- lib/zstd.h
- programs/zstd.1
- programs/zstdgrep.1
- programs/zstdless.1
@felixhandte , @terrelln , @senhuang42 ,
please have a look to make sure that all topics you want to be mentioned are effectively present.
A few additional notes : 
- the next release is presumed to be numbered `v1.4.7`.
This will automatically bring the question "what about `v1.4.6` ?".
I think we can mention that `v1.4.6` is a non-public release.
If that feels too much hassle, we could also decide to call _this_ coming release `v1.4.6`,
though we will then need another discriminant to differentiate from the kernel release.
+ Note that the next action is to update source code and documentation to `v1.4.7` if this is the preferred choice
(likely a follow-up commit in this PR).
- My bullet-point list (`v1.4.7`) is not as dense as the `v1.4.6` one.
I only care to mention changes which are …
> Updated CHANGELOG for v1.4.7

- contrib/seekable_format/zstd_seekable.h
- contrib/seekable_format/zstdseek_decompress.c
Memory constrained use cases that manage multiple archives benefit from
retaining multiple archive seek tables without retaining a `ZSTD_seekable`
instance for each.
* New opaque type for seek table:` ZSTD_seekTable`.
* `ZSTD_seekable_copySeekTable()` supports copying seek table out of a
`ZSTD_seekable`.
* `ZSTD_seekTable_[eachSeekTableOp]()` defines seek table API that mirrors
existing seek table operations.
* Existing `ZSTD_seekable_[eachSeekTableOp]()` retained; they delegate to
`ZSTD_seekTable` the variant.
These changes allow the above-mentioned use cases to initialize a
`ZSTD_seekable`, extract its `ZSTD_seekTable`, then throw the `ZSTD_seekable`
away to save memory. Standard ZSTD operations can then be used to
decompress frames based on seek table offsets.
The copy and delegate …
> [contrib] Support seek table-only API
